Repository timescale/timescaledb, pull requests merged in 2018-02, with the labels that each got.

#420 Migrate table data when creating a hypertable
  sql/ddl_api.sql
  sql/updates/pre-0.8.0--0.9.0-dev.sql
  src/copy.c
  src/copy.h
  src/hypertable.c
  src/indexing.c
  src/indexing.h
  test/expected/create_hypertable.out
  test/sql/create_hypertable.sql
Labels: docs-pipeline, docs-update-needed, enhancement

#427 Release 0.9.0
  CHANGELOG.md
  sql/timescaledb--0.8.0--0.9.0.sql
  sql/updates/post-0.8.0--0.9.0.sql
  sql/updates/pre-0.8.0--0.9.0.sql
  test/expected/drop_extension.out
  version.config
Labels: release

#436 Fix handling of custom SQL-based partitioning functions
  src/partitioning.c
  test/expected/partitioning.out
  test/sql/partitioning.sql
Labels: limitation

#438 Remove unused cache invalidation triggers
  sql/CMakeLists.txt
  sql/cache.sql
  sql/cache_functions.sql
  sql/timescaledb--0.8.0--0.9.0.sql
  sql/trigger_functions.sql
  sql/updates/pre-0.8.0--0.9.0.sql
  src/cache_invalidate.c
  src/catalog.h
  src/compat.c
  test/expected/pg_dump.out
Labels: cleanup, enhancement

#441 Refactor/simplify update scripts and build process
  sql/CMakeLists.txt
  sql/ddl_triggers.sql
  sql/permissions.sql
  sql/schemas.sql
  sql/tables.sql
  sql/timescaledb--0.1.0--0.2.0.sql
  sql/timescaledb--0.2.0--0.3.0.sql
  sql/timescaledb--0.3.0--0.4.0.sql
  sql/timescaledb--0.4.0--0.4.1.sql
  sql/timescaledb--0.4.1--0.4.2.sql
  sql/timescaledb--0.4.2--0.5.0.sql
  sql/timescaledb--0.5.0--0.6.0.sql
  sql/timescaledb--0.6.0--0.6.1.sql
  sql/timescaledb--0.6.1--0.7.0.sql
  sql/timescaledb--0.6.1--0.7.1.sql
  sql/timescaledb--0.7.0--0.7.1.sql
  sql/timescaledb--0.7.1--0.8.0.sql
  sql/timescaledb--0.8.0--0.9.0.sql
  sql/trigger_functions.sql
  sql/updates/0.1.0--0.2.0.sql
  sql/updates/0.2.0--0.3.0.sql
  sql/updates/0.3.0--0.4.0.sql
  sql/updates/0.4.2--0.5.0.sql
  sql/updates/0.5.0--0.6.0.sql
  sql/updates/0.6.1--0.7.0.sql
  sql/updates/0.7.0--0.7.1.sql
  sql/updates/0.7.1--0.8.0.sql
  sql/updates/0.8.0--0.9.0.sql
  sql/updates/README.md
  sql/updates/post-0.1.0--0.2.0.sql
  sql/updates/post-0.3.0--0.4.0.sql
  sql/updates/post-0.4.0--0.4.1.sql
  sql/updates/post-0.4.1--0.4.2.sql
  sql/updates/post-0.4.2--0.5.0.sql
  sql/updates/post-0.5.0--0.6.0.sql
  sql/updates/post-0.6.0--0.6.1.sql
  sql/updates/post-0.6.1--0.7.0.sql
  sql/updates/post-0.7.0--0.7.1.sql
  sql/updates/post-0.7.1--0.8.0.sql
  sql/updates/post-0.8.0--0.9.0.sql
  sql/updates/pre-0.2.0--0.3.0.sql
  sql/updates/pre-0.4.0--0.4.1.sql
  sql/updates/pre-0.4.1--0.4.2.sql
  sql/updates/pre-0.4.2--0.5.0.sql
  sql/updates/pre-0.5.0--0.6.0.sql
  sql/updates/pre-0.6.0--0.6.1.sql
  sql/updates/pre-0.6.1--0.7.0.sql
  sql/updates/pre-0.7.1--0.8.0.sql
  sql/updates/pre-0.8.0--0.9.0.sql
  sql/updates/pre-global.sql
  src/CMakeLists.txt
  src/compat.c
Labels: cleanup, refactoring

#443 Update README to emphasize checking out tagged commit
  README.md
Labels: documentation

#444 Fix update scripts for version 0.6.1
  sql/CMakeLists.txt
  sql/updates/0.6.1--0.7.0.sql
  sql/updates/0.7.0--0.7.1.sql
  sql/updates/0.7.0.sql
  sql/updates/README.md
Labels: bug
