Repository timescale/timescaledb, pull requests merged in 2018-07, with the labels that each got.

#578 Add support for changing chunk schema and name
  src/chunk.c
  src/chunk.h
  src/process_utility.c
  test/expected/alter.out
  test/sql/alter.sql
Labels: bug

#575 Release cache pin memory
  src/cache.c
Labels: bug

#588 Fix bug where dropping triggers caused dangling references in pg_depe…
  sql/updates/0.10.0--0.11.0-dev.sql
  src/process_utility.c
  test/expected/triggers.out
  test/sql/triggers.sql
Labels: bug

#591 Release 0.10.1
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/0.10.0--0.10.1.sql
  version.config
Labels: release

#587 Improve version checking
  .travis.yml
  src/compat.h
  src/extension.c
  src/extension.h
  src/init.c
Labels: docs-update-needed

#608 Remove unused files from scripts/
  scripts/setup-db.sh
  scripts/sql/setup_sample_hypertable.psql
Labels: cleanup

#624 Block NO INHERIT constraints on hypertables
  src/chunk_constraint.c
  src/hypertable.c
  src/process_utility.c
  test/expected/constraint.out
  test/sql/constraint.sql
Labels: bug, enhancement
