Repository timescale/timescaledb, pull requests merged in 2018-12, with the labels that each got.

#639 Add support for functions on open (time) dimensions
  sql/ddl_api.sql
  sql/updates/1.0.1--1.1.0-dev.sql
  sql/util_internal_table_ddl.sql
  src/dimension.c
  src/dimension.h
  src/hypertable.c
  src/hypertable_restrict_info.c
  src/indexing.c
  src/partitioning.c
  src/partitioning.h
  test/expected/create_hypertable.out
  test/expected/partitioning.out
  test/expected/plan_expand_hypertable_optimized.out
  test/expected/plan_hashagg_optimized-10.out
  test/expected/plan_hashagg_optimized-9.6.out
  test/expected/sql_query_results_optimized.out
  test/expected/sql_query_results_unoptimized.out
  test/expected/sql_query_results_x_diff.out
  test/sql/create_hypertable.sql
  test/sql/include/plan_expand_hypertable_load.sql
  test/sql/include/plan_expand_hypertable_query.sql
  test/sql/include/plan_hashagg_load.sql
  test/sql/include/plan_hashagg_query.sql
  test/sql/include/sql_query_results.sql
  test/sql/partitioning.sql
Labels: docs-update-needed, enhancement, limitation, update-script

#905 Release 1.1.0
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/1.0.1--1.1.0.sql
  version.config
Labels: release

#904 Use create_upper_paths_hook for hypertable insert plan modifications
  src/CMakeLists.txt
  src/chunk_dispatch_plan.c
  src/chunk_dispatch_plan.h
  src/hypertable_insert.c
  src/hypertable_insert.h
  src/plan_add_hashagg.c
  src/planner.c
  src/planner_utils.c
  src/planner_utils.h
  test/expected/insert.out
  test/expected/insert_single.out
  test/expected/rowsecurity-10.out
  test/expected/rowsecurity-11.out
  test/expected/rowsecurity-9.6.out
Labels: clustering, enhancement

#917 Update README with tools and other fixes
  README.md
Labels: documentation
