Repository timescale/timescaledb, pull requests merged in 2018-11, with the labels that each got.

#832 [Documentation Only Change] Document timescales loading procedure
  src/loader/loader.c
Labels: documentation

#772 Refactor scanner callback interface
  src/bgw/job.c
  src/bgw/job_stat.c
  src/chunk.c
  src/chunk_constraint.c
  src/chunk_index.c
  src/dimension.c
  src/dimension_slice.c
  src/hypertable.c
  src/hypertable_cache.c
  src/installation_metadata.c
  src/scanner.c
  src/scanner.h
  src/tablespace.c
Labels: enhancement

#862 Add view to show hypertable information
  sql/CMakeLists.txt
  sql/views.sql
  test/expected/loader.out
  test/expected/pg_dump.out
  test/expected/views.out
  test/pgtest/CMakeLists.txt
  test/sql/CMakeLists.txt
  test/sql/loader.sql
  test/sql/views.sql
Labels: docs-update-needed
