Repository timescale/timescaledb, pull requests merged in 2019-06, with the labels that each got.

#1263 Remove space partition restriction from ordered append
  src/chunk_append/chunk_append.c
  src/hypertable_restrict_info.c
  src/plan_expand_hypertable.c
  test/expected/plan_ordered_append-10.out
  test/expected/plan_ordered_append-11.out
  test/expected/plan_ordered_append-9.6.out
  test/sql/include/plan_ordered_append_load.sql
  test/sql/include/plan_ordered_append_query.sql
Labels: fixup

#1260 Update release notes for 1.3.1
  CHANGELOG.md
Labels: documentation

#1283 Fix constraint exclusion for OUTER JOIN
  CHANGELOG.md
  src/plan_expand_hypertable.c
  test/expected/plan_expand_hypertable-10.out
  test/expected/plan_expand_hypertable-11.out
  test/expected/plan_expand_hypertable-9.6.out
  test/sql/include/plan_expand_hypertable_query.sql
Labels: bug, planner

#1284 Release 1.3.1
  sql/CMakeLists.txt
  sql/updates/1.3.0--1.3.1.sql
  version.config
Labels: release

#1273 Propagate quals to joined hypertables
  CHANGELOG.md
  src/plan_expand_hypertable.c
  test/expected/delete.out
  test/expected/plan_expand_hypertable-10.out
  test/expected/plan_expand_hypertable-11.out
  test/expected/plan_expand_hypertable-9.6.out
  test/expected/plan_ordered_append-10.out
  test/expected/plan_ordered_append-11.out
  test/expected/plan_ordered_append-9.6.out
  test/expected/update.out
  test/sql/include/plan_expand_hypertable_load.sql
  test/sql/include/plan_expand_hypertable_query.sql
Labels: minor-feature, performance, planner

#1288 Do not remove Result nodes with one-time filter
  src/constraint_aware_append.c
Labels: bug

#1290 Test continuous aggs with extension updates
  scripts/test_updates_pg10.sh
  scripts/test_updates_with_constraints.sh
  test/sql/updates/post.continuous_aggs.sql
  test/sql/updates/post.v3.sql
  test/sql/updates/setup.continuous_aggs.sql
  test/sql/updates/setup.v3.sql
Labels: continuous-aggs, testing

#1299 Fix Datum to int cast issue
  .travis.yml
  src/plan_expand_hypertable.c
Labels: bug

#1309 Skip runtime exclusion when Param is not partitioning column
  src/chunk_append/chunk_append.c
  src/hypertable.c
  src/hypertable.h
  test/expected/append-10.out
  test/expected/append-11.out
  test/expected/append-9.6.out
  test/sql/include/append_query.sql
Labels: fixup

#1296 Expose a function cache for query optimizations
  src/CMakeLists.txt
  src/estimate.c
  src/estimate.h
  src/func_cache.c
  src/func_cache.h
  src/plan_add_hashagg.c
  src/plan_add_hashagg.h
  src/sort_transform.c
  src/sort_transform.h
Labels: cleanup, enhancement, refactoring

#1315 Fix potentially lost invalidations in continuous aggs
  tsl/src/continuous_aggs/insert.c
Labels: bug

#1310 Fix Order display in ChunkAppend EXPLAIN
  src/chunk_append/explain.c
  test/expected/plan_ordered_append-10.out
  test/expected/plan_ordered_append-11.out
  test/expected/plan_ordered_append-9.6.out
  test/sql/include/plan_ordered_append_query.sql
Labels: fixup

#1257 Support for multiple continuous aggregates
  sql/pre_install/tables.sql
  sql/updates/latest-dev.sql
  src/catalog.c
  src/catalog.h
  src/continuous_agg.c
  test/expected/drop_rename_hypertable.out
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/materialize.c
  tsl/src/continuous_aggs/materialize.h
  tsl/test/expected/continuous_aggs.out
  tsl/test/expected/continuous_aggs_ddl-10.out
  tsl/test/expected/continuous_aggs_ddl-11.out
  tsl/test/expected/continuous_aggs_ddl-9.6.out
  tsl/test/expected/continuous_aggs_multi.out
  tsl/test/isolation/expected/continuous_aggs_insert.out
  tsl/test/isolation/expected/continuous_aggs_multi.out
  tsl/test/isolation/specs/CMakeLists.txt
  tsl/test/isolation/specs/continuous_aggs_insert.spec
  tsl/test/isolation/specs/continuous_aggs_multi.spec
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/continuous_aggs.sql
  tsl/test/sql/continuous_aggs_ddl.sql.in
  tsl/test/sql/continuous_aggs_multi.sql
  tsl/test/src/test_continuous_aggs.c
Labels: continuous-aggs, minor-feature

#1317 Support time bucket functions in Ordered Append
  src/chunk_append/chunk_append.c
  src/planner.c
  test/expected/append-10.out
  test/expected/append-11.out
  test/expected/append-9.6.out
  test/expected/plan_ordered_append-10.out
  test/expected/plan_ordered_append-11.out
  test/expected/plan_ordered_append-9.6.out
  test/expected/query.out
  test/expected/sort_optimization-10.out
  test/expected/sort_optimization-11.out
  test/expected/sort_optimization-9.6.out
  test/sql/include/plan_ordered_append_query.sql
Labels: minor-feature, performance, planner

#1322 CMake check for necessary testing tools
  CMakeLists.txt
  appveyor.yml
  scripts/docker-build.sh
  scripts/docker-run-abi-test.sh
  test/CMakeLists.txt
  test/expected/metadata.out
  test/sql/metadata.sql
  test/test-defs.cmake
  tsl/test/CMakeLists.txt
Labels: enhancement
