Repository timescale/timescaledb, pull requests merged in 2019-05, with the labels that each got.

#1200 Coverity fixes for 1.3
  src/plan_expand_hypertable.c
  src/planner.c
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/insert.c
  tsl/src/continuous_aggs/materialize.c
Labels: bug

#1201 Add telemetry for policies: drop_chunk & reorder
  src/bgw_policy/drop_chunks.c
  src/bgw_policy/drop_chunks.h
  src/bgw_policy/reorder.c
  src/bgw_policy/reorder.h
  src/telemetry/telemetry.c
  test/expected/telemetry.out
  tsl/test/expected/bgw_reorder_drop_chunks.out
  tsl/test/sql/bgw_reorder_drop_chunks.sql
Labels: docs-update-needed

#1183 Handle NULL in a check constraint name
  src/process_utility.c
  test/expected/constraint.out
  test/sql/constraint.sql
Labels: bug

#1211 Release 1.3.0
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/1.2.2--1.3.0.sql
  sql/updates/latest-dev.sql
  version.config
Labels: release

#1220 Fix detecting JOINs for continuous aggs
  CHANGELOG.md
  tsl/src/continuous_aggs/create.c
  tsl/test/expected/continuous_aggs_errors.out
  tsl/test/sql/continuous_aggs_errors.sql
Labels: bug, continuous-aggs

#1233 Add missing ORDER BY to test query
  test/expected/copy.out
  test/expected/delete.out
  test/expected/insert.out
  test/expected/pg_dump.out
  test/sql/copy.sql
  test/sql/delete.sql
  test/sql/insert.sql
  test/sql/pg_dump.sql
Labels: bug, testing

#1221 Fix segfault in VACUUM on PG11
  src/process_utility.c
Labels: bug

#1236 Stop preventing REFRESH in transaction blocks
  src/process_utility.c
Labels: bug, continuous-aggs

#1244 Fix partitionwise aggregates on PG 11.3
  src/plan_expand_hypertable.c
Labels: fixup

#1228 Pass int64 using Int64GetDatum when a Datum is required
  src/utils.c
  test/src/test_time_to_internal.c
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/materialize.c
  tsl/test/src/test_continuous_aggs.c
Labels: bug

#1230 Add chunk append node and use it for ordered append
  src/CMakeLists.txt
  src/chunk_append/CMakeLists.txt
  src/chunk_append/chunk_append.c
  src/chunk_append/chunk_append.h
  src/chunk_append/exec.c
  src/chunk_append/exec.h
  src/chunk_append/planner.c
  src/chunk_append/planner.h
  src/chunk_append/transform.c
  src/chunk_append/transform.h
  src/chunk_dispatch_plan.c
  src/compat.h
  src/constraint_aware_append.c
  src/guc.c
  src/guc.h
  src/hypertable_insert.c
  src/hypertable_restrict_info.c
  src/hypertable_restrict_info.h
  src/init.c
  src/plan_expand_hypertable.c
  src/plan_ordered_append.c
  src/plan_ordered_append.h
  src/planner.c
  src/planner.h
  src/planner_import.c
  src/planner_import.h
  test/expected/agg_bookends_optimized-10.out
  test/expected/agg_bookends_optimized-11.out
  test/expected/agg_bookends_optimized-9.6.out
  test/expected/append.out
  test/expected/multi_transaction_index.out
  test/expected/plan_expand_hypertable-10.out
  test/expected/plan_expand_hypertable-11.out
  test/expected/plan_expand_hypertable-9.6.out
  test/expected/plan_ordered_append-10.out
  test/expected/plan_ordered_append-11.out
  test/expected/plan_ordered_append-9.6.out
  test/expected/sql_query-10.out
  test/expected/sql_query-11.out
  test/expected/sql_query-9.6.out
  test/expected/sql_query_results_optimized-10.out
  test/expected/sql_query_results_optimized-11.out
  test/expected/sql_query_results_optimized-9.6.out
  test/expected/sql_query_results_x_diff-10.out
  test/expected/sql_query_results_x_diff-11.out
  test/expected/sql_query_results_x_diff-9.6.out
  test/sql/include/append_query.sql
  test/sql/include/plan_ordered_append_load.sql
  test/sql/include/plan_ordered_append_query.sql
  tsl/src/gapfill/exec.c
  tsl/src/gapfill/planner.c
Labels: major-feature, performance, planner

#1258 Fix regression tests running without OpenSSL in travis
  .travis.yml
Labels: bug, testing
