Repository timescale/timescaledb, pull requests merged in 2019-04, with the labels that each got.

#1135 Remove unspecific ANALYZE from sql_query_results test
  test/expected/sql_query_results_optimized.out
  test/expected/sql_query_results_unoptimized.out
  test/expected/sql_query_results_x_diff.out
  test/sql/include/sql_query_results.sql
Labels: cleanup, testing

#1132 Adjust ordered append path cost
  CHANGELOG.md
  src/plan_ordered_append.c
  test/expected/plan_ordered_append-10.out
  test/expected/plan_ordered_append-11.out
  test/expected/plan_ordered_append-9.6.out
  test/sql/include/plan_ordered_append_load.sql
Labels: bug

#1134 Add support for partitionwise aggregation
  CHANGELOG.md
  src/plan_expand_hypertable.c
  test/expected/parallel-11.out
  test/expected/partitionwise.out
  test/expected/plan_hashagg-11.out
  test/expected/plan_ordered_append-11.out
  test/expected/sort_optimization-10.out
  test/expected/sort_optimization-11.out
  test/expected/sort_optimization-9.6.out
  test/expected/sql_query-10.out
  test/expected/sql_query-11.out
  test/expected/sql_query-9.6.out
  test/expected/sql_query_results_optimized-10.out
  test/expected/sql_query_results_optimized-11.out
  test/expected/sql_query_results_optimized-9.6.out
  test/expected/sql_query_results_unoptimized-10.out
  test/expected/sql_query_results_unoptimized-11.out
  test/expected/sql_query_results_unoptimized-9.6.out
  test/expected/sql_query_results_x_diff-10.out
  test/expected/sql_query_results_x_diff-11.out
  test/expected/sql_query_results_x_diff-9.6.out
  test/sql/.gitignore
  test/sql/CMakeLists.txt
  test/sql/partitionwise.sql
  test/sql/sort_optimization.sql.in
  test/sql/sql_query.sql.in
  test/sql/sql_query_results_optimized.sql.in
  test/sql/sql_query_results_unoptimized.sql.in
  test/sql/sql_query_results_x_diff.sql.in
  tsl/test/expected/plan_gapfill-11.out
Labels: enhancement, performance

#1145 Add a Git commit hook to validate commit messages
  .travis.yml
  CMakeLists.txt
  scripts/githooks/commit_msg.py
  scripts/githooks/commit_msg_tests.py
Labels: enhancement

#1150 Add a gitignore for Git hook tests
  scripts/githooks/.gitignore
Labels: cleanup

#1148 Fix gapfill sanitizer bugs
  tsl/src/gapfill/planner.c
Labels: testing

#1146 Refactor collecting RestrictInfo
  src/plan_expand_hypertable.c
  test/expected/plan_expand_hypertable-10.out
  test/expected/plan_expand_hypertable-11.out
  test/expected/plan_expand_hypertable-9.6.out
  test/sql/include/plan_expand_hypertable_chunks_in_query.sql
Labels: refactoring

#1159 Add content of installation_metadata to telemetry
  appveyor.yml
  src/guc.c
  src/guc.h
  src/telemetry/metadata.c
  src/telemetry/metadata.h
  src/telemetry/telemetry.c
  test/expected/telemetry.out
  test/postgresql.conf
  test/sql/telemetry.sql
Labels: docs-update-needed

#1194 Fix sanitizer and release tests [Merge into 1.3.x]
  scripts/test_sanitizers.sh
  tsl/test/sql/CMakeLists.txt
Labels: bug, build

#1189 Add default index for continuous aggregates
  src/continuous_agg.c
  src/continuous_agg.h
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/options.c
  tsl/test/expected/continuous_aggs.out
  tsl/test/expected/continuous_aggs_dump.out
  tsl/test/expected/continuous_aggs_errors.out
  tsl/test/expected/continuous_aggs_usage.out
  tsl/test/sql/continuous_aggs.sql
  tsl/test/sql/continuous_aggs_errors.sql
Labels: minor-feature
