Repository timescale/timescaledb, pull requests merged in 2019-01, with the labels that each got.

#956 Remove out-dated and unused scripts
  scripts/docker-run.sh
  scripts/start-test-docker.sh
Labels: cleanup

#961 Remove git merge/rebase lines from TSL
  tsl/LICENSE-TIMESCALE
Labels: cleanup

#996 Fix bgw_launcher restart when failing during launcher setup
  src/loader/bgw_launcher.c
  src/loader/bgw_message_queue.c
Labels: bug

#1001 Use hypertable for parallel tests
  test/expected/parallel-10.out
  test/expected/parallel-11.out
  test/expected/parallel-9.6.out
  test/sql/parallel.sql.in
Labels: cleanup, testing
