Repository timescale/timescaledb, pull requests merged in 2019-02, with the labels that each got.

#1036 Make code formatting cover TSL test source code
  CMakeLists.txt
  tsl/src/gapfill/interpolate.c
  tsl/src/reorder.c
  tsl/test/isolation/specs/reorder_deadlock.spec
  tsl/test/isolation/specs/reorder_vs_insert.spec
  tsl/test/isolation/specs/reorder_vs_select.spec
  tsl/test/src/test_auto_policy.c
  tsl/test/src/test_chunk_stats.c
Labels: cleanup

#1039 Fix release build tests and exclude debug/test code
  test/CMakeLists.txt
  test/pg_isolation_regress.sh
  tsl/test/CMakeLists.txt
  tsl/test/isolation/specs/CMakeLists.txt
  tsl/test/isolation/specs/reorder_deadlock.spec
  tsl/test/isolation/specs/reorder_vs_insert.spec
  tsl/test/isolation/specs/reorder_vs_select.spec
  tsl/test/sql/CMakeLists.txt
Labels: bug, cleanup, testing

#1043 Stop background worker on rename database
  src/loader/loader.c
  test/expected/bgw_launcher.out
  test/sql/bgw_launcher.sql
Labels: bug

#1044 Explicitly check for NULL pointer in ts_bookend_finalfunc
  CHANGELOG.md
  src/agg_bookend.c
  src/histogram.c
Labels: bug

#1047 Fix group handling in time_bucket_gapfill
  CHANGELOG.md
  tsl/src/gapfill/exec.c
  tsl/test/expected/gapfill.out
  tsl/test/sql/gapfill.sql
Labels: bug

#1010 Add session locks to CLUSTER
  src/process_utility.c
  test/expected/cluster.out
Labels: bug

#1051 Exclude hidden and CMake directories when formatting code
  scripts/clang_format_all.sh
Labels: bug

#1048 Fix tlist on hypertable inserts inside CTEs
  src/hypertable_insert.c
  src/hypertable_insert.h
  src/planner.c
  test/expected/upsert.out
  test/sql/upsert.sql
Labels: bug

#1054 Only perform chunk insert state switch actions when necessary
  src/chunk_dispatch.c
  src/chunk_dispatch.h
  src/chunk_dispatch_state.c
  src/copy.c
Labels: cleanup

#1064 Add .editorconfig for better github display
  .editorconfig
Labels: cleanup

#1007 Remove parent oid from find_children_oids result
  .gitignore
  CHANGELOG.md
  src/constraint_aware_append.c
  src/guc.c
  src/guc.h
  src/plan_expand_hypertable.c
  src/planner.c
  test/expected/agg_bookends_optimized-10.out
  test/expected/agg_bookends_optimized-11.out
  test/expected/agg_bookends_optimized-9.6.out
  test/expected/append.out
  test/expected/append_unoptimized.out
  test/expected/append_x_diff.out
  test/expected/cursor.out
  test/expected/custom_type.out
  test/expected/ddl.out
  test/expected/ddl_alter_column.out
  test/expected/ddl_single.out
  test/expected/delete.out
  test/expected/parallel-10.out
  test/expected/parallel-11.out
  test/expected/parallel-9.6.out
  test/expected/partitioning.out
  test/expected/plan_expand_hypertable_optimized-10.out
  test/expected/plan_expand_hypertable_optimized-11.out
  test/expected/plan_expand_hypertable_optimized-9.6.out
  test/expected/plan_hashagg_optimized-10.out
  test/expected/plan_hashagg_optimized-11.out
  test/expected/plan_hashagg_optimized-9.6.out
  test/expected/plan_ordered_append-10.out
  test/expected/plan_ordered_append-11.out
  test/expected/plan_ordered_append-9.6.out
  test/expected/rowsecurity-10.out
  test/expected/rowsecurity-11.out
  test/expected/rowsecurity-9.6.out
  test/expected/sort_optimization.out
  test/expected/sql_query.out
  test/expected/sql_query_results_optimized.out
  test/expected/sql_query_results_x_diff.out
  test/expected/update.out
  test/expected/views.out
  test/sql/CMakeLists.txt
  test/sql/cursor.sql
  test/sql/include/append.sql
  test/sql/plan_expand_hypertable_optimized.sql.in
  test/sql/rowsecurity-11.sql
  test/sql/sort_optimization.sql
  test/sql/views.sql
  tsl/test/expected/plan_gapfill-10.out
  tsl/test/expected/plan_gapfill-11.out
  tsl/test/expected/plan_gapfill-9.6.out
  tsl/test/expected/reorder.out
Labels: cleanup

#1062 Make constraint aware append parallel safe
  CHANGELOG.md
  src/constraint_aware_append.c
  src/constraint_aware_append.h
  src/init.c
  src/planner.c
  test/expected/append.out
  test/expected/append_x_diff.out
  test/expected/parallel-10.out
  test/expected/parallel-11.out
  test/expected/parallel-9.6.out
  test/expected/plan_ordered_append-10.out
  test/expected/plan_ordered_append-11.out
  test/expected/plan_ordered_append-9.6.out
  test/sql/include/append.sql
  test/sql/include/plan_ordered_append_load.sql
  test/sql/include/plan_ordered_append_query.sql
  test/sql/parallel.sql.in
Labels: minor-feature, performance
