Repository timescale/timescaledb, pull requests merged in 2020-11, with the labels that each got.

#2615 Ignore PostgreSQL's timetz test
  test/pgtest/CMakeLists.txt
Labels: testing

#2612 Optimize internal cagg_watermark function
  src/continuous_agg.c
  tsl/test/expected/continuous_aggs_union_view-11.out
  tsl/test/expected/continuous_aggs_union_view-12.out
Labels: continuous-aggs

#2604 Fix chunk creation on hypertables with foreign key constraints
  sql/chunk_constraint.sql
  test/expected/constraint.out
  test/sql/constraint.sql
Labels: bug, core

#2586 Remove commented code blocks
  tsl/src/data_node_dispatch.c
  tsl/src/nodes/decompress_chunk/planner.c
Labels: cleanup

#2617 Fix validation of available extensions on data node
  tsl/src/data_node.c
  tsl/src/dist_util.c
Labels: multinode

#2613 Refresh correct partial during refresh on drop
  src/chunk.c
  src/cross_module_fn.c
  src/cross_module_fn.h
  tsl/src/continuous_aggs/materialize.c
  tsl/src/continuous_aggs/materialize.h
  tsl/src/continuous_aggs/refresh.c
  tsl/src/continuous_aggs/refresh.h
  tsl/test/expected/continuous_aggs_drop_chunks.out
  tsl/test/sql/continuous_aggs_drop_chunks.sql
Labels: continuous-aggs

#2620 Fix DROP CASCADE for continuous aggregate
  src/process_utility.c
  tsl/test/expected/continuous_aggs_ddl.out
  tsl/test/sql/continuous_aggs_ddl.sql
Labels: continuous-aggs

#2625 Fix subquery errors when using AsyncAppend
  src/guc.c
  tsl/src/async_append.c
  tsl/src/async_append.h
  tsl/src/fdw/data_node_scan_exec.c
  tsl/src/fdw/option.c
  tsl/src/fdw/relinfo.c
  tsl/src/fdw/scan_exec.c
  tsl/src/fdw/scan_exec.h
  tsl/src/fdw/scan_plan.c
  tsl/src/remote/async.c
  tsl/src/remote/cursor_fetcher.c
  tsl/src/remote/cursor_fetcher.h
  tsl/src/remote/data_fetcher.c
  tsl/src/remote/data_fetcher.h
  tsl/src/remote/row_by_row_fetcher.c
  tsl/src/remote/row_by_row_fetcher.h
  tsl/test/expected/dist_query-11.out
  tsl/test/expected/dist_query-12.out
  tsl/test/sql/data_fetcher.sql
  tsl/test/sql/dist_query.sql.in
  tsl/test/sql/include/dist_query_run.sql
Labels: multinode

#2624 Improve error when converting time arguments
  src/time_utils.c
  test/expected/chunk_utils.out
  tsl/test/expected/continuous_aggs_refresh.out
Labels: cleanup

#2628 Stop recursion in cache invalidation
  src/cache_invalidate.c
Labels: bug, relcache, segfault

#2619 Fix segfault in decompress_chunk for chunks with dropped columns
  tsl/src/compression/compression.c
Labels: 1.7, 2.0

#2631 Fix segfault in decompress_chunk for chunks with dropped columns
  tsl/src/compression/compression.c
Labels: 1.7

#2632 Ignore PostgreSQL's timetz test
  test/pgtest/CMakeLists.txt
Labels: 1.7

#2639 Fix uninitialized variable in data node validation
  tsl/src/data_node.c
Labels: bug

#2635 Add API to refresh continuous aggregate on chunk
  sql/ddl_internal.sql
  src/catalog.h
  src/chunk.c
  src/chunk.h
  src/cross_module_fn.c
  src/cross_module_fn.h
  src/process_utility.c
  tsl/src/continuous_aggs/refresh.c
  tsl/src/continuous_aggs/refresh.h
  tsl/src/init.c
  tsl/test/expected/continuous_aggs_ddl.out
  tsl/test/expected/continuous_aggs_drop_chunks.out
  tsl/test/expected/continuous_aggs_errors.out
  tsl/test/sql/continuous_aggs_ddl.sql
  tsl/test/sql/continuous_aggs_drop_chunks.sql
  tsl/test/sql/continuous_aggs_errors.sql
Labels: continuous-aggs

#2637 Release 2.0.0-rc3
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.0.0-rc2--2.0.0-rc3.sql
  sql/updates/latest-dev.sql
  version.config
Labels: release

#2643 Make compatible with old Windows compiler
  src/chunk.c
  tsl/src/continuous_aggs/materialize.c
Labels: Windows, build

#2641 Add 2.0.0-rc3 to update tests
  scripts/test_updates_pg11.sh
  scripts/test_updates_pg12.sh
Labels: testing

#2664 Fix support for complex aggregate expression
  tsl/src/continuous_aggs/create.c
  tsl/test/expected/continuous_aggs.out
  tsl/test/sql/continuous_aggs.sql
Labels: continuous-aggs

#2668 Fix support for complex aggregate expression
  tsl/src/continuous_aggs/create.c
  tsl/test/expected/continuous_aggs.out
  tsl/test/sql/continuous_aggs.sql
Labels: 1.7, bug, continuous-aggs

#2672 Add hypertable to continuous aggregates view
  sql/updates/latest-dev.sql
  sql/views.sql
  tsl/test/expected/continuous_aggs_usage.out
Labels: docs-update-needed, enhancement

#2678 Include user actions into job stats view
  sql/updates/latest-dev.sql
  sql/views.sql
  tsl/test/expected/bgw_db_scheduler.out
  tsl/test/sql/bgw_db_scheduler.sql
Labels: 2.0, Informational Tables, bug

#2683 Fix crash in add_job when given NULL interval
  tsl/src/bgw_policy/job_api.c
  tsl/test/expected/bgw_custom.out
  tsl/test/expected/tsl_tables.out
  tsl/test/sql/bgw_custom.sql
Labels: bug

#2666 Fix timeout handling in async library
  tsl/src/remote/async.c
  tsl/src/remote/async.h
  tsl/src/remote/connection.c
  tsl/src/remote/connection.h
  tsl/src/remote/txn.c
  tsl/test/expected/remote_txn.out
  tsl/test/sql/remote_txn.sql
  tsl/test/src/remote/async.c
Labels: multinode

#2688 Fix crash for concurrent drop and compress chunk
  src/dimension_slice.c
  src/scanner.c
  src/scanner.h
  tsl/test/isolation/expected/deadlock_drop_chunks_compress.out
  tsl/test/isolation/specs/CMakeLists.txt
  tsl/test/isolation/specs/deadlock_drop_chunks_compress.spec
Labels: 1.7, bug
