Repository timescale/timescaledb, pull requests merged in 2020-04, with the labels that each got.

#1791 Fix use of uninitialized variables in cont. aggs
  tsl/src/continuous_aggs/materialize.c
Labels: fixup

#1792 Add missing cast to cagg union view
  src/utils.h
  tsl/src/continuous_aggs/create.c
  tsl/test/expected/continuous_aggs_union_view-10.out
  tsl/test/expected/continuous_aggs_union_view-11.out
  tsl/test/expected/continuous_aggs_union_view-9.6.out
Labels: bug

#1795 Fix use-after-free in cagg union view creation
  tsl/src/continuous_aggs/create.c
Labels: bug

#1771 Run regression test on latest PG versions
  .gitignore
  .travis.yml
  scripts/docker-build.sh
  scripts/test_sanitizers.sh
  test/isolation/specs/bgw_job_delete.spec.in
  test/pg_isolation_regress.sh
  tsl/test/isolation/expected/compression_ddl.out
  tsl/test/isolation/expected/continuous_aggs_insert-11.out
  tsl/test/isolation/expected/continuous_aggs_insert-9.6.out
  tsl/test/isolation/expected/continuous_aggs_insert.out
  tsl/test/isolation/expected/continuous_aggs_multi-11.out
  tsl/test/isolation/expected/continuous_aggs_multi-9.6.out
  tsl/test/isolation/expected/continuous_aggs_multi.out
  tsl/test/isolation/specs/CMakeLists.txt
  tsl/test/isolation/specs/continuous_aggs_insert.spec
  tsl/test/isolation/specs/continuous_aggs_multi.spec
Labels: testing

#1780 Point to Timescale Code of Conduct
  .github/CODE_OF_CONDUCT.md
Labels: documentation

#1808 Fix ts_hypertable_get_all for compressed tables
  src/hypertable.c
  test/expected/chunk_utils_compression.out
  test/sql/CMakeLists.txt
  test/sql/chunk_utils.sql
  test/sql/chunk_utils_compression.sql
Labels: Compression, bug

#1823 Fix null pointer deref in continuous aggregates
  src/continuous_agg.c
Labels: bug, continuous-aggs

#1828 Ignore dropped chunks in compressed_chunk_stats
  sql/views.sql
  test/sql/views.sql
  tsl/test/expected/compression.out
  tsl/test/sql/compression.sql
Labels: Compression, bug

#1834 Define strerror() for Windows
  src/net/conn_plain.c
Labels: fixup

#1838 Update build from source instructions for 1.7
  docs/BuildSource.md
Labels: documentation

#1851 Fix hypertable expansion for UNION ALL
  src/planner.c
  test/expected/plan_expand_hypertable-10.out
  test/expected/plan_expand_hypertable-11.out
  test/expected/plan_expand_hypertable-12.out
  test/expected/plan_expand_hypertable-9.6.out
  test/sql/include/plan_expand_hypertable_query.sql
Labels: bug

#1856 Silence various compiler warnings
  src/bgw/job.c
  src/hypertable.c
  src/hypertable_cache.h
  src/import/planner.h
  src/plan_add_hashagg.c
  src/process_utility.c
  test/CMakeLists.txt
  tsl/src/compression/create.c
  tsl/src/compression/deltadelta.c
  tsl/src/compression/gorilla.c
  tsl/src/compression/simple8b_rle.h
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/src/nodes/gapfill/exec.c
  tsl/src/reorder.c
Labels: cleanup

#1850 Validate job time to avoid error thrown by scheduler
  src/bgw/scheduler.c
Labels: 1.7.1 - Candidate

#1843 Improve handling of "dropped" chunks
  src/chunk.c
  src/chunk.h
  src/chunk_constraint.c
  src/chunk_index.c
  src/chunk_index.h
  src/chunk_insert_state.c
  src/hypertable.c
  src/hypertable.h
  src/plan_expand_hypertable.c
  src/planner.c
  src/process_utility.c
  src/trigger.c
  src/trigger.h
  tsl/src/bgw_policy/job.c
  tsl/src/compression/compress_utils.c
  tsl/src/compression/create.c
  tsl/src/continuous_aggs/insert.c
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/src/planner.c
  tsl/src/reorder.c
Labels: bug, refactoring
