Repository timescale/timescaledb, pull requests merged in 2020-07, with the labels that each got.

#2045 Merge pg_regress.sh and pg_isolation_regress.sh
  test/CMakeLists.txt
  test/pg_isolation_regress.sh
  test/pg_regress.sh
  test/test-defs.cmake
  tsl/test/CMakeLists.txt
Labels: cleanup, testing

#2046 Use index tablespace during chunk creation
  sql/chunk_constraint.sql
  test/expected/alter.out
  test/sql/alter.sql
Labels: bug

#2028 Add locks for dimension slice tuples
  sql/updates/latest-dev.sql
  src/bgw/job.c
  src/chunk.c
  src/chunk.h
  src/dimension_slice.c
  src/dimension_slice.h
  src/hypercube.c
  src/hypercube.h
  src/hypertable_restrict_info.c
  src/scanner.c
  src/scanner.h
  test/isolation/expected/insert_dropchunks_race.out
  test/isolation/specs/CMakeLists.txt
  test/isolation/specs/insert_dropchunks_race.spec
Labels: bug

#2051 Fix tuple concurrently deleted error with multiple continuous aggregates
  tsl/src/continuous_aggs/materialize.c
  tsl/test/isolation/expected/continuous_aggs_multi.out
  tsl/test/isolation/specs/continuous_aggs_multi.spec
Labels: bug

#2041 Cleanup unused code paths
  src/chunk_dispatch_state.c
  src/chunk_insert_state.c
Labels: cleanup

#2059 Improve infering start and stop arguments from gapfill query
  tsl/src/nodes/gapfill/exec.c
  tsl/test/expected/gapfill.out
  tsl/test/sql/gapfill.sql
Labels: Gap Fill

#2095 Add test of drop_chunks on distributed hypertable
  tsl/test/expected/dist_api_calls.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/dist_api_calls.sql
Labels: multinode, testing

#2094 Fetch collations from data nodes during ANALYZE
  sql/chunk.sql
  tsl/src/chunk_api.c
  tsl/test/expected/chunk_api-11.out
  tsl/test/expected/chunk_api-12.out
  tsl/test/sql/.gitignore
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/chunk_api.sql.in
Labels: multinode

#2110 Remove include of pg_config.h
  src/init.c
  src/loader/loader.c
  src/net/conn.c
  src/net/conn.h
  src/net/conn_plain.c
  src/net/conn_ssl.c
  src/telemetry/telemetry.h
  test/src/loader/init.c
  test/src/net/conn_mock.c
Labels: cleanup

#2105 Support moving compressed chunks
  src/chunk.c
  src/chunk.h
  tsl/src/reorder.c
  tsl/test/expected/compression_ddl.out
  tsl/test/sql/compression_ddl.sql
Labels: fixup

#2098 Add chunks and dimensions view
  sql/views.sql
  test/expected/pg_dump.out
  test/expected/views.out
  test/sql/views.sql
  tsl/test/expected/dist_compression.out
  tsl/test/sql/dist_compression.sql
Labels: enhancement

#2116 Propagate privileges from hypertables to chunks
  src/chunk.c
  src/process_utility.c
  test/expected/grant_hypertable.out
  test/expected/rowsecurity-11.out
  test/expected/rowsecurity-12.out
  test/sql/CMakeLists.txt
  test/sql/grant_hypertable.sql
  tsl/test/expected/dist_grant.out
  tsl/test/sql/dist_grant.sql
Labels: permissions

#2084 Utility function and hypertables view
  sql/dist_internal.sql
  sql/size_utils.sql
  sql/updates/latest-dev.sql
  sql/views.sql
  src/cross_module_fn.c
  src/cross_module_fn.h
  test/expected/extension.out
  test/expected/pg_dump.out
  test/expected/relocate_extension.out
  test/expected/size_utils.out
  test/expected/views.out
  test/isolation/expected/multi_transaction_indexing.out
  test/isolation/specs/multi_transaction_indexing.spec
  test/sql/relocate_extension.sql
  test/sql/size_utils.sql
  test/sql/views.sql
  tsl/src/dist_util.c
  tsl/src/dist_util.h
  tsl/src/init.c
  tsl/test/expected/compression.out
  tsl/test/expected/compression_hypertable.out
  tsl/test/expected/dist_compression.out
  tsl/test/expected/dist_hypertable-11.out
  tsl/test/expected/dist_hypertable-12.out
  tsl/test/expected/dist_query-11.out
  tsl/test/expected/dist_query-12.out
  tsl/test/expected/dist_util.out
  tsl/test/expected/dist_views.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/compression.sql
  tsl/test/sql/compression_hypertable.sql
  tsl/test/sql/dist_compression.sql
  tsl/test/sql/dist_hypertable.sql.in
  tsl/test/sql/dist_query.sql.in
  tsl/test/sql/dist_util.sql
  tsl/test/sql/dist_views.sql
Labels: enhancement

#2148 Rename add_drop_chunks_policy
  sql/bgw_scheduler.sql
  sql/updates/1.2.2--1.3.0.sql
  sql/updates/latest-dev.sql
  src/cross_module_fn.c
  src/cross_module_fn.h
  test/expected/extension.out
  tsl/src/bgw_policy/drop_chunks_api.c
  tsl/src/init.c
  tsl/test/expected/bgw_policy.out
  tsl/test/expected/bgw_reorder_drop_chunks.out
  tsl/test/expected/compress_bgw_reorder_drop_chunks.out
  tsl/test/expected/compression_errors.out
  tsl/test/expected/continuous_aggs_bgw_drop_chunks.out
  tsl/test/expected/tsl_tables.out
  tsl/test/sql/bgw_policy.sql
  tsl/test/sql/bgw_reorder_drop_chunks.sql
  tsl/test/sql/compress_bgw_reorder_drop_chunks.sql
  tsl/test/sql/compression_errors.sql
  tsl/test/sql/continuous_aggs_bgw_drop_chunks.sql
  tsl/test/sql/tsl_tables.sql
Labels: docs-update-needed
