Repository timescale/timescaledb, pull requests merged in 2020-10, with the labels that each got.

#2472 Make function parameter names consistent
  sql/ddl_api.sql
  sql/policy_api.sql
  sql/size_utils.sql
  sql/updates/latest-dev.sql
  src/dimension.c
  src/hypertable.c
  test/expected/chunk_utils.out
  test/expected/relocate_extension.out
  test/sql/chunk_utils.sql
  test/sql/relocate_extension.sql
  tsl/test/expected/deparse.out
Labels: cleanup

#2482 Improve check for fallthrough support
  src/annotations.h
Labels: cleanup

#2481 Fix parameter names in policy API code
  sql/updates/latest-dev.sql
  tsl/src/bgw_policy/compression_api.c
  tsl/src/bgw_policy/compression_api.h
  tsl/src/bgw_policy/continuous_aggregate_api.c
  tsl/src/bgw_policy/job.c
  tsl/src/bgw_policy/retention_api.c
  tsl/src/bgw_policy/retention_api.h
  tsl/test/expected/bgw_policy.out
  tsl/test/expected/bgw_reorder_drop_chunks.out
  tsl/test/expected/compress_bgw_reorder_drop_chunks.out
  tsl/test/expected/compression_bgw.out
  tsl/test/expected/continuous_aggs.out
  tsl/test/expected/continuous_aggs_bgw.out
  tsl/test/expected/continuous_aggs_bgw_drop_chunks.out
  tsl/test/expected/continuous_aggs_policy.out
  tsl/test/expected/continuous_aggs_usage.out
  tsl/test/expected/tsl_tables.out
Labels: cleanup

#2490 Make data nodes view consistent with other views
  sql/views.sql
  test/expected/pg_dump.out
  tsl/test/expected/data_node.out
  tsl/test/expected/dist_hypertable-11.out
  tsl/test/expected/dist_hypertable-12.out
  tsl/test/expected/dist_util.out
  tsl/test/sql/data_node.sql
  tsl/test/sql/dist_hypertable.sql.in
  tsl/test/sql/dist_util.sql
Labels: multinode

#2489 Show unscheduled jobs as paused in job_stats
  sql/views.sql
  tsl/test/expected/tsl_tables.out
  tsl/test/sql/tsl_tables.sql
Labels: docs-update-needed

#2478 Release 2.0.0-rc1
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/1.7.4--2.0.0-rc1.sql
  sql/updates/latest-dev.sql
  version.config
Labels: release

#2507 Fix validation logic when adding a new data node
  tsl/src/data_node.c
  tsl/src/remote/connection.c
  tsl/src/remote/connection.h
  tsl/test/expected/data_node.out
  tsl/test/sql/data_node.sql
Labels: 2.0-proposed, multinode

#2520 Support non-transactional distibuted_exec
  sql/ddl_api.sql
  sql/updates/latest-dev.sql
  src/compat.h
  tsl/src/remote/dist_commands.c
  tsl/test/expected/chunk_api-11.out
  tsl/test/expected/chunk_api-12.out
  tsl/test/expected/dist_commands.out
  tsl/test/expected/dist_ddl.out
  tsl/test/expected/dist_hypertable-11.out
  tsl/test/expected/dist_hypertable-12.out
  tsl/test/expected/dist_query-11.out
  tsl/test/expected/dist_query-12.out
  tsl/test/sql/chunk_api.sql.in
  tsl/test/sql/dist_commands.sql
  tsl/test/sql/dist_ddl.sql
  tsl/test/sql/dist_hypertable.sql.in
  tsl/test/sql/include/dist_query_load.sql
Labels: 2.0-proposed, docs-update-needed, multinode

#2531 Cleanup public API
  sql/ddl_api.sql
  sql/updates/latest-dev.sql
  sql/views.sql
  test/sql/updates/post.continuous_aggs.v2.sql
  tsl/test/expected/continuous_aggs_usage.out
Labels: cleanup, docs-update-needed

#2514 Lock dimension slices when creating new chunk
  src/chunk.c
  src/chunk.h
  src/dimension_slice.c
  src/dimension_slice.h
  src/hypercube.c
  src/hypercube.h
  src/hypertable.c
  test/isolation/expected/dropchunks_race.out
  test/isolation/specs/dropchunks_race.spec.in
Labels: bug

#2571 Make errors and messages conform to style guide
  src/bgw/job_stat.c
  src/chunk.c
  src/compression_with_clause.c
  src/dimension.c
  src/errors.h
  src/hypertable.c
  src/loader/bgw_message_queue.c
  src/loader/loader.c
  src/process_utility.c
  src/telemetry/telemetry.c
  src/time_utils.c
  test/expected/bgw_launcher.out
  test/expected/create_chunks.out
  test/expected/create_hypertable.out
  test/expected/ddl_errors.out
  test/expected/partition-11.out
  test/expected/partition-12.out
  test/expected/rowsecurity-11.out
  test/expected/rowsecurity-12.out
  test/expected/timestamp.out
  tsl/src/bgw_policy/compression_api.c
  tsl/src/bgw_policy/continuous_aggregate_api.c
  tsl/src/bgw_policy/job_api.c
  tsl/src/bgw_policy/policy_utils.c
  tsl/src/bgw_policy/reorder_api.c
  tsl/src/bgw_policy/retention_api.c
  tsl/src/chunk.c
  tsl/src/compression/compress_utils.c
  tsl/src/compression/create.c
  tsl/src/continuous_aggs/create.c
  tsl/src/data_node.c
  tsl/src/hypertable.c
  tsl/src/nodes/gapfill/exec.c
  tsl/src/reorder.c
  tsl/test/expected/bgw_policy.out
  tsl/test/expected/chunk_api-11.out
  tsl/test/expected/chunk_api-12.out
  tsl/test/expected/compression.out
  tsl/test/expected/compression_bgw.out
  tsl/test/expected/compression_ddl.out
  tsl/test/expected/compression_errors.out
  tsl/test/expected/continuous_aggs_bgw_drop_chunks.out
  tsl/test/expected/continuous_aggs_ddl.out
  tsl/test/expected/continuous_aggs_errors.out
  tsl/test/expected/continuous_aggs_policy.out
  tsl/test/expected/continuous_aggs_refresh.out
  tsl/test/expected/continuous_aggs_usage.out
  tsl/test/expected/data_node.out
  tsl/test/expected/dist_compression.out
  tsl/test/expected/dist_ddl.out
  tsl/test/expected/dist_grant.out
  tsl/test/expected/dist_hypertable-11.out
  tsl/test/expected/dist_hypertable-12.out
  tsl/test/expected/dist_hypertable_with_oids.out
  tsl/test/expected/dist_policy.out
  tsl/test/expected/reorder-11.out
  tsl/test/expected/tsl_tables.out
  tsl/test/sql/compression_errors.sql
  tsl/test/sql/tsl_tables.sql
  tsl/test/src/remote/remote_exec.c
Labels: cleanup

#2584 Read function name dynamically
  src/chunk.c
  src/chunk_adaptive.c
  src/compat.h
  src/dimension.c
  src/hypertable.c
  src/tablespace.c
  tsl/src/bgw_policy/compression_api.c
  tsl/src/bgw_policy/continuous_aggregate_api.c
  tsl/src/bgw_policy/job_api.c
  tsl/src/bgw_policy/reorder_api.c
  tsl/src/bgw_policy/retention_api.c
  tsl/src/data_node.c
  tsl/src/hypertable.c
Labels: refactoring
