Repository timescale/timescaledb, pull requests merged in 2020-06, with the labels that each got.

#1943 Support table access methods for distributed hypertables
  tsl/src/deparse.c
  tsl/test/expected/dist_hypertable_am.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/dist_hypertable_am.sql
Labels: multinode

#1952 Remove cascade option from drop_chunks
  sql/bgw_scheduler.sql
  sql/ddl_api.sql
  sql/pre_install/tables.sql
  sql/updates/latest-dev.sql
  sql/views.sql
  src/bgw_policy/drop_chunks.c
  src/bgw_policy/drop_chunks.h
  src/catalog.h
  src/chunk.c
  src/chunk.h
  src/cross_module_fn.c
  src/cross_module_fn.h
  test/expected/chunk_utils.out
  test/sql/chunk_utils.sql
  tsl/src/bgw_policy/drop_chunks_api.c
  tsl/src/bgw_policy/job.c
  tsl/src/chunk.c
  tsl/src/chunk.h
  tsl/src/continuous_aggs/drop.c
  tsl/src/continuous_aggs/drop.h
  tsl/test/expected/bgw_reorder_drop_chunks.out
  tsl/test/expected/compress_bgw_reorder_drop_chunks.out
  tsl/test/expected/compression_ddl.out
  tsl/test/expected/deparse.out
  tsl/test/expected/deparse_fail.out
  tsl/test/expected/dist_hypertable-11.out
  tsl/test/expected/dist_hypertable-12.out
  tsl/test/expected/tsl_tables.out
  tsl/test/sql/compression_ddl.sql
  tsl/test/sql/deparse.sql
  tsl/test/sql/dist_hypertable.sql.in
  tsl/test/sql/include/deparse_func.sql
  tsl/test/sql/tsl_tables.sql
  tsl/test/src/deparse.c
Labels: 2.0-proposed, breaks-api, docs-update-needed, ui/ux

#1938 Fix gapfill locf treat_null_as_missing
  CHANGELOG.md
  tsl/src/nodes/gapfill/exec.c
Labels: Gap Fill, bug

#1908 Include internal dependencies in delete of chunks
  src/chunk_index.c
  tsl/test/expected/continuous_aggs_drop_chunks.out
  tsl/test/sql/continuous_aggs_drop_chunks.sql
Labels: continuous-aggs

#1984 Fix bit array left shift count
  src/adts/bit_array_impl.h
Labels: Compression, undefined-behaviour

#1957 Make table mandatory for drop_chunks
  sql/ddl_api.sql
  sql/updates/latest-dev.sql
  src/chunk.c
  src/chunk.h
  src/cross_module_fn.c
  src/cross_module_fn.h
  test/expected/alter.out
  test/expected/chunk_utils.out
  test/expected/chunk_utils_compression.out
  test/expected/relocate_extension.out
  test/isolation/expected/deadlock_dropchunks_select.out
  test/isolation/specs/deadlock_dropchunks_select.spec
  test/sql/alter.sql
  test/sql/chunk_utils.sql
  test/sql/chunk_utils_compression.sql
  test/sql/relocate_extension.sql
  tsl/src/bgw_policy/job.c
  tsl/src/chunk.c
  tsl/src/chunk.h
  tsl/src/continuous_aggs/drop.c
  tsl/src/continuous_aggs/drop.h
  tsl/test/expected/compression.out
  tsl/test/expected/compression_bgw.out
  tsl/test/expected/compression_ddl.out
  tsl/test/expected/continuous_aggs_ddl.out
  tsl/test/expected/data_node.out
  tsl/test/expected/deparse.out
  tsl/test/expected/deparse_fail.out
  tsl/test/expected/dist_hypertable-11.out
  tsl/test/expected/dist_hypertable-12.out
  tsl/test/sql/compression.sql
  tsl/test/sql/compression_bgw.sql
  tsl/test/sql/compression_ddl.sql
  tsl/test/sql/continuous_aggs_ddl.sql
  tsl/test/sql/data_node.sql
  tsl/test/sql/deparse.sql
  tsl/test/sql/dist_hypertable.sql.in
  tsl/test/sql/include/deparse_func.sql
  tsl/test/src/deparse.c
Labels: 2.0-proposed, breaks-api, docs-update-needed, ui/ux

#1989 Fix output in function to show connection cache
  tsl/src/remote/connection_cache.c
  tsl/test/expected/remote_txn.out
  tsl/test/sql/remote_txn.sql
Labels: bug

#1995 Fix ANALYZE on replicated distributed hypertable
  tsl/src/chunk_api.c
  tsl/src/remote/dist_commands.c
  tsl/src/remote/dist_commands.h
  tsl/test/expected/chunk_api.out
  tsl/test/sql/chunk_api.sql
Labels: bug, multinode

#1997 Add checks for read-only transactions
  src/chunk.c
  src/chunk_adaptive.c
  src/dimension.c
  src/hypertable.c
  src/process_utility.c
  src/process_utility.h
  src/tablespace.c
  tsl/src/data_node.c
  tsl/src/hypertable.c
  tsl/test/expected/read_only.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/read_only.sql
Labels: security

#2038 Fix potential mem corruption in distributed copy
  src/chunk.h
  tsl/src/remote/dist_copy.c
Labels: bug
