Repository timescale/timescaledb, pull requests merged in 2020-01, with the labels that each got.

#1608 Add jobs to timescaledb_information.policy_stats
  CHANGELOG.md
  sql/views.sql
Labels: bug

#1544 Fix crash when partializing agg with HAVING
  src/plan_partialize.c
  src/planner.c
  tsl/test/expected/partialize_finalize.out
  tsl/test/sql/partialize_finalize.sql
Labels: bug, cleanup

#1609 Fix bug with parent table in decompression
  CHANGELOG.md
  src/planner.c
  tsl/test/expected/compression.out
  tsl/test/sql/compression.sql
Labels: bug

#1630 Print notice for COPY TO on hypertable
  src/process_utility.c
  test/expected/copy.out
  test/expected/metadata.out
  test/sql/copy.sql
  test/sql/metadata.sql
  test/sql/utils/pg_dump_aux_dump.sh
  test/sql/utils/pg_dump_unprivileged.sh
Labels: minor-feature, ui/ux

#1646 Add CODEOWNERS file to auto-assign reviewers
  .github/CODEOWNERS
Labels: enhancement

#1648 Drop chunks for materialized hypertable
  src/chunk.c
  src/chunk.h
  src/continuous_agg.h
  src/cross_module_fn.c
  src/cross_module_fn.h
  tsl/src/continuous_aggs/drop.c
  tsl/src/continuous_aggs/drop.h
  tsl/test/expected/continuous_aggs_ddl-10.out
  tsl/test/expected/continuous_aggs_ddl-11.out
  tsl/test/expected/continuous_aggs_ddl-9.6.out
  tsl/test/sql/continuous_aggs_ddl.sql.in
Labels: bug, continuous-aggs

#1658 Unify error message if hypertable not found
  src/chunk.c
  src/chunk_adaptive.c
  src/chunk_dispatch_state.c
  src/dimension.c
  src/hypertable.c
  src/hypertable_cache.c
  src/hypertable_cache.h
  src/hypertable_insert.c
  src/interval.c
  src/planner.c
  src/process_utility.c
  src/tablespace.c
  tsl/src/bgw_policy/compress_chunks_api.c
  tsl/src/bgw_policy/drop_chunks_api.c
  tsl/src/bgw_policy/job.c
  tsl/src/compression/compress_utils.c
  tsl/src/compression/create.c
  tsl/src/continuous_aggs/create.c
  tsl/src/reorder.c
  tsl/test/expected/continuous_aggs_errors.out
  tsl/test/expected/tsl_tables.out
  tsl/test/src/test_continuous_aggs.c
  tsl/test/src/test_ddl_hook.c
Labels: refactoring, ui/ux
