Repository timescale/timescaledb, pull requests merged in 2020-03, with the labels that each got.

#1715 Fix incorrect chunk exclusion and broken test
  CHANGELOG.md
  src/plan_expand_hypertable.c
  test/expected/plan_expand_hypertable-10.out
  test/expected/plan_expand_hypertable-11.out
  test/expected/plan_expand_hypertable-9.6.out
  test/sql/include/plan_expand_hypertable_chunks_in_query.sql
  test/sql/include/plan_expand_hypertable_load.sql
  test/sql/include/plan_expand_hypertable_query.sql
  test/sql/plan_expand_hypertable.sql.in
  tsl/test/expected/transparent_decompression-10.out
  tsl/test/expected/transparent_decompression-11.out
Labels: bug

#1711 Change log level for cagg materialization messages
  tsl/src/continuous_aggs/materialize.c
  tsl/test/expected/compression_ddl.out
  tsl/test/expected/continuous_aggs.out
  tsl/test/expected/continuous_aggs_bgw_drop_chunks.out
  tsl/test/expected/continuous_aggs_ddl-10.out
  tsl/test/expected/continuous_aggs_ddl-11.out
  tsl/test/expected/continuous_aggs_ddl-9.6.out
  tsl/test/expected/continuous_aggs_dump.out
  tsl/test/expected/continuous_aggs_materialize.out
  tsl/test/expected/continuous_aggs_multi.out
  tsl/test/expected/continuous_aggs_permissions-10.out
  tsl/test/expected/continuous_aggs_permissions-11.out
  tsl/test/expected/continuous_aggs_permissions-9.6.out
  tsl/test/expected/continuous_aggs_query-10.out
  tsl/test/expected/continuous_aggs_query-11.out
  tsl/test/expected/continuous_aggs_query-9.6.out
  tsl/test/expected/continuous_aggs_usage.out
  tsl/test/expected/transparent_decompression-10.out
  tsl/test/expected/transparent_decompression-11.out
  tsl/test/isolation/expected/continuous_aggs_insert.out
  tsl/test/isolation/expected/continuous_aggs_multi.out
  tsl/test/isolation/specs/continuous_aggs_insert.spec
  tsl/test/isolation/specs/continuous_aggs_multi.spec
  tsl/test/shared/sql/.gitignore
  tsl/test/shared/sql/ordered_append-11.sql
  tsl/test/sql/.gitignore
  tsl/test/sql/continuous_aggs.sql
  tsl/test/sql/continuous_aggs_ddl.sql.in
  tsl/test/sql/continuous_aggs_dump.sql
  tsl/test/sql/continuous_aggs_materialize.sql
  tsl/test/sql/continuous_aggs_multi.sql
  tsl/test/sql/continuous_aggs_query.sql.in
  tsl/test/sql/continuous_aggs_usage.sql
Labels: docs-update-needed

#1725 Stop background worker in tests
  test/expected/bgw_db_scheduler.out
  test/expected/bgw_launcher.out
  test/runner.sh
  test/sql/bgw_db_scheduler.sql
  test/sql/bgw_launcher.sql
  test/sql/utils/testsupport.sql
  tsl/test/expected/bgw_policy.out
  tsl/test/expected/bgw_reorder_drop_chunks.out
  tsl/test/expected/compress_bgw_drop_chunks.out
  tsl/test/expected/compression_bgw.out
  tsl/test/expected/compression_permissions-10.out
  tsl/test/expected/compression_permissions-11.out
  tsl/test/expected/continuous_aggs.out
  tsl/test/expected/continuous_aggs_bgw.out
  tsl/test/expected/continuous_aggs_bgw_drop_chunks.out
  tsl/test/expected/continuous_aggs_ddl-10.out
  tsl/test/expected/continuous_aggs_ddl-11.out
  tsl/test/expected/continuous_aggs_ddl-9.6.out
  tsl/test/expected/continuous_aggs_dump.out
  tsl/test/expected/continuous_aggs_materialize.out
  tsl/test/expected/continuous_aggs_multi.out
  tsl/test/expected/continuous_aggs_permissions-10.out
  tsl/test/expected/continuous_aggs_permissions-11.out
  tsl/test/expected/continuous_aggs_permissions-9.6.out
  tsl/test/expected/continuous_aggs_query-10.out
  tsl/test/expected/continuous_aggs_query-11.out
  tsl/test/expected/continuous_aggs_query-9.6.out
  tsl/test/expected/continuous_aggs_usage.out
  tsl/test/expected/continuous_aggs_watermark.out
  tsl/test/expected/tsl_tables.out
  tsl/test/sql/bgw_policy.sql
  tsl/test/sql/bgw_reorder_drop_chunks.sql
  tsl/test/sql/compress_bgw_drop_chunks.sql
  tsl/test/sql/compression_bgw.sql
  tsl/test/sql/compression_permissions.sql.in
  tsl/test/sql/continuous_aggs.sql
  tsl/test/sql/continuous_aggs_bgw.sql
  tsl/test/sql/continuous_aggs_bgw_drop_chunks.sql
  tsl/test/sql/continuous_aggs_ddl.sql.in
  tsl/test/sql/continuous_aggs_dump.sql
  tsl/test/sql/continuous_aggs_materialize.sql
  tsl/test/sql/continuous_aggs_multi.sql
  tsl/test/sql/continuous_aggs_permissions.sql.in
  tsl/test/sql/continuous_aggs_query.sql.in
  tsl/test/sql/continuous_aggs_usage.sql
  tsl/test/sql/continuous_aggs_watermark.sql
  tsl/test/sql/tsl_tables.sql
Labels: background-worker, testing

#1727 Fix compressing interval columns
  CHANGELOG.md
  tsl/src/compression/create.c
  tsl/test/expected/compression.out
  tsl/test/sql/compression.sql
Labels: bug

#1709 Prevent starting background workers with NOLOGIN
  src/bgw/job.c
  src/bgw/job.h
  tsl/src/bgw_policy/compress_chunks_api.c
  tsl/src/bgw_policy/drop_chunks_api.c
  tsl/src/bgw_policy/reorder_api.c
  tsl/test/expected/compression_bgw.out
  tsl/test/expected/continuous_aggs_permissions-10.out
  tsl/test/expected/continuous_aggs_permissions-11.out
  tsl/test/expected/continuous_aggs_permissions-9.6.out
  tsl/test/expected/tsl_tables.out
  tsl/test/sql/compression_bgw.sql
Labels: background-worker

#1724 Fix typo of "continuous"
  src/continuous_agg.c
  src/continuous_agg.h
  src/process_utility.c
  tsl/src/bgw_policy/drop_chunks_api.c
  tsl/src/bgw_policy/job.c
  tsl/test/expected/continuous_aggs.out
  tsl/test/expected/continuous_aggs_dump.out
Labels: 1.7.1 - Candidate, continuous-aggs

#1730 Adjust index predicate attnos when creating chunk index
  src/chunk_index.c
  test/expected/index.out
  test/sql/index.sql
Labels: bug

#1688 Handle many BGW jobs better
  src/bgw/job_stat.c
  src/bgw/job_stat.h
  src/bgw/scheduler.c
  src/compat.h
  test/expected/bgw_db_scheduler.out
  test/sql/bgw_db_scheduler.sql
Labels: background-worker

#1728 Handle Sort nodes in ConstraintAwareAppend
  CHANGELOG.md
  src/constraint_aware_append.c
  tsl/test/expected/transparent_decompression_queries.out
  tsl/test/sql/transparent_decompression_queries.sql
Labels: bug

#1737 Fix flaky gapfill test
  tsl/test/expected/gapfill.out
  tsl/test/sql/gapfill.sql
Labels: Gap Fill

#1744 Cleanup compression-related errors
  tsl/src/bgw_policy/drop_chunks_api.c
  tsl/src/compression/compress_utils.c
  tsl/src/compression/compression.c
  tsl/src/compression/create.c
  tsl/test/expected/compression_errors.out
Labels: cleanup

#1746 Fix continuous aggs DDL test on PG9.6
  tsl/test/expected/compression.out
  tsl/test/expected/continuous_aggs_ddl-10.out
  tsl/test/expected/continuous_aggs_ddl.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/compression.sql
  tsl/test/sql/continuous_aggs_ddl.sql
  tsl/test/sql/continuous_aggs_ddl.sql.in
Labels: cleanup

#1748 Fix remove_drop_chunks_policy for continuous aggregates
  tsl/src/bgw_policy/drop_chunks_api.c
  tsl/test/expected/continuous_aggs_bgw_drop_chunks.out
  tsl/test/sql/continuous_aggs_bgw_drop_chunks.sql
Labels: continuous-aggs

#1756 Do not attempt to compress chunks that are dropped
  src/chunk.c
  src/chunk.h
  src/dimension_slice.c
  tsl/test/expected/compression_bgw.out
  tsl/test/sql/compression_bgw.sql
Labels: Compression

#1769 Add rescan function to CompressChunkDml CustomScan node
  tsl/src/nodes/compress_dml/compress_dml.c
  tsl/test/expected/compression.out
  tsl/test/sql/compression.sql
Labels: bug

#1685 Real-time support for continuous aggregates
  CHANGELOG.md
  sql/util_time.sql
  src/continuous_agg.c
  src/continuous_agg.h
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/create.h
  tsl/src/continuous_aggs/options.c
  tsl/test/expected/compression_ddl.out
  tsl/test/expected/continuous_aggs.out
  tsl/test/expected/continuous_aggs_bgw.out
  tsl/test/expected/continuous_aggs_ddl.out
  tsl/test/expected/continuous_aggs_errors.out
  tsl/test/expected/continuous_aggs_materialize.out
  tsl/test/expected/continuous_aggs_multi.out
  tsl/test/expected/continuous_aggs_permissions-10.out
  tsl/test/expected/continuous_aggs_permissions-11.out
  tsl/test/expected/continuous_aggs_permissions-9.6.out
  tsl/test/expected/continuous_aggs_query-10.out
  tsl/test/expected/continuous_aggs_query-11.out
  tsl/test/expected/continuous_aggs_query-9.6.out
  tsl/test/expected/continuous_aggs_union_view-10.out
  tsl/test/expected/continuous_aggs_union_view-11.out
  tsl/test/expected/continuous_aggs_union_view-9.6.out
  tsl/test/expected/continuous_aggs_usage.out
  tsl/test/expected/continuous_aggs_watermark.out
  tsl/test/expected/transparent_decompression-10.out
  tsl/test/expected/transparent_decompression-11.out
  tsl/test/isolation/specs/continuous_aggs_insert.spec.in
  tsl/test/shared/sql/chunk_append.sql
  tsl/test/sql/.gitignore
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/compression_ddl.sql
  tsl/test/sql/continuous_aggs.sql
  tsl/test/sql/continuous_aggs_bgw.sql
  tsl/test/sql/continuous_aggs_ddl.sql
  tsl/test/sql/continuous_aggs_materialize.sql
  tsl/test/sql/continuous_aggs_permissions.sql.in
  tsl/test/sql/continuous_aggs_union_view.sql.in
  tsl/test/sql/continuous_aggs_usage.sql
  tsl/test/sql/include/transparent_decompression_query.sql
Labels: docs-update-needed, major-feature
