Repository timescale/timescaledb, pull requests merged in 2020-05, with the labels that each got.

#1873 Add 12 folder to search for PG bin in CMake
  CMakeLists.txt
Labels: build

#1872 Ignore Windows build files
  .gitignore
Labels: Windows, build

#1875 Fix hypertable detection in subqueries
  CHANGELOG.md
  src/planner.c
  test/expected/plan_hypertable_cache.out
  test/sql/CMakeLists.txt
  test/sql/plan_hypertable_cache.sql
Labels: bug

#1854 Fix reorder policy job to skip compressed chunks
  src/dimension_slice.c
  src/dimension_slice.h
  tsl/src/bgw_policy/job.c
  tsl/test/expected/compress_bgw_reorder_drop_chunks.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/compress_bgw_reorder_drop_chunks.sql
Labels: 1.7.1 - Candidate

#1881 Fix flaky hypertable cache plan test
  test/expected/plan_hypertable_cache.out
  test/sql/plan_hypertable_cache.sql
Labels: flaky-test

#1680 Improve time_bucket_gapfill optimizations
  src/func_cache.c
  src/sort_transform.c
  tsl/test/expected/gapfill.out
  tsl/test/expected/plan_gapfill-10.out
  tsl/test/expected/plan_gapfill-11.out
  tsl/test/expected/plan_gapfill-12.out
  tsl/test/expected/plan_gapfill-9.6.out
  tsl/test/sql/gapfill.sql
  tsl/test/sql/plan_gapfill.sql.in
Labels: enhancement

#1880 Remove DEBUG logging in extension check
  src/extension.c
Labels: cleanup

#1888 Run Windows builds and tests using GitHub Actions
  .github/workflows/windows-build-and-test.yaml
Labels: Windows, testing

#1886 Change ChunkAppend leader to use worker subplan
  CHANGELOG.md
  src/chunk_append/exec.c
Labels: bug

#1890 Remove unused static declaration of a function
  src/chunk_append/exec.c
Labels: cleanup

#1876 Run Windows regression tests on PG12
  appveyor.yml
Labels: Windows, testing

#1869 Fix real time aggregate support for multiple aggregates
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/README.md
  sql/updates/post-update.sql
  sql/util_time.sql
  src/extension.c
  tsl/src/continuous_aggs/create.c
  tsl/test/expected/continuous_aggs_multi.out
  tsl/test/expected/continuous_aggs_query-10.out
  tsl/test/expected/continuous_aggs_query-11.out
  tsl/test/expected/continuous_aggs_query-12.out
  tsl/test/expected/continuous_aggs_query-9.6.out
  tsl/test/expected/continuous_aggs_union_view-10.out
  tsl/test/expected/continuous_aggs_union_view-11.out
  tsl/test/expected/continuous_aggs_union_view-12.out
  tsl/test/expected/continuous_aggs_union_view-9.6.out
  tsl/test/expected/jit-11.out
  tsl/test/expected/jit-12.out
  tsl/test/isolation/expected/continuous_aggs_multi.out
  tsl/test/isolation/specs/continuous_aggs_multi.spec
  tsl/test/sql/continuous_aggs_multi.sql
  tsl/test/sql/continuous_aggs_union_view.sql.in
Labels: continuous-aggs

#1904 Use test-specific assertions in C test code
  .travis.yml
  CMakeLists.txt
  test/expected/test_utils.out
  test/sql/CMakeLists.txt
  test/sql/test_utils.sql
  test/src/CMakeLists.txt
  test/src/adt_tests.c
  test/src/bgw/params.c
  test/src/bgw/scheduler_mock.c
  test/src/net/test_http.c
  test/src/test_time_to_internal.c
  test/src/test_utils.c
  test/src/test_utils.h
  test/src/test_with_clause_parser.c
  tsl/test/src/CMakeLists.txt
  tsl/test/src/test_compression.c
  tsl/test/src/test_ddl_hook.c
Labels: cleanup, testing

#1905 Release 1.7.1
  CHANGELOG.md
  sql/CMakeLists.txt
  version.config
Labels: release

#1893 Cleanup TODOs and FIXMEs
  CMakeLists.txt
  appveyor.yml
  sql/updates/0.6.1--0.7.0.sql
  sql/updates/1.4.2--1.5.0.sql
  sql/util_internal_table_ddl.sql
  src/adts/simplehash.h
  src/adts/vec.h
  src/extension.c
  src/plan_agg_bookend.c
  src/planner.c
  src/process_utility.c
  src/scanner.c
  src/scanner.h
  test/expected/constraint.out
  test/expected/sql_query-10.out
  test/expected/sql_query-11.out
  test/expected/sql_query-12.out
  test/expected/sql_query-9.6.out
  test/expected/triggers.out
  test/sql/constraint.sql
  test/sql/sql_query.sql.in
  test/sql/triggers.sql
  test/src/bgw/params.c
  test/src/bgw/scheduler_mock.c
  tsl/src/compression/compression.c
  tsl/src/compression/dictionary.c
  tsl/src/compression/dictionary_hash.h
  tsl/src/compression/gorilla.c
  tsl/src/compression/simple8b_rle.h
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/materialize.c
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/src/nodes/decompress_chunk/planner.c
  tsl/src/nodes/decompress_chunk/qual_pushdown.c
  tsl/src/nodes/gapfill/planner.c
  tsl/src/reorder.c
  tsl/test/CMakeLists.txt
  tsl/test/expected/bgw_policy.out
  tsl/test/expected/compress_table.out
  tsl/test/expected/compression.out
  tsl/test/expected/compression_algos.out
  tsl/test/expected/continuous_aggs_materialize.out
  tsl/test/expected/transparent_decompression-10.out
  tsl/test/expected/transparent_decompression-11.out
  tsl/test/expected/transparent_decompression-12.out
  tsl/test/isolation/specs/reorder_deadlock.spec.in
  tsl/test/sql/bgw_policy.sql
  tsl/test/sql/compress_table.sql
  tsl/test/sql/compression.sql
  tsl/test/sql/compression_algos.sql
  tsl/test/sql/continuous_aggs_materialize.sql
  tsl/test/sql/transparent_decompression.sql.in
Labels: cleanup

#1915 Check for database in extension_current_state
  CHANGELOG.md
  src/extension_utils.c
Labels: bug

#1913 Cleanup code coverage and make it work locally
  .travis.yml
  CMakeLists.txt
  codecov/CMakeLists.txt
  codecov/README.md
  test/CMakeLists.txt
Labels: cleanup, refactoring, testing

#1910 Update tests to run on newest PG
  .travis.yml
Labels: testing

#1922 Cleanup GUC names
  src/chunk_append/chunk_append.c
  src/constraint_aware_append.c
  src/guc.c
  src/guc.h
  src/plan_expand_hypertable.c
  src/planner.c
  test/expected/agg_bookends-10.out
  test/expected/agg_bookends-11.out
  test/expected/agg_bookends-12.out
  test/expected/agg_bookends-9.6.out
  test/expected/append-10.out
  test/expected/append-11.out
  test/expected/append-12.out
  test/expected/append-9.6.out
  test/expected/join.out
  test/expected/plan_expand_hypertable-10.out
  test/expected/plan_expand_hypertable-11.out
  test/expected/plan_expand_hypertable-12.out
  test/expected/plan_expand_hypertable-9.6.out
  test/expected/plan_hashagg-10.out
  test/expected/plan_hashagg-11.out
  test/expected/plan_hashagg-12.out
  test/expected/plan_hashagg-9.6.out
  test/expected/query-10.out
  test/expected/query-11.out
  test/expected/query-12.out
  test/expected/query-9.6.out
  test/expected/relocate_extension.out
  test/expected/rowsecurity-10.out
  test/runner.sh
  test/sql/agg_bookends.sql.in
  test/sql/append.sql.in
  test/sql/include/agg_bookends_query.sql
  test/sql/include/append_query.sql
  test/sql/include/join_query.sql
  test/sql/include/query_query.sql
  test/sql/join.sql
  test/sql/plan_expand_hypertable.sql.in
  test/sql/plan_hashagg.sql.in
  test/sql/query.sql.in
  test/sql/relocate_extension.sql
  test/sql/rowsecurity-10.sql
  tsl/test/sql/plan_gapfill-10.sql
Labels: docs-update-needed

#1936 Run 32 bit linux test as github action
  .github/workflows/alpine-32bit-build-and-test.yaml
  .travis.yml
Labels: testing
