Repository timescale/timescaledb, pull requests merged in 2020-12, with the labels that each got.

#2696 Support gapfill on distributed hypertable
  tsl/src/fdw/deparse.c
  tsl/src/nodes/gapfill/planner.c
  tsl/src/nodes/gapfill/planner.h
  tsl/src/planner.c
  tsl/test/expected/dist_api_calls.out
  tsl/test/sql/dist_api_calls.sql
Labels: Gap Fill, multinode

#2689 Check configuration in alter_job and add_job
  src/bgw/job.c
  src/bgw/job.h
  tsl/src/bgw_policy/job.c
  tsl/src/bgw_policy/job.h
  tsl/src/bgw_policy/job_api.c
  tsl/test/expected/continuous_aggs.out
  tsl/test/expected/continuous_aggs_errors.out
  tsl/test/expected/tsl_tables.out
  tsl/test/sql/bgw_custom.sql
  tsl/test/sql/continuous_aggs.sql
  tsl/test/sql/continuous_aggs_errors.sql
  tsl/test/sql/tsl_tables.sql
Labels: background-worker, ui/ux

#2662 Save compression metadata settings on access node
  sql/pre_install/tables.sql
  sql/updates/latest-dev.sql
  sql/views.sql
  src/catalog.h
  src/chunk.c
  src/hypertable.c
  src/hypertable.h
  src/process_utility.c
  test/expected/alter.out
  test/expected/alternate_users.out
  test/expected/create_hypertable.out
  test/expected/ddl.out
  test/expected/drop_extension.out
  test/expected/drop_hypertable.out
  test/expected/drop_owned.out
  test/expected/drop_rename_hypertable.out
  test/expected/drop_schema.out
  test/expected/dump_meta.out
  test/expected/pg_dump.out
  test/expected/relocate_extension.out
  test/expected/truncate.out
  tsl/src/bgw_policy/retention_api.c
  tsl/src/compression/create.c
  tsl/test/expected/compression.out
  tsl/test/expected/dist_compression.out
  tsl/test/expected/dist_hypertable-11.out
  tsl/test/expected/dist_hypertable-12.out
  tsl/test/expected/dist_views.out
  tsl/test/sql/compression.sql
  tsl/test/sql/dist_compression.sql
Labels: Compression

#2698 Improve memory handling for remote COPY
  src/copy.c
  src/cross_module_fn.c
  src/cross_module_fn.h
  tsl/src/remote/dist_copy.c
  tsl/src/remote/dist_copy.h
  tsl/test/expected/remote_copy.out
Labels: multinode

#2707 Introduce additional db for data node bootstrapping
  tsl/src/data_node.c
Labels: multinode

#2702 Release 2.0.0-rc4
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.0.0-rc3--2.0.0-rc4.sql
  sql/updates/latest-dev.sql
  version.config
Labels: release

#2709 Remove workaround for AT_CookedColumnDefault to build against snapshot
  src/build-defs.cmake
  src/process_utility.c
Labels: cleanup

#2703 Compare distributed gapfill test to single-node
  tsl/test/expected/dist_api_calls.out
  tsl/test/expected/dist_gapfill.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/dist_api_calls.sql
  tsl/test/sql/dist_gapfill.sql
  tsl/test/sql/include/dist_gapfill_query.sql
Labels: Gap Fill, multinode, testing

#2719 Support disabling compression on distributed hypertables
  src/hypertable.c
  src/hypertable.h
  tsl/src/compression/create.c
  tsl/test/expected/dist_compression.out
  tsl/test/sql/dist_compression.sql
Labels: bug

#2727 Run same table gapfill test on multinode
  tsl/test/shared/expected/dist_gapfill.out
  tsl/test/shared/expected/gapfill.out
  tsl/test/shared/sql/CMakeLists.txt
  tsl/test/shared/sql/dist_gapfill.sql
  tsl/test/shared/sql/gapfill.sql
  tsl/test/shared/sql/include/dist_gapfill_query.sql
  tsl/test/shared/sql/include/gapfill_metrics_query.sql
  tsl/test/shared/sql/include/shared_setup.sql
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/dist_gapfill.sql
Labels: Gap Fill, testing

#2746 Optimize locking for create chunk API
  src/chunk.c
  src/debug_wait.c
  tsl/test/isolation/expected/remote_create_chunk.out
  tsl/test/isolation/specs/CMakeLists.txt
  tsl/test/isolation/specs/remote_create_chunk.spec.in
Labels: enhancement, multinode

#2742 Fix compression status in chunks view for distributed chunks
  sql/views.sql
  tsl/test/expected/dist_compression.out
  tsl/test/expected/dist_views.out
Labels: docs-update-needed

#2751 Fix crash and cancel when adding data node
  tsl/src/data_node.c
  tsl/src/dist_util.c
  tsl/src/remote/connection.c
  tsl/test/expected/data_node.out
Labels: bug, multinode

#2756 Revert to blocking connection establishment
  tsl/src/remote/connection.c
Labels: multinode

#2753 Release 2.0.0
  CHANGELOG.md
  sql/CMakeLists.txt
  version.config
Labels: release

#2765 Revert "Release 2.0.0"
  CHANGELOG.md
  sql/CMakeLists.txt
  version.config
Labels: release

#2764 Bootstrap data nodes with versioned extension
  src/extension.c
  src/extension.h
  tsl/src/data_node.c
Labels: multinode

#2762 Remove unused field for ignoring invalidations
  src/hypertable.c
  src/hypertable.h
Labels: cleanup

#2766 Release 2.0.0
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.0.0-rc4--2.0.0.sql
  sql/updates/latest-dev.sql
  version.config
Labels: release

#2769 Add 2.0.0 to update test scripts
  scripts/test_updates_pg11.sh
  scripts/test_updates_pg12.sh
Labels: testing

#2772 Always validate existing database and extension
  tsl/src/data_node.c
  tsl/test/expected/data_node_bootstrap.out
  tsl/test/expected/dist_util.out
  tsl/test/sql/data_node_bootstrap.sql
Labels: multinode
