Repository timescale/timescaledb, pull requests merged in 2021-09, with the labels that each got.

#3566 Adjust code to PG14 FDW API changes
  tsl/src/fdw/fdw.c
Labels: pg14

#3565 Use LookupFuncWithArgs in bgw job lookup
  tsl/src/bgw_policy/job.c
Labels: pg14

#3520 Modify compression bgw chunk selection logic
  src/chunk.c
  src/chunk.h
  src/dimension_slice.c
  src/dimension_slice.h
  tsl/src/bgw_policy/compression_api.c
  tsl/src/bgw_policy/compression_api.h
  tsl/src/bgw_policy/job.c
  tsl/src/bgw_policy/job.h
  tsl/test/expected/compression_bgw.out
  tsl/test/expected/dist_compression.out
  tsl/test/sql/compression_bgw.sql
  tsl/test/sql/dist_compression.sql
  tsl/test/sql/include/recompress_basic.sql
Labels: documentation

#3555 Update prepare_sort_from_pathkeys import
  src/import/planner.c
Labels: pg14

#3590 Call cleanup functions on backend exit
  src/cache.c
  src/init.c
  tsl/src/init.c
  tsl/src/remote/connection_cache.c
Labels: multinode

#3599 Update connection cache on role changes
  src/cache_invalidate.c
  tsl/src/remote/connection_cache.c
  tsl/src/remote/connection_cache.h
  tsl/src/remote/dist_ddl.c
  tsl/test/expected/remote_connection_cache.out
  tsl/test/sql/remote_connection_cache.sql
  tsl/test/t/003_connections.pl
  tsl/test/t/CMakeLists.txt
Labels: multinode
