Repository timescale/timescaledb, pull requests merged in 2021-01, with the labels that each got.

#2723 Add support for PG13 List implementation
  .clang-format
  src/bgw/scheduler.c
  src/cache.c
  src/chunk_append/chunk_append.c
  src/chunk_append/exec.c
  src/compat.h
  src/import/planner.c
  src/plan_agg_bookend.c
  src/plan_expand_hypertable.c
  test/src/bgw/test_job_refresh.c
  tsl/src/continuous_aggs/create.c
  tsl/src/debug.c
  tsl/src/fdw/deparse.c
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/src/nodes/decompress_chunk/exec.c
  tsl/src/nodes/gapfill/planner.c
Labels: PG13

#2734 Adjust code to PG13 list sort changes
  src/bgw/scheduler.c
Labels: PG13

#2780 Fix config enum entries for remote data fetcher
  src/guc.c
Labels: bug

#2741 Adjust copy code to PG13 addRTEtoQuery changes
  src/copy.c
Labels: PG13

#2738 Adjust code to PG13 convert_tuples_by_name signature change
  src/chunk_insert_state.c
  src/compat.h
  tsl/src/fdw/modify_exec.c
Labels: PG13

#2787 Adjust jsonb_utils to PG13 changes
  src/jsonb_utils.c
Labels: PG13

#2786 Adjust decompress code to Var field renames
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
Labels: PG13

#2800 Lock dimension slices when creating new chunk
  src/chunk.c
  src/chunk.h
  src/dimension_slice.c
  src/dimension_slice.h
  src/hypercube.c
  src/hypertable.c
  test/isolation/expected/dropchunks_race.out
  test/isolation/specs/dropchunks_race.spec.in
Labels: bug

#2552 Repair dimension slice table on update
  sql/updates/latest-dev.sql
  test/sql/updates/post.post_insert.sql
Labels: 1.7

#2828 Improve cagg watermark caching
  src/continuous_agg.c
  tsl/test/expected/continuous_aggs_query-11.out
  tsl/test/expected/continuous_aggs_query-12.out
  tsl/test/sql/continuous_aggs_query.sql.in
Labels: enhancement, performance

#2860 Fix projection in ChunkAppend nodes
  src/chunk_append/planner.c
  test/expected/append-11.out
  test/expected/append-12.out
  test/sql/include/append_load.sql
  test/sql/include/append_query.sql
Labels: bug, planner

#2861 Remove compression stat update from update script
  sql/updates/2.0.0-rc3--2.0.0-rc4.sql
  test/sql/updates/post.compression.sql
Labels: Compression, docs-update-needed, update-script

#2845 Fix continuous aggregate privileges during upgrade
  CHANGELOG.md
  scripts/test_update_from_tag.sh
  sql/updates/latest-dev.sql
  test/sql/updates/post.continuous_aggs.sql
  test/sql/updates/setup.continuous_aggs.sql
  test/sql/updates/setup.continuous_aggs.v2.sql
  test/sql/updates/setup.roles.sql
Labels: bug, permissions, update-script

#2851 Fix nested loop joins that involve compressed chunks
  CHANGELOG.md
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/test/expected/transparent_decompression_ordered_index-11.out
  tsl/test/expected/transparent_decompression_ordered_index-12.out
  tsl/test/sql/include/transparent_decompression_ordered_index.sql
Labels: bug, planner

#2868 Fix corruption in gapfill plan
  CHANGELOG.md
  tsl/src/nodes/gapfill/planner.c
  tsl/test/shared/expected/gapfill.out
  tsl/test/shared/sql/gapfill.sql
Labels: bug

#2866 Avoid partitionwise planning of partialize_agg
  CHANGELOG.md
  src/plan_expand_hypertable.c
  src/plan_partialize.c
  src/plan_partialize.h
  src/planner.c
  tsl/test/expected/continuous_aggs.out
  tsl/test/expected/partialize_finalize.out
  tsl/test/sql/continuous_aggs.sql
  tsl/test/sql/dist_partial_agg.sql
  tsl/test/sql/dist_query.sql.in
  tsl/test/sql/partialize_finalize.sql
Labels: bug

#2874 Fix partitionwise agg crash due to uninitialized memory
  src/plan_expand_hypertable.c
Labels: bug

#2870 Release 2.0.1
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.0.0--2.0.1.sql
  sql/updates/latest-dev.sql
  version.config
Labels: release
