Repository timescale/timescaledb, pull requests merged in 2021-02, with the labels that each got.

#2885 Fix compressed chunk check when disabling compression
  sql/updates/latest-dev.sql
  src/chunk.c
  tsl/test/expected/compression_ddl.out
  tsl/test/sql/include/compression_alter.sql
Labels: bug

#2893 Change bootstrap and CMake defaults
  .github/workflows/coverity.yaml
  CMakeLists.txt
  scripts/gh_matrix_builder.py
Labels: build

#2935 Release 1.7.5
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/1.7.4--1.7.5.sql
  sql/updates/1.7.5--2.0.0-rc1.sql
Labels: release

#2938 Add row security tests for PG13
  test/expected/rowsecurity-13.out
  test/sql/CMakeLists.txt
  test/sql/rowsecurity-13.sql
Labels: PG13

#2947 Fix flaky distributed hypertable test on PG13
  tsl/test/expected/dist_hypertable-11.out
  tsl/test/expected/dist_hypertable-12.out
  tsl/test/expected/dist_hypertable-13.out
  tsl/test/sql/dist_hypertable.sql.in
Labels: flaky-test

#2919 Add test to check PARALLEL VACUUM functionality with PG13
  test/expected/vacuum_parallel.out
  test/sql/CMakeLists.txt
  test/sql/vacuum_parallel.sql
Labels: PG13, testing

#2956 Disable strict-overflow for gcc < 8
  CMakeLists.txt
Labels: build

#2957 Fix sanitizer test
  scripts/test_sanitizers.sh
Labels: testing

#2958 Add string mapping for CONNECTION_CHECK_TARGET
  tsl/src/remote/connection_cache.c
Labels: PG13

#2909 Support column renames on tables that have compression enabled.
  CHANGELOG.md
  src/cross_module_fn.c
  src/cross_module_fn.h
  src/hypertable_compression.c
  src/hypertable_compression.h
  src/process_utility.c
  tsl/src/compression/compression.c
  tsl/src/compression/create.c
  tsl/src/compression/create.h
  tsl/src/init.c
  tsl/src/process_utility.c
  tsl/src/process_utility.h
  tsl/test/expected/compression_ddl.out
  tsl/test/expected/dist_compression.out
  tsl/test/sql/compression_ddl.sql
  tsl/test/sql/dist_compression.sql
  tsl/test/sql/include/compression_alter.sql
Labels: Compression

#2961 Release 2.0.2
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.0.1--2.0.2.sql
  sql/updates/latest-dev.sql
  version.config
Labels: release

#2965 Release 2.0.2
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.0.1--2.0.2.sql
  sql/updates/latest-dev.sql
  version.config
Labels: release

#2962 Release 2.1.0
  CHANGELOG.md
  sql/CMakeLists.txt
  version.config
Labels: release

#2843 Add distributed restore point functionality
  sql/ddl_api.sql
  src/cross_module_fn.c
  src/cross_module_fn.h
  src/debug_wait.h
  test/expected/extension.out
  tsl/src/CMakeLists.txt
  tsl/src/dist_backup.c
  tsl/src/dist_backup.h
  tsl/src/init.c
  tsl/src/remote/txn.c
  tsl/test/expected/dist_backup.out
  tsl/test/isolation/expected/dist_restore_point.out
  tsl/test/isolation/specs/CMakeLists.txt
  tsl/test/isolation/specs/dist_restore_point.spec.in
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/dist_backup.sql
Labels: docs-update-needed

#2986 Fix mismatched dsm_attach/dsm_detach calls
  test/src/bgw/params.c
Labels: bug, testing
