Repository timescale/timescaledb, pull requests merged in 2021-12, with the labels that each got.

#3867 Add package test for Ubuntu 21.10
  .github/workflows/apt-packages.yaml
Labels: packaging

#3853 Handle default privileges on distributed databases
  tsl/src/deparse.c
  tsl/src/deparse.h
  tsl/src/remote/dist_ddl.c
  tsl/test/expected/dist_grant-12.out
  tsl/test/expected/dist_grant-13.out
  tsl/test/expected/dist_grant-14.out
  tsl/test/sql/dist_grant.sql.in
Labels: multinode

#3886 Post release 2.5.1
  scripts/test_updates_pg12.sh
  scripts/test_updates_pg13.sh
  scripts/test_updates_pg14.sh
  sql/CMakeLists.txt
  sql/updates/2.5.1--2.5.0.sql
  sql/updates/reverse-dev.sql
  version.config
Labels: 2.5.1

#3933 Refactoring: get rid of max_bucket_width
  sql/cagg_utils.sql
  src/catalog.h
  src/continuous_agg.c
  src/continuous_agg.h
  tsl/src/bgw_policy/continuous_aggregate_api.c
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/invalidation.c
  tsl/src/continuous_aggs/refresh.c
  tsl/src/continuous_aggs/refresh.h
Labels: tech-debt

#3929 Add option to drop database when deleting data node
  sql/ddl_api.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  tsl/src/data_node.c
  tsl/src/remote/connection.c
  tsl/src/remote/connection.h
  tsl/test/expected/data_node_bootstrap.out
  tsl/test/sql/data_node_bootstrap.sql
Labels: documentation, multinode, ui/ux, low-hanging-fruit

#3940 Fix compilation against PG15
  tsl/src/deparse.c
Labels: pg15

#3923 Allow changing a data node via alter server
  src/process_utility.c
  tsl/test/expected/data_node.out
  tsl/test/sql/data_node.sql
Labels: multinode, enhancement

#3941 Override the default ACL for public schema on PG15
  test/runner.sh
  tsl/src/data_node.c
Labels: pg15

#3946 Don't display an error message when creating an empty CAGG
  tsl/src/continuous_aggs/invalidation_threshold.c
  tsl/test/expected/continuous_aggs_variable_size_buckets.out
  tsl/test/sql/continuous_aggs_variable_size_buckets.sql
Labels: time_bucket_ng
