Repository timescale/timescaledb, pull requests merged in 2021-03, with the labels that each got.

#2805 Annotate fallthrough with TS_FALLTHROUGH
  tsl/src/reorder.c
Labels: build

#3013 Refactor regresscheck-t database creation
  tsl/test/expected/chunk_api-11.out
  tsl/test/expected/chunk_api-12.out
  tsl/test/expected/chunk_api-13.out
  tsl/test/expected/data_fetcher.out
  tsl/test/expected/data_node.out
  tsl/test/expected/data_node_bootstrap.out
  tsl/test/expected/debug_notice.out
  tsl/test/expected/dist_api_calls.out
  tsl/test/expected/dist_backup.out
  tsl/test/expected/dist_commands.out
  tsl/test/expected/dist_grant.out
  tsl/test/expected/dist_hypertable_am.out
  tsl/test/expected/dist_hypertable_with_oids.out
  tsl/test/expected/dist_partial_agg.out
  tsl/test/expected/dist_query-11.out
  tsl/test/expected/dist_query-12.out
  tsl/test/expected/dist_query-13.out
  tsl/test/expected/dist_util.out
  tsl/test/expected/remote_connection_cache.out
  tsl/test/expected/remote_copy-11.out
  tsl/test/expected/remote_copy-12.out
  tsl/test/expected/remote_copy-13.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/chunk_api.sql.in
  tsl/test/sql/data_fetcher.sql
  tsl/test/sql/data_node.sql
  tsl/test/sql/data_node_bootstrap.sql
  tsl/test/sql/debug_notice.sql
  tsl/test/sql/dist_api_calls.sql
  tsl/test/sql/dist_backup.sql
  tsl/test/sql/dist_commands.sql
  tsl/test/sql/dist_grant.sql
  tsl/test/sql/dist_hypertable_am.sql
  tsl/test/sql/dist_hypertable_with_oids.sql
  tsl/test/sql/dist_partial_agg.sql
  tsl/test/sql/dist_query.sql.in
  tsl/test/sql/dist_util.sql
  tsl/test/sql/include/data_fetcher_load.sql
  tsl/test/sql/include/dist_query_load.sql
  tsl/test/sql/remote_connection_cache.sql
  tsl/test/sql/remote_copy.sql.in
Labels: cleanup, testing

#3045 Make data_fetcher solo test to fix failing tests
  tsl/test/sql/CMakeLists.txt
Labels: flaky-test

#2989 Refactor and harden size and stats functions
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/size_utils.sql
  sql/updates/latest-dev.sql
  test/expected/relocate_extension.out
  test/expected/size_utils.out
  test/isolation/expected/multi_transaction_indexing.out
  test/sql/size_utils.sql
  tsl/test/expected/compression.out
  tsl/test/expected/dist_compression.out
  tsl/test/expected/dist_hypertable-11.out
  tsl/test/expected/dist_hypertable-12.out
  tsl/test/expected/dist_hypertable-13.out
  tsl/test/expected/dist_util.out
  tsl/test/expected/dist_views.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/dist_util.sql
Labels: ui/ux

#3061 Add 2.1.0 to update test scripts
  scripts/test_updates_pg11.sh
  scripts/test_updates_pg12.sh
Labels: release

#3053 Fix gapfill/hashagg planner interaction
  CHANGELOG.md
  src/plan_add_hashagg.c
  tsl/test/shared/expected/gapfill-11.out
  tsl/test/shared/expected/gapfill-12.out
  tsl/test/shared/expected/gapfill-13.out
  tsl/test/shared/sql/gapfill.sql.in
Labels: bug, planner

#3058 Reduce memory usage for distributed inserts
  CHANGELOG.md
  tsl/src/data_node_dispatch.c
Labels: multinode

#3067 Fix chunks_in queries to use ChunkAppend plans
  CHANGELOG.md
  src/hypertable_restrict_info.c
  src/hypertable_restrict_info.h
  src/plan_expand_hypertable.c
  tsl/test/expected/dist_hypertable-11.out
  tsl/test/expected/dist_hypertable-12.out
  tsl/test/expected/dist_hypertable-13.out
  tsl/test/sql/dist_hypertable.sql.in
Labels: multinode, performance
