Repository timescale/timescaledb, pull requests merged in 2021-06, with the labels that each got.

#3298 Remove TTSOps pointer macros
  src/compat.h
  src/event_trigger.c
  tsl/src/compression/compression.c
  tsl/src/nodes/gapfill/exec.c
Labels: cleanup

#3299 Detect TAP test prerequisites with CMake
  .github/workflows/linux-build-and-test.yaml
  .github/workflows/windows-build-and-test.yaml
  CMakeLists.txt
  appveyor.yml
  scripts/docker-build.sh
  tsl/test/CMakeLists.txt
Labels: testing

#3301 Use ExecComputeStoredGeneratedCompat macro
  src/copy.c
  tsl/src/nodes/data_node_copy.c
  tsl/src/nodes/data_node_dispatch.c
Labels: cleanup

#3306 Run ABI tests with TAP support
  .github/workflows/coverity.yaml
  scripts/docker-run-abi-test.sh
Labels: testing

#3302 Move internal API functions to experimental schema
  sql/CMakeLists.txt
  sql/ddl_experimental.sql
  sql/ddl_internal.sql
  sql/updates/latest-dev.sql
  tsl/test/expected/continuous_aggs_ddl.out
  tsl/test/expected/continuous_aggs_drop_chunks.out
  tsl/test/expected/continuous_aggs_errors.out
  tsl/test/expected/data_node.out
  tsl/test/sql/continuous_aggs_ddl.sql
  tsl/test/sql/continuous_aggs_drop_chunks.sql
  tsl/test/sql/continuous_aggs_errors.sql
  tsl/test/sql/data_node.sql
Labels: cleanup

#3327 Make aggregate in caggs fully qualified
  CHANGELOG.md
  sql/updates/post-update.sql
  tsl/src/continuous_aggs/create.c
  tsl/test/expected/continuous_aggs_query-12.out
  tsl/test/expected/continuous_aggs_query-13.out
  tsl/test/expected/continuous_aggs_union_view-12.out
  tsl/test/expected/continuous_aggs_union_view-13.out
  tsl/test/expected/jit-12.out
  tsl/test/expected/jit-13.out
Labels: bug, continuous_aggregate

#3194 Constify parameters and return values of core APIs
  src/bgw/job.c
  src/chunk.c
  src/chunk.h
  src/chunk_adaptive.c
  src/chunk_constraint.c
  src/chunk_constraint.h
  src/chunk_data_node.c
  src/chunk_data_node.h
  src/chunk_index.c
  src/continuous_agg.c
  src/continuous_agg.h
  src/cross_module_fn.c
  src/cross_module_fn.h
  src/dimension.c
  src/dimension.h
  src/dimension_slice.c
  src/dimension_slice.h
  src/dimension_vector.c
  src/dimension_vector.h
  src/hypercube.c
  src/hypercube.h
  src/hypertable.c
  src/hypertable.h
  src/hypertable_data_node.c
  src/hypertable_data_node.h
  src/indexing.c
  src/indexing.h
  src/process_utility.c
  src/scanner.h
  src/subspace_store.c
  src/subspace_store.h
  src/tablespace.c
  src/tablespace.h
  src/trigger.c
  src/trigger.h
  tsl/src/bgw_policy/compression_api.c
  tsl/src/bgw_policy/job.c
  tsl/src/bgw_policy/reorder_api.c
  tsl/src/bgw_policy/retention_api.c
  tsl/src/chunk_api.c
  tsl/src/chunk_api.h
  tsl/src/compression/create.c
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/materialize.c
  tsl/src/continuous_aggs/materialize.h
  tsl/src/continuous_aggs/refresh.c
  tsl/src/data_node.c
  tsl/src/fdw/data_node_chunk_assignment.c
  tsl/src/fdw/data_node_scan_plan.c
  tsl/src/fdw/relinfo.c
Labels: cleanup

#3329 Fix flaky pg_dump test
  test/expected/pg_dump.out
  test/sql/pg_dump.sql
Labels: testing

#3300 Improve trigger handling on distributed hypertables
  src/process_utility.c
  test/sql/utils/testsupport.sql
  tsl/src/deparse.c
  tsl/src/deparse.h
  tsl/src/remote/connection.c
  tsl/src/remote/dist_ddl.c
  tsl/test/expected/dist_compression.out
  tsl/test/expected/dist_ddl.out
  tsl/test/expected/dist_triggers.out
  tsl/test/sql/dist_compression.sql
  tsl/test/sql/dist_ddl.sql
  tsl/test/sql/dist_triggers.sql
  tsl/test/sql/include/deparse_create.sql
Labels: multinode

#3344 Add missing ORDER BY clause to dist_hypertable test
  tsl/test/expected/dist_hypertable-12.out
  tsl/test/expected/dist_hypertable-13.out
  tsl/test/sql/dist_hypertable.sql.in
Labels: flaky-test, testing

#3346 Move timestamp_limits and with_clause_parser test
  test/sql/CMakeLists.txt
  tsl/test/shared/expected/timestamp_limits.out
  tsl/test/shared/expected/with_clause_parser.out
  tsl/test/shared/sql/CMakeLists.txt
  tsl/test/shared/sql/include/shared_setup.sql
  tsl/test/shared/sql/timestamp_limits.sql
  tsl/test/shared/sql/with_clause_parser.sql
Labels: cleanup, testing
