Repository timescale/timescaledb, pull requests merged in 2021-04, with the labels that each got.

#3081 Allow use of wildcards in TESTS
  test/pg_regress.sh
Labels: testing

#3087 Install clang-8 for PG11.0 CI test
  scripts/gh_matrix_builder.py
Labels: testing

#3076 Refactor chunk creation for future extension
  src/catalog.c
  src/catalog.h
  src/chunk.c
  src/chunk.h
  src/chunk_constraint.c
  src/hypercube.c
  src/hypercube.h
  src/hypertable.c
  src/hypertable.h
  tsl/src/chunk_api.c
Labels: multinode

#3100 Fix command execution in pr-validation
  .github/workflows/pr-validation.yaml
Labels: security

#3110 Add 2.2.0 to update test scripts
  scripts/test_updates_pg11.sh
  scripts/test_updates_pg12.sh
  scripts/test_updates_pg13.sh
Labels: release

#3104 Fix use after free in add_reorder_policy
  CHANGELOG.md
  tsl/src/bgw_policy/reorder_api.c
Labels: bug, segfault

#3113 Add "SELECT DISTINCT" pushdown in multi-node
  CHANGELOG.md
  src/utils.h
  tsl/src/fdw/deparse.c
  tsl/test/expected/dist_hypertable-11.out
  tsl/test/expected/dist_hypertable-12.out
  tsl/test/expected/dist_hypertable-13.out
  tsl/test/expected/dist_query-11.out
  tsl/test/expected/dist_query-12.out
  tsl/test/expected/dist_query-13.out
  tsl/test/shared/expected/dist_distinct.out
  tsl/test/shared/sql/CMakeLists.txt
  tsl/test/shared/sql/dist_distinct.sql
  tsl/test/shared/sql/include/dist_distinct_run.sql
Labels: multinode

#3151 Fix fdw_relinfo_get assertion failure on DELETE
  CHANGELOG.md
  tsl/src/fdw/relinfo.c
  tsl/src/fdw/relinfo.h
  tsl/test/expected/dist_hypertable-11.out
  tsl/test/expected/dist_hypertable-12.out
  tsl/test/expected/dist_hypertable-13.out
  tsl/test/sql/dist_hypertable.sql.in
Labels: bug, multinode, segfault

#3155 Inherit CFLAGS from postgresql
  CHANGELOG.md
  CMakeLists.txt
  src/build-defs.cmake
  tsl/src/build-defs.cmake
Labels: bug, segfault

#3137 Create an empty chunk table
  sql/chunk.sql
  src/chunk.c
  src/chunk.h
  src/cross_module_fn.c
  src/cross_module_fn.h
  src/dimension.c
  tsl/src/chunk_api.c
  tsl/src/chunk_api.h
  tsl/src/init.c
  tsl/test/expected/chunk_api-11.out
  tsl/test/expected/chunk_api-12.out
  tsl/test/expected/chunk_api-13.out
  tsl/test/sql/chunk_api.sql.in
Labels: multinode

#3156 Add coredump support for 32bit ci runs
  .github/workflows/linux-32bit-build-and-test.yaml
Labels: testing

#3174 Drop inherit from chunk table to hypertable
  src/chunk.c
  tsl/test/expected/chunk_api-11.out
  tsl/test/expected/chunk_api-12.out
  tsl/test/expected/chunk_api-13.out
  tsl/test/sql/chunk_api.sql.in
Labels: multinode

#3171 Create chunk table from access node
  sql/ddl_internal.sql
  src/cross_module_fn.c
  src/cross_module_fn.h
  tsl/src/chunk.c
  tsl/src/chunk.h
  tsl/src/chunk_api.c
  tsl/src/chunk_api.h
  tsl/src/data_node.c
  tsl/src/data_node.h
  tsl/src/init.c
  tsl/src/remote/dist_commands.c
  tsl/src/remote/dist_commands.h
  tsl/test/shared/expected/dist_chunk.out
  tsl/test/shared/sql/CMakeLists.txt
  tsl/test/shared/sql/dist_chunk.sql
  tsl/test/shared/sql/include/shared_setup.sql
Labels: multinode
