Repository timescale/timescaledb, pull requests merged in 2022-03, with the labels that each got.

#4146 Refactor function `hypertable_local_size`
  sql/size_utils.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  src/telemetry/stats.c
  src/utils.c
  src/utils.h
  test/expected/relocate_extension.out
  test/expected/size_utils.out
  test/sql/size_utils.sql
  tsl/src/compression/compress_utils.c
  tsl/test/expected/compression.out
  tsl/test/expected/dist_util.out
  tsl/test/sql/dist_util.sql
Labels: bug, tech-debt

#4151 Enhance extension function test
  test/expected/extension.out
  test/sql/CMakeLists.txt
  test/sql/extension.sql
  tsl/test/shared/expected/extension.out
  tsl/test/shared/sql/CMakeLists.txt
  tsl/test/shared/sql/extension.sql
Labels: ci

#4150 Add workflow for running sqlsmith
  .github/workflows/sqlsmith.yaml
Labels: ci

#4164 Trigger Sqlsmith tests manually or by push to branch
  .github/workflows/sqlsmith.yaml
Labels: testing

#4184 Set minimum required cmake version to 3.10
  CMakeLists.txt
Labels: packaging

#4141 Improve restriction scanning during hypertable expansion
  sql/pre_install/tables.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  src/chunk.c
  src/chunk_constraint.c
  src/chunk_scan.c
  src/dimension_slice.c
  src/dimension_slice.h
  src/dimension_vector.c
  src/hypertable_restrict_info.c
  src/ts_catalog/catalog.c
  src/ts_catalog/catalog.h
  tsl/test/expected/chunk_api.out
Labels: performance, tech-debt
