Repository timescale/timescaledb, pull requests merged in 2022-05, with the labels that each got.

#4313 Telemetry Stats for CAggs finals form
  src/telemetry/stats.c
  src/telemetry/stats.h
  src/telemetry/telemetry.c
  src/ts_catalog/continuous_agg.h
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/refresh.c
  tsl/test/expected/telemetry_stats.out
  tsl/test/sql/telemetry_stats.sql
Labels: continuous_aggregate, enhancement, telemetry, Core Database Team

#4344 Fix build failure on PG12.0
  test/src/test_utils.c
Labels: Query Experience Team

#4349 Fix crashes in functions using AlterTableInternal
  src/chunk.c
  src/chunk_index.c
  src/dimension.c
  src/ts_catalog/tablespace.c
  src/utils.c
  src/utils.h
  test/expected/tablespace.out
  test/sql/tablespace.sql
  tsl/src/compression/compress_utils.c
  tsl/src/compression/create.c
  tsl/src/reorder.c
  tsl/test/expected/compression_ddl.out
  tsl/test/expected/move.out
  tsl/test/sql/compression_ddl.sql
  tsl/test/sql/move.sql
Labels: bug

#4358 Fix crash and other issues in telemetry reporter
  CHANGELOG.md
  src/telemetry/stats.c
  src/telemetry/telemetry.c
  tsl/test/isolation/expected/telemetry.out
  tsl/test/isolation/specs/CMakeLists.txt
  tsl/test/isolation/specs/telemetry.spec.in
Labels: bug, telemetry

#4373 Fix PG13.2 isolation tests
  scripts/gh_matrix_builder.py
Labels: ci
