Repository timescale/timescaledb, pull requests merged in 2022-10, with the labels that each got.

#4785 Adjust pgspot CI check
  .github/workflows/pgspot.yaml
Labels: ci

#4794 Improve size utils functions and views performance
  sql/size_utils.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
Labels: performance, core, enhancement, Core Database Team

#4746 Fix missing upgrade/downgrade tests DDL validation
  scripts/test_downgrade_from_tag.sh
  test/sql/updates/post.catalog.sql
Labels: testing, upgrade, ci, tech-debt, downgrade, Core Database Team

#4806 Increase timeout to wait for cluster start
  .github/workflows/windows-build-and-test.yaml
Labels: ci

#4805 Improve job_crash_log test
  tsl/test/t/006_job_crash_log.pl
Labels: ci

#4801 Fix libpq disconnect for PG15
  tsl/src/remote/connection.c
Labels: pg15

#4476 Batch rows on access node for distributed COPY
  src/guc.c
  src/guc.h
  test/src/test_utils.c
  tsl/src/nodes/data_node_copy.c
  tsl/src/remote/connection.c
  tsl/src/remote/dist_copy.c
  tsl/src/remote/dist_copy.h
  tsl/test/expected/dist_copy_format_long.out
  tsl/test/expected/dist_copy_long.out
  tsl/test/expected/remote_copy-12.out
  tsl/test/expected/remote_copy-13.out
  tsl/test/expected/remote_copy-14.out
  tsl/test/shared/expected/dist_remote_error.out
  tsl/test/shared/sql/.gitignore
  tsl/test/shared/sql/dist_remote_error.sql
  tsl/test/sql/.gitignore
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/dist_copy_format_long.sql
  tsl/test/sql/dist_copy_long.sql
  tsl/test/sql/remote_copy.sql.in
Labels: performance, multinode

#4813 Adjust TAP tests permissions
  tsl/test/t/002_chunk_copy_move.pl
  tsl/test/t/003_connections_privs.pl
Labels: pg15

#4841 Adjust partition pruning to support PG15
  src/planner/expand_hypertable.c
  test/src/test_utils.c
  tsl/src/fdw/data_node_scan_plan.c
Labels: pg15

#4822 Miss segmentby compression option in CAGGs
  tsl/src/continuous_aggs/options.c
  tsl/test/expected/continuous_aggs.out
  tsl/test/expected/telemetry_stats.out
Labels: bug, continuous_aggregate, compression, Core Database Team

#4843 Bump github action versions
  .github/workflows/abi.yaml
  .github/workflows/apt-arm-packages.yaml
  .github/workflows/apt-packages.yaml
  .github/workflows/coccinelle.yaml
  .github/workflows/code_style.yaml
  .github/workflows/coverity.yaml
  .github/workflows/cron-tests.yaml
  .github/workflows/homebrew.yaml
  .github/workflows/linux-32bit-build-and-test.yaml
  .github/workflows/linux-build-and-test.yaml
  .github/workflows/memory-tests.yaml
  .github/workflows/pgspot.yaml
  .github/workflows/pr-validation.yaml
  .github/workflows/pull-review.yaml
  .github/workflows/release.yaml
  .github/workflows/rpm-packages.yaml
  .github/workflows/sanitizer-build-and-test.yaml
  .github/workflows/shellcheck.yaml
  .github/workflows/sqlsmith.yaml
  .github/workflows/update-test.yaml
  .github/workflows/windows-build-and-test.yaml
  .github/workflows/windows-packages.yaml
Labels: ci, Core Database Team

#4853 Bump codecov github action version
  .github/workflows/linux-build-and-test.yaml
Labels: ci, Core Database Team

#4831 Fix unused sort in dimension partition lookup
  src/ts_catalog/dimension_partition.c
Labels: multinode

#4840 Fix performance regressions in the copy code
  CHANGELOG.md
  src/copy.c
  test/expected/copy_memory_usage.out
  test/sql/copy_memory_usage.sql
Labels: performance

#4731 Add health check function
  sql/ddl_internal.sql
  sql/updates/reverse-dev.sql
  src/cross_module_fn.c
  src/cross_module_fn.h
  tsl/src/init.c
  tsl/src/remote/CMakeLists.txt
  tsl/src/remote/healthcheck.c
  tsl/src/remote/healthcheck.h
  tsl/test/expected/dist_commands.out
  tsl/test/shared/expected/extension.out
  tsl/test/sql/dist_commands.sql
  tsl/test/t/007_healthcheck.pl
  tsl/test/t/CMakeLists.txt
Labels: multinode

#4862 Fix GitHub output action
  .github/gh_config_reader.py
  .github/gh_matrix_builder.py
  .github/workflows/abi.yaml
  .github/workflows/apt-arm-packages.yaml
  .github/workflows/apt-packages.yaml
  .github/workflows/linux-32bit-build-and-test.yaml
  .github/workflows/linux-build-and-test.yaml
  .github/workflows/rpm-packages.yaml
  .github/workflows/sanitizer-build-and-test.yaml
  .github/workflows/sqlsmith.yaml
  .github/workflows/windows-build-and-test.yaml
  .github/workflows/windows-packages.yaml
Labels: ci

#4871 Fix ereport call in job schedule for PG 12.0
  src/bgw/job.c
Labels: build, pg12, ci, Core Database Team

#4882 Remove useless message from tsl_cagg_try_repair
  tsl/src/continuous_aggs/create.c
Labels: continuous_aggregate, tech-debt

#4886 Refactor Continuous Aggregate catalog code
  src/ts_catalog/continuous_agg.c
  src/ts_catalog/continuous_agg.h
Labels: continuous_aggregate, tech-debt, Core Database Team
