Repository timescale/timescaledb, pull requests merged in 2022-09, with the labels that each got.

#4658 GROUP BY error when setting compress_segmentby with an enum column
  CHANGELOG.md
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/test/expected/compression_errors.out
  tsl/test/sql/compression_errors.sql
Labels: bug, compression, Core Database Team

#4686 Add CAGG migration permission tests
  tsl/test/expected/cagg_migrate_integer.out
  tsl/test/expected/cagg_migrate_integer_dist_ht.out
  tsl/test/expected/cagg_migrate_timestamp.out
  tsl/test/expected/cagg_migrate_timestamp_dist_ht.out
  tsl/test/sql/include/cagg_migrate_common.sql
Labels: testing, continuous_aggregate, enhancement, Core Database Team

#4694 Change parameter names of cagg_migrate procedure
  .github/workflows/pgspot.yaml
  sql/cagg_migrate.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  tsl/test/expected/cagg_migrate_integer.out
  tsl/test/expected/cagg_migrate_integer_dist_ht.out
  tsl/test/expected/cagg_migrate_timestamp.out
  tsl/test/expected/cagg_migrate_timestamp_dist_ht.out
  tsl/test/sql/include/cagg_migrate_common.sql
Labels: continuous_aggregate, tech-debt, migration, Core Database Team

#4715 Fix vacuum_set_xid_limits_compat() macro
  src/compat/compat.h
Labels: pg15

#4739 Fix continuous aggregate migrate check constraint
  CHANGELOG.md
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
Labels: bug, continuous_aggregate, Core Database Team

#4713 Fix Continuous Aggregate migration policies
  sql/cagg_migrate.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  tsl/test/expected/cagg_migrate_integer.out
  tsl/test/expected/cagg_migrate_integer_dist_ht.out
  tsl/test/expected/cagg_migrate_timestamp.out
  tsl/test/expected/cagg_migrate_timestamp_dist_ht.out
  tsl/test/sql/include/cagg_migrate_common.sql
Labels: bug, continuous_aggregate, compression, Core Database Team

#4734 Port perl tests to support PG15
  test/CMakeLists.txt
  test/perl/TimescaleNode.pm
  test/pg_prove.sh
  test/t/001_extension.pl
  test/t/002_replication_telemetry.pl
  tsl/test/CMakeLists.txt
  tsl/test/t/001_simple_multinode.pl
  tsl/test/t/002_chunk_copy_move.pl
  tsl/test/t/003_connections_privs.pl
  tsl/test/t/004_multinode_rdwr_1pc.pl
  tsl/test/t/005_add_data_node.pl
Labels: pg15

#4745 Hypertable FK reference to PostgreSQL partitioned table
  CHANGELOG.md
  src/chunk_constraint.c
  test/expected/create_hypertable.out
  test/sql/create_hypertable.sql
Labels: bug

#4756 Improve compression job IO performance
  CHANGELOG.md
  tsl/src/compression/api.c
  tsl/src/compression/compression.c
Labels: performance, compression
