Repository timescale/timescaledb, pull requests merged in 2022-07, with the labels that each got.

#4493 Segfault when executing IMMUTABLE functions
  CHANGELOG.md
  src/planner/planner.c
  test/expected/ddl-12.out
  test/expected/ddl-13.out
  test/expected/ddl-14.out
  test/sql/ddl.sql.in
Labels: bug, segfault, Core Database Team

#4488 Add a distributed COPY test with more data
  tsl/test/expected/dist_copy_long.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/data/prices-100k-random-1.tsv.gz
  tsl/test/sql/data/prices-10k-random-1.tsv.gz
  tsl/test/sql/dist_copy_long.sql
Labels: performance, multinode

#4439 Enable ORDER BY on Continuous Aggregates
  tsl/src/continuous_aggs/create.c
  tsl/test/expected/cagg_errors.out
  tsl/test/expected/continuous_aggs.out
  tsl/test/sql/cagg_errors.sql
  tsl/test/sql/continuous_aggs.sql
Labels: ui/ux, continuous_aggregate, enhancement, Core Database Team

#4558 Fix hash_create calls without HASH_CONTEXT flag
  coccinelle/hash_create.cocci
  src/cache.c
  tsl/src/fdw/data_node_chunk_assignment.c
  tsl/src/fdw/shippable.c
Labels: ci
