Repository timescale/timescaledb, pull requests merged in 2023-08, with the labels that each got.

#5889 PG16: Remove recursion-marker values in enum AlterTableType
  src/process_utility.c
  tsl/src/process_utility.c
  tsl/src/remote/dist_ddl.c
Labels: pg16

#5925 Backport to 2.11.x: #5909: Support CREATE INDEX ONLY ON main table
  .unreleased/bugfix_5909
  src/process_utility.c
  test/expected/index.out
  test/sql/index.sql
Labels: is-auto-backport

#5921 PG16: ExecInsertIndexTuples requires additional parameter
  src/compat/compat.h
  src/copy.c
  src/import/ht_hypertable_modify.c
  src/nodes/hypertable_modify.c
  tsl/src/compression/compression.c
Labels: pg16

#5947 Revert "PG16: Use new function to check vacuum permission"
  src/process_utility.c
Labels: pg16

#5945 Release 2.11.2
  .unreleased/PR_5906
  .unreleased/PR_5923
  .unreleased/bugfix_5774
  .unreleased/bugfix_5786
  .unreleased/bugfix_5907
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.11.1--2.11.2.sql
  version.config
Labels: release

#5870 Improved parallel DecompressChunk worker selection
  src/import/allpaths.c
  src/import/allpaths.h
  test/sql/updates/post.compression.sql
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/test/expected/compression.out
  tsl/test/sql/compression.sql
Labels: compression

#5943 PG16: vacuum_set_xid_limits is now vacuum_get_cutoffs
  src/compat/compat.h
Labels: pg16

#5562 Move trigger functions to _timescaledb_functions schema
  .unreleased/bugfix_5562
  sql/cagg_utils.sql
  sql/hypertable.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  src/hypertable.c
  test/expected/create_hypertable.out
  test/expected/pg_dump.out
  test/expected/rowsecurity-13.out
  test/expected/rowsecurity-14.out
  test/expected/rowsecurity-15.out
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/invalidation.c
  tsl/test/expected/cagg_ddl.out
  tsl/test/expected/cagg_ddl_dist_ht.out
  tsl/test/expected/cagg_watermark.out
  tsl/test/expected/compression_ddl.out
  tsl/test/expected/continuous_aggs_deprecated-13.out
  tsl/test/expected/continuous_aggs_deprecated-14.out
  tsl/test/expected/continuous_aggs_deprecated-15.out
  tsl/test/expected/dist_ddl.out
  tsl/test/expected/dist_hypertable-13.out
  tsl/test/expected/dist_hypertable-14.out
  tsl/test/expected/dist_hypertable-15.out
  tsl/test/expected/dist_triggers.out
  tsl/test/shared/expected/extension.out
  tsl/test/sql/cagg_watermark.sql
Labels: security

#5973 Move get_create_command into _timescaledb_functions schema
  scripts/ts_dump.sh
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  sql/util_internal_table_ddl.sql
  test/expected/create_hypertable.out
  test/sql/create_hypertable.sql
  tsl/test/shared/expected/extension.out
Labels: security

#5990 Place data in first/last function in correct mctx
  .unreleased/bugfix_5990
  src/agg_bookend.c
  test/expected/agg_bookends.out
  test/sql/agg_bookends.sql
Labels: bug

#5992 Move dist_internal functions to _timescaledb_functions schema
  sql/data_node.sql
  sql/dist_internal.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  tsl/src/data_node.c
  tsl/src/remote/connection.c
  tsl/test/expected/data_node.out
  tsl/test/expected/dist_commands.out
  tsl/test/expected/remote_connection_cache.out
  tsl/test/expected/remote_txn.out
  tsl/test/expected/remote_txn_resolve.out
  tsl/test/shared/expected/dist_queries.out
  tsl/test/shared/expected/extension.out
  tsl/test/shared/sql/dist_queries.sql
  tsl/test/sql/data_node.sql
  tsl/test/sql/dist_commands.sql
  tsl/test/sql/remote_connection_cache.sql
  tsl/test/sql/remote_txn.sql
  tsl/test/sql/remote_txn_resolve.sql
  tsl/test/src/remote/txn_resolve.c
  tsl/test/t/003_connections_privs.pl
Labels: security

#5993 Backport to 2.11.x: #5990: Place data in first/last function in correct mctx
  .unreleased/bugfix_5990
  src/agg_bookend.c
  test/expected/agg_bookends-12.out
  test/expected/agg_bookends-13.out
  test/expected/agg_bookends-14.out
  test/expected/agg_bookends-15.out
  test/sql/agg_bookends.sql.in
Labels: is-auto-backport

#5991 Call eq_func correctly in time_bucket_gapfill
  .unreleased/bugfix_5991
  tsl/src/nodes/gapfill/gapfill_exec.c
  tsl/test/shared/expected/gapfill.out
  tsl/test/shared/sql/gapfill.sql
Labels: bug

#5995 Move size_util functions to _timescaledb_functions schema
  scripts/dump_meta_data.sql
  sql/size_utils.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  test/expected/dump_meta.out
  test/expected/size_utils.out
  test/sql/size_utils.sql
  tsl/src/dist_util.c
  tsl/test/expected/dist_util.out
  tsl/test/shared/expected/extension.out
  tsl/test/sql/dist_util.sql
Labels: security

#5997 Move utility functions to _timescaledb_functions schema
  sql/metadata.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  sql/version.sql
  test/expected/license.out
  test/expected/version.out
  test/sql/license.sql
  test/sql/utils/testsupport.sql
  test/sql/version.sql
  tsl/test/expected/license_tsl.out
  tsl/test/shared/expected/build_info.out
  tsl/test/shared/expected/extension.out
  tsl/test/shared/sql/build_info.sql
  tsl/test/sql/license_tsl.sql
Labels: security

#6003 Exclude PRs from bugs project board
  .github/workflows/procedural.yaml
Labels: ci

#5809 Relax strong table lock when refreshing a Continuous Aggregate
  .unreleased/feature_5809
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/invalidation_threshold.c
  tsl/src/continuous_aggs/invalidation_threshold.h
  tsl/src/continuous_aggs/refresh.c
  tsl/test/expected/cagg_invalidation.out
  tsl/test/expected/cagg_invalidation_dist_ht-13.out
  tsl/test/expected/cagg_invalidation_dist_ht-14.out
  tsl/test/expected/cagg_invalidation_dist_ht-15.out
  tsl/test/expected/cagg_watermark.out
  tsl/test/expected/exp_cagg_monthly.out
  tsl/test/expected/exp_cagg_timezone.out
  tsl/test/isolation/expected/cagg_concurrent_refresh.out
  tsl/test/isolation/expected/cagg_concurrent_refresh_dist_ht.out
  tsl/test/isolation/expected/cagg_insert.out
  tsl/test/isolation/specs/cagg_concurrent_refresh.spec
  tsl/test/isolation/specs/cagg_insert.spec
  tsl/test/sql/cagg_watermark.sql
  tsl/test/sql/exp_cagg_monthly.sql
  tsl/test/sql/exp_cagg_timezone.sql
  tsl/test/sql/include/cagg_invalidation_common.sql
Labels: continuous_aggregate, locking, enhancement

#5994 Backport to 2.11.x: #5991: Call eq_func correctly in time_bucket_gapfill
  .unreleased/bugfix_5991
  tsl/src/nodes/gapfill/gapfill_exec.c
  tsl/test/shared/expected/gapfill-12.out
  tsl/test/shared/expected/gapfill-13.out
  tsl/test/shared/expected/gapfill-14.out
  tsl/test/shared/expected/gapfill-15.out
  tsl/test/shared/sql/gapfill.sql.in
Labels: is-auto-backport

#5987 PG16: Datum macros are now inline functions
  src/compression_with_clause.c
  src/process_utility.c
  src/ts_catalog/continuous_agg.c
  test/src/telemetry/test_telemetry.c
  test/src/test_with_clause_parser.c
  tsl/test/src/test_compression.c
Labels: pg16

#5560 Move cagg migrate functions into _timescaledb_functions schema
  .github/workflows/pgspot.yaml
  sql/cagg_migrate.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  tsl/test/expected/cagg_migrate.out
  tsl/test/expected/cagg_migrate_dist_ht.out
  tsl/test/shared/expected/extension.out
  tsl/test/sql/include/cagg_migrate_common.sql
Labels: continuous_aggregate

#6029 Fix an invalid SPI result use after free
  src/hypertable.c
Labels: bug

#5954 PG16: Fix concurrent update issues with MERGE.
  src/compat/compat.h
  src/import/ht_hypertable_modify.c
  src/import/ht_hypertable_modify.h
  src/nodes/hypertable_modify.c
Labels: pg16

#6033 Backport to 2.11.x: #6015: Fix incorrect row count in EXPLAIN ANALYZE INSERT .. ON CONFLICT output
  .unreleased/bugfix_6015
  src/nodes/hypertable_modify.c
  test/expected/upsert.out
  test/sql/upsert.sql
Labels: is-auto-backport

#6034 Backport to 2.11.x: #6029: Fix an invalid SPI result use after free
  src/hypertable.c
Labels: is-auto-backport
