Repository timescale/timescaledb, pull requests merged in 2023-10, with the labels that each got.

#6138 PG16: adjust tests to use debug_parallel_query
  test/expected/loader-tsl.out
  test/expected/parallel-13.out
  test/expected/parallel-14.out
  test/expected/parallel-15.out
  test/sql/loader.sql.in
  test/sql/parallel.sql.in
  tsl/test/expected/agg_partials_pushdown.out
  tsl/test/expected/continuous_aggs-13.out
  tsl/test/expected/continuous_aggs-14.out
  tsl/test/expected/continuous_aggs-15.out
  tsl/test/expected/partialize_finalize.out
  tsl/test/expected/plan_skip_scan-13.out
  tsl/test/expected/plan_skip_scan-14.out
  tsl/test/expected/plan_skip_scan-15.out
  tsl/test/expected/skip_scan.out
  tsl/test/sql/agg_partials_pushdown.sql
  tsl/test/sql/continuous_aggs.sql.in
  tsl/test/sql/include/skip_scan_query.sql
  tsl/test/sql/partialize_finalize.sql
  tsl/test/t/008_mvcc_cagg.pl
Labels: pg16

#6151 Backport to 2.12.x: #6142: Do not throw an error on missing GUC value
  .unreleased/pr_6142
  sql/compat.sql
Labels: is-auto-backport

#6150 Backport to 2.12.x: #6146: Modify interpolate() call in gapfill test
  tsl/test/shared/expected/gapfill.out
  tsl/test/shared/sql/gapfill.sql
Labels: is-auto-backport

#6149 Backport to 2.12.x: #6117: Avoid decompressing batches using an empty slot
  .unreleased/PR_6117
  tsl/src/compression/compression.c
  tsl/test/expected/compression_insert.out
  tsl/test/sql/compression_insert.sql
  tsl/test/sql/data/copy_data.csv
Labels: is-auto-backport

#6153 PG16 Fix transparent decompression
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
Labels: pg16

#6160 Improve arg handling in continuous_agg_trigfn
  tsl/src/continuous_aggs/insert.c
  tsl/test/expected/cagg_usage.out
  tsl/test/sql/cagg_usage.sql
Labels: bug

#6162 Backport to 2.12.x: #6160: Improve arg handling in continuous_agg_trigfn
  tsl/src/continuous_aggs/insert.c
  tsl/test/expected/cagg_usage.out
  tsl/test/sql/cagg_usage.sql
Labels: is-auto-backport

#6163 Fix cagg trigger on compat schema layer
  sql/compat.sql
  tsl/test/shared/expected/compat.out
  tsl/test/shared/sql/compat.sql
Labels: bug

#6166 Reduce loops in scheduled sqlsmith runs
  .github/workflows/sqlsmith.yaml
Labels: ci

#6167 Backport to 2.12.x: #6163: Fix cagg trigger on compat schema layer
  sql/compat.sql
  tsl/test/shared/expected/compat.out
  tsl/test/shared/sql/compat.sql
Labels: is-auto-backport

#6168 PG16: Reset PlannerInfo->placeholdersFrozen
  src/planner/agg_bookend.c
  tsl/test/shared/expected/ordered_append-16.out
Labels: pg16

#6164 Handle non existing ht in cache_inval_entry_init
  tsl/src/continuous_aggs/insert.c
  tsl/test/expected/cagg_usage.out
  tsl/test/sql/cagg_usage.sql
Labels: bug

#6173 Backport to 2.12.x: #6164: Handle non existing ht in cache_inval_entry_init
  tsl/src/continuous_aggs/insert.c
  tsl/test/expected/cagg_usage.out
  tsl/test/sql/cagg_usage.sql
Labels: is-auto-backport

#6172 Make agg_partials_pushdown test more predictable
  tsl/test/expected/agg_partials_pushdown.out
  tsl/test/sql/agg_partials_pushdown.sql
Labels: testing, flaky-test, ci

#6180 PG16: Fix regression tests
  tsl/test/expected/cagg_ddl_dist_ht-16.out
  tsl/test/expected/cagg_usage-16.out
  tsl/test/expected/dist_param.out
Labels: testing, pg16

#6181 Ensure fixed_schedule field is populated
  src/bgw/job.c
Labels: bug

#6192 Backport to 2.12.x: #6181: Ensure fixed_schedule field is populated
  src/bgw/job.c
Labels: is-auto-backport

#6191 Add CI check for unecessary template tests
  .github/workflows/code_style.yaml
  scripts/check_unecessary_template_tests.sh
Labels: ci, enhancement

#6178 Show batches/tuples decompressed during DML operations in EXPLAIN output
  .unreleased/pr_6178
  src/cross_module_fn.h
  src/nodes/chunk_dispatch/chunk_dispatch.h
  src/nodes/chunk_dispatch/chunk_insert_state.c
  src/nodes/chunk_dispatch/chunk_insert_state.h
  src/nodes/hypertable_modify.c
  src/nodes/hypertable_modify.h
  tsl/src/compression/compression.c
  tsl/src/compression/compression.h
  tsl/test/shared/expected/decompress_tracking.out
  tsl/test/shared/sql/CMakeLists.txt
  tsl/test/shared/sql/decompress_tracking.sql
Labels: compression

#6200 Remove canceled bgw jobs from test output
  test/runner.sh
  test/runner_shared.sh
Labels: bug, testing, ci

#6201 Backport to 2.12.x: #6200: Remove canceled bgw jobs from test output
  test/runner.sh
  test/runner_shared.sh
Labels: is-auto-backport

#6188 Add GUC for setting background worker log level
  .unreleased/fix_6188
  src/bgw/job.c
  src/bgw/scheduler.c
  src/guc.c
  src/guc.h
  test/src/bgw/log.c
  tsl/test/expected/bgw_db_scheduler.out
  tsl/test/expected/bgw_db_scheduler_fixed.out
  tsl/test/expected/bgw_reorder_drop_chunks.out
  tsl/test/expected/bgw_scheduler_control.out
  tsl/test/expected/cagg_bgw-13.out
  tsl/test/expected/cagg_bgw-14.out
  tsl/test/expected/cagg_bgw-15.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/bgw_db_scheduler.sql
  tsl/test/sql/bgw_scheduler_control.sql
Labels: bug

#6206 Fix uninitialized variable ts_guc_bgw_log_level
  src/guc.c
Labels: bug, disable-auto-backport

#6207 PG16: Fix ts_bgw_log_level bootval
  src/guc.c
Labels: pg16

#6155 Align gapfill bucket generation with time_bucket
  .unreleased/PR_6155
  tsl/src/nodes/gapfill/gapfill_exec.c
  tsl/src/nodes/gapfill/gapfill_internal.h
  tsl/test/shared/expected/gapfill-13.out
  tsl/test/shared/expected/gapfill-14.out
  tsl/test/shared/expected/gapfill-15.out
  tsl/test/shared/expected/gapfill-16.out
  tsl/test/shared/sql/gapfill.sql.in
Labels: bug

#6195 Restart scheduler on error
  .unreleased/feature_6195
  src/bgw/scheduler.c
  src/guc.c
  src/guc.h
  src/loader/bgw_launcher.c
  src/loader/bgw_launcher.h
  src/loader/loader.c
  tsl/test/expected/bgw_scheduler_restart.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/bgw_scheduler_restart.sql
Labels: bug

#6226 PG16: Fix JOIN behaviour
  src/planner/planner.c
  test/sql/include/join_query.sql
Labels: pg16

#6228 PG16: Removed ignore feature from pg_regress
  test/pg_regress.sh
Labels: pg16

#6230 Adjust relation size in MN test results
  tsl/test/expected/dist_compression-13.out
  tsl/test/expected/dist_compression-14.out
  tsl/test/expected/dist_compression-15.out
  tsl/test/expected/dist_move_chunk-13.out
  tsl/test/expected/dist_move_chunk-14.out
  tsl/test/expected/dist_move_chunk-15.out
  tsl/test/expected/dist_views-13.out
  tsl/test/expected/dist_views-14.out
  tsl/test/expected/dist_views-15.out
  tsl/test/sql/.gitignore
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/dist_compression.sql.in
  tsl/test/sql/dist_move_chunk.sql.in
  tsl/test/sql/dist_views.sql.in
Labels: ci

#6232 Backport to 2.12.x: #6231: Fix flaky upgrade test
  test/sql/updates/post.continuous_aggs.sql
  test/sql/updates/post.continuous_aggs.v3.sql
  test/sql/updates/setup.catalog.sql
  test/sql/updates/setup.continuous_aggs.sql
  test/sql/updates/setup.continuous_aggs.v2.sql
Labels: is-auto-backport

#6234 Use "dylib" uniformly on MacOSX
  src/build-defs.cmake
  tsl/src/build-defs.cmake
Labels: pg16

#6236 PG16: Handle new vacuum option ONLY_DATABASE_STATS
  src/process_utility.c
Labels: pg16

#6242 PG16: Refactored ownercheck functions
  src/process_utility.c
Labels: pg16

#6245 PG16: Fix ordered append output test
  tsl/test/shared/expected/ordered_append-16.out
Labels: pg16

#6249 Adjust dist_util test output
  tsl/test/expected/dist_util-13.out
  tsl/test/expected/dist_util-14.out
  tsl/test/expected/dist_util-15.out
  tsl/test/expected/dist_util-16.out
  tsl/test/sql/.gitignore
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/dist_util.sql.in
Labels: ci
