Repository timescale/timescaledb, pull requests merged in 2023-04, with the labels that each got.

#5417 Refactor and optimize distributed COPY
  CHANGELOG.md
  tsl/src/fdw/option.c
  tsl/src/nodes/data_node_copy.c
  tsl/src/remote/CMakeLists.txt
  tsl/src/remote/connection.c
  tsl/src/remote/connection.h
  tsl/src/remote/dist_copy.c
  tsl/src/remote/dist_copy.h
  tsl/test/expected/dist_copy_format_long.out
  tsl/test/expected/dist_remote_error-14.out
  tsl/test/expected/dist_remote_error-15.out
  tsl/test/expected/remote_copy-12.out
  tsl/test/expected/remote_copy-13.out
  tsl/test/expected/remote_copy-14.out
  tsl/test/expected/remote_copy-15.out
  tsl/test/sql/dist_copy_format_long.sql
  tsl/test/sql/remote_copy.sql.in
Labels: multinode, tech-debt

#5339 Support UPDATE/DELETE on compressed hypertables.
  CHANGELOG.md
  src/cross_module_fn.h
  src/nodes/hypertable_modify.c
  src/nodes/hypertable_modify.h
  tsl/src/compression/compression.c
  tsl/src/compression/compression.h
  tsl/src/init.c
  tsl/src/planner.c
  tsl/test/expected/chunk_utils_internal.out
  tsl/test/expected/compression.out
  tsl/test/expected/compression_permissions.out
  tsl/test/expected/compression_update_delete.out
  tsl/test/expected/continuous_aggs-12.out
  tsl/test/expected/continuous_aggs-13.out
  tsl/test/expected/continuous_aggs-14.out
  tsl/test/expected/continuous_aggs-15.out
  tsl/test/expected/continuous_aggs_deprecated.out
  tsl/test/isolation/expected/compression_dml_iso.out
  tsl/test/isolation/specs/CMakeLists.txt
  tsl/test/isolation/specs/compression_dml_iso.spec
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/compression.sql
  tsl/test/sql/compression_update_delete.sql
  tsl/test/sql/continuous_aggs.sql.in
  tsl/test/sql/continuous_aggs_deprecated.sql
Labels: compression, core, enhancement, Team: Core Database

#5524 Remove unused function
  tsl/src/continuous_aggs/invalidation_threshold.c
  tsl/src/continuous_aggs/invalidation_threshold.h
Labels: tech-debt

#5462 Fix segfault after column drop on compressed table
  CHANGELOG.md
  tsl/src/nodes/decompress_chunk/exec.c
  tsl/test/expected/compression_errors.out
  tsl/test/sql/compression_errors.sql
Labels: compression, segfault

#5540 Silence WARNING after extension update
  sql/updates/post-update.sql
Labels: continuous_aggregate, tech-debt

#5533 Fix chunk status when inserting into chunks
  src/nodes/chunk_dispatch/chunk_dispatch.c
  src/nodes/chunk_dispatch/chunk_insert_state.c
  src/nodes/chunk_dispatch/chunk_insert_state.h
  tsl/src/compression/compression.c
  tsl/test/isolation/expected/compression_conflicts_iso.out
  tsl/test/isolation/expected/compression_ddl_iso.out
  tsl/test/isolation/specs/CMakeLists.txt
  tsl/test/isolation/specs/compression_conflicts_iso.spec
Labels: compression

#5544 Fix timestamp out of range refreshing CAgg
  CHANGELOG.md
  src/time_utils.c
  src/time_utils.h
  tsl/src/continuous_aggs/refresh.c
  tsl/test/expected/cagg_ddl.out
  tsl/test/expected/cagg_ddl_dist_ht.out
  tsl/test/sql/include/cagg_ddl_common.sql
Labels: bug, continuous_aggregate

#5556 Fix timescaledb_experimental.policies duplicates
  CHANGELOG.md
  sql/views_experimental.sql
  tsl/test/expected/cagg_policy.out
  tsl/test/sql/cagg_policy.sql
Labels: bug, experimental-schema

#5510 Propagate vacuum/analyze to compressed chunks
  CHANGELOG.md
  src/process_utility.c
  tsl/test/expected/compression.out
  tsl/test/sql/compression.sql
Labels: compression

#5552 Windows debug build failure
  CMakeLists.txt
Labels: ci, force-auto-backport

#5563 Backport to 2.10.x: #5552: Windows debug build failure
  CMakeLists.txt
Labels: is-auto-backport

#5559 Backport to 2.10.x: #5556: Fix timescaledb_experimental.policies duplicates
  sql/views_experimental.sql
  tsl/test/expected/cagg_policy.out
  tsl/test/sql/cagg_policy.sql
Labels: is-auto-backport

#5564 Force dist_move_chunk as solo test for PG15.2
  tsl/test/sql/CMakeLists.txt
Labels: force-auto-backport

#5566 Backport to 2.10.x: #5564: Force dist_move_chunk as solo test for PG15.2
  tsl/test/sql/CMakeLists.txt
Labels: is-auto-backport

#5568 Backport to 2.10.x: #5519: Disallow MergeAppend optimizations when there is an OSM chunk
  src/planner/planner.c
Labels: is-auto-backport

#5571 Backport to 2.10.x: #5543: Copy scheduled_jobs list before sorting it
  CHANGELOG.md
  src/bgw/scheduler.c
  tsl/test/expected/bgw_custom.out
  tsl/test/sql/bgw_custom.sql
Labels: is-auto-backport

#5523 Add CI check for missing gitignore entries
  .github/workflows/code_style.yaml
  scripts/check_missing_gitignore_for_template_tests.sh
  test/sql/.gitignore
Labels: ci, tech-debt

#5580 Fix post repair tests
  test/sql/updates/post.repair.sql
Labels: bug, ci

#5581 Backport to 2.10.x: #5580: Fix post repair tests
  test/sql/updates/post.repair.sql
Labels: is-auto-backport

#5558 Use regrole for job owner
  CHANGELOG.md
  sql/job_error_log_retention.sql
  sql/pre_install/tables.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  sql/with_telemetry.sql
  src/bgw/job.c
  src/bgw/job.h
  src/bgw/scheduler.c
  src/process_utility.c
  src/ts_catalog/catalog.h
  test/expected/telemetry.out
  tsl/src/bgw_policy/compression_api.c
  tsl/src/bgw_policy/continuous_aggregate_api.c
  tsl/src/bgw_policy/job_api.c
  tsl/src/bgw_policy/reorder_api.c
  tsl/src/bgw_policy/retention_api.c
  tsl/test/expected/bgw_custom.out
  tsl/test/expected/bgw_db_scheduler.out
  tsl/test/expected/bgw_db_scheduler_fixed.out
  tsl/test/sql/bgw_custom.sql
  tsl/test/sql/bgw_db_scheduler.sql
  tsl/test/sql/bgw_db_scheduler_fixed.sql
Labels: bug, bgw

#5584 Reduce decompression during constraint checking
  CHANGELOG.md
  tsl/src/compression/compression.c
  tsl/test/expected/compression_conflicts.out
  tsl/test/sql/compression_conflicts.sql
Labels: compression

#5594 Block unique idx creation on compressed hypertable
  src/process_utility.c
  tsl/test/expected/compression_ddl.out
  tsl/test/sql/compression_ddl.sql
Labels: compression

#5597 Bump version to 2.10.3-dev after release
  sql/CMakeLists.txt
  version.config
Labels: release

#5593 Refactor compression code to reduce duplication
  tsl/src/compression/compression.c
  tsl/src/compression/compression.h
Labels: compression, tech-debt

#5598 Backport to 2.10.x: #5583: Fix parameterization in DecompressChunk path generation
  CHANGELOG.md
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/test/shared/expected/decompress_join-12.out
  tsl/test/shared/expected/decompress_join-13.out
  tsl/test/shared/expected/decompress_join-14.out
  tsl/test/shared/expected/decompress_join-15.out
  tsl/test/shared/sql/decompress_join.sql.in
Labels: is-auto-backport

#5604 Reduce decompression during UPDATE/DELETE
  tsl/src/compression/compression.c
  tsl/src/compression/compression.h
  tsl/test/expected/compression_update_delete.out
  tsl/test/sql/compression_update_delete.sql
Labels: compression

#5602 Fix broken CAgg with JOIN repair function
  CHANGELOG.md
  tsl/src/continuous_aggs/create.c
  tsl/test/expected/cagg_repair.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/cagg_repair.sql
Labels: bug

#5616 Backport to 2.10.x: #5602: Fix broken CAgg with JOIN repair function
  CHANGELOG.md
  tsl/src/continuous_aggs/create.c
  tsl/test/expected/cagg_repair.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/cagg_repair.sql
Labels: is-auto-backport

#5619 Fix cagg_repair for the old CAgg format
  tsl/src/continuous_aggs/create.c
  tsl/test/expected/cagg_repair.out
  tsl/test/sql/cagg_repair.sql
Labels: bug, continuous_aggregate

#5622 Backport to 2.10.x: #5619: Fix cagg_repair for the old CAgg format
  tsl/src/continuous_aggs/create.c
  tsl/test/expected/cagg_repair.out
  tsl/test/sql/cagg_repair.sql
Labels: is-auto-backport

#5621 Fix CI ignored regression workflows
  .github/workflows/linux-build-and-test-ignored.yaml
Labels: ci

#5618 Release 2.10.3
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.10.2--2.10.3.sql
  sql/updates/2.10.3--2.10.2.sql
Labels: release

#5623 Add missing matrix in ignored regression workflow
  .github/workflows/linux-build-and-test-ignored.yaml
Labels: ci

#5625 Add missing matrix in ignored 32bits regression workflow
  .github/workflows/linux-32bit-build-and-test-ignored.yaml
Labels: ci

#5617 Changelog for 2.10.3
  CHANGELOG.md
Labels: release

#5626 Bump version to 2.10.4 after release
  sql/CMakeLists.txt
  version.config
Labels: release

#5627 Post-release 2.10.3
  scripts/test_updates_pg12.sh
  scripts/test_updates_pg13.sh
  scripts/test_updates_pg14.sh
  scripts/test_updates_pg15.sh
  sql/CMakeLists.txt
  sql/updates/2.10.2--2.10.3.sql
  sql/updates/2.10.3--2.10.2.sql
  version.config
Labels: release
