Repository timescale/timescaledb, pull requests merged in 2023-07, with the labels that each got.

#5868 Allow Replica Identity (Alter Table) on CAGGs
  .unreleased/PR_5868
  src/process_utility.c
Labels: continuous_aggregate, enhancement

#5872 Fix duplicates on partially compressed chunk reads
  .unreleased/bugfix_5872
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/test/expected/compression.out
  tsl/test/sql/compression.sql
Labels: compression, force-auto-backport

#5893 Fix broken CI after PG12 removal
  .github/gh_matrix_builder.py
Labels: pg12
