Repository timescale/timescaledb, pull requests merged in 2023-12, with the labels that each got.

#6377 Use processed group clauses in PG16
  .unreleased/fix_6377
  src/planner/partialize.c
  test/expected/partitionwise-13.out
  test/expected/partitionwise-14.out
  test/expected/partitionwise-15.out
  test/expected/partitionwise-16.out
  test/sql/.gitignore
  test/sql/CMakeLists.txt
  test/sql/partitionwise.sql.in
  tsl/test/expected/merge_append_partially_compressed-16.out
Labels: bug

#6378 Backport to 2.13.x: #6377: Use processed group clauses in PG16
  .unreleased/fix_6377
  src/planner/partialize.c
  test/expected/partitionwise-13.out
  test/expected/partitionwise-14.out
  test/expected/partitionwise-15.out
  test/expected/partitionwise-16.out
  test/sql/.gitignore
  test/sql/CMakeLists.txt
  test/sql/partitionwise.sql.in
  tsl/test/expected/merge_append_partially_compressed-16.out
Labels: is-auto-backport

#6393 Disable vectorized sum for expressions
  .unreleased/fix_6393
  tsl/src/partialize_agg.c
  tsl/test/expected/vectorized_aggregation.out
  tsl/test/sql/vectorized_aggregation.sql
Labels: bug

#6395 Use NameStr() macro for NameData struct usage
  src/bgw/job.c
  src/chunk.c
  src/chunk_adaptive.c
  src/compression_with_clause.c
  src/hypertable.c
  src/hypertable_cache.c
  tsl/src/bgw_policy/job.c
  tsl/src/chunk_api.c
  tsl/src/chunk_copy.c
  tsl/src/compression/api.c
  tsl/src/compression/compression.c
  tsl/src/deparse.c
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/src/nodes/decompress_chunk/qual_pushdown.c
  tsl/src/remote/connection_cache.c
Labels: tech-debt

#6404 Use table scan API in compression code
  tsl/src/compression/api.c
  tsl/src/compression/compression.c
Labels: compression

#6409 Remove multinode cagg regression tests
  tsl/test/expected/cagg_bgw-13.out
  tsl/test/expected/cagg_bgw-14.out
  tsl/test/expected/cagg_bgw-15.out
  tsl/test/expected/cagg_bgw-16.out
  tsl/test/expected/cagg_ddl-13.out
  tsl/test/expected/cagg_ddl-14.out
  tsl/test/expected/cagg_ddl-15.out
  tsl/test/expected/cagg_ddl-16.out
  tsl/test/expected/cagg_invalidation.out
  tsl/test/expected/cagg_on_cagg.out
  tsl/test/expected/cagg_on_cagg_joins.out
  tsl/test/sql/.gitignore
  tsl/test/sql/cagg_bgw.sql.in
  tsl/test/sql/cagg_ddl.sql.in
  tsl/test/sql/cagg_invalidation.sql
  tsl/test/sql/cagg_on_cagg.sql
  tsl/test/sql/cagg_on_cagg_joins.sql
  tsl/test/sql/include/cagg_bgw_common.sql
  tsl/test/sql/include/cagg_ddl_common.sql
  tsl/test/sql/include/cagg_invalidation_common.sql
  tsl/test/sql/include/cagg_on_cagg_setup.sql
Labels: multinode, continuous_aggregate

#6408 Fix groupby pathkeys for gapfill in PG16
  .unreleased/fix_6408
  tsl/src/nodes/gapfill/gapfill_plan.c
  tsl/test/shared/expected/gapfill-13.out
  tsl/test/shared/expected/gapfill-14.out
  tsl/test/shared/expected/gapfill-15.out
  tsl/test/shared/expected/gapfill-16.out
  tsl/test/shared/sql/gapfill.sql.in
Labels: bug, gapfill

#6360 Remove support for creating Continuous Aggregates with old format
  .unreleased/pr_6360
  scripts/test_functions.inc
  scripts/test_updates_pg13.sh
  scripts/test_updates_pg14.sh
  scripts/test_updates_pg15.sh
  scripts/test_updates_pg16.sh
  sql/updates/post-update.sql
  test/sql/updates/post.repair.sql
  test/sql/updates/setup.continuous_aggs.sql
  test/sql/updates/setup.continuous_aggs.v2.sql
  test/sql/updates/setup.policies.sql
  test/sql/updates/setup.post-downgrade.sql
  test/sql/updates/setup.repair.cagg.sql
  test/sql/updates/setup.repair.sql
  tsl/src/continuous_aggs/common.c
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/finalize.c
  tsl/src/continuous_aggs/finalize.h
  tsl/src/continuous_aggs/repair.c
  tsl/test/expected/cagg_errors_deprecated-13.out
  tsl/test/expected/cagg_errors_deprecated-14.out
  tsl/test/expected/cagg_errors_deprecated-15.out
  tsl/test/expected/cagg_errors_deprecated-16.out
  tsl/test/expected/cagg_joins.out
  tsl/test/expected/cagg_migrate.out
  tsl/test/expected/cagg_repair-13.out
  tsl/test/expected/cagg_repair-14.out
  tsl/test/expected/cagg_repair-15.out
  tsl/test/expected/cagg_repair-16.out
  tsl/test/expected/continuous_aggs-13.out
  tsl/test/expected/continuous_aggs-14.out
  tsl/test/expected/continuous_aggs-15.out
  tsl/test/expected/continuous_aggs-16.out
  tsl/test/expected/telemetry_stats-13.out
  tsl/test/expected/telemetry_stats-14.out
  tsl/test/expected/telemetry_stats-15.out
  tsl/test/expected/telemetry_stats-16.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/cagg_errors_deprecated.sql.in
  tsl/test/sql/cagg_joins.sql
  tsl/test/sql/cagg_migrate.sql
  tsl/test/sql/cagg_repair.sql.in
  tsl/test/sql/continuous_aggs.sql.in
  tsl/test/sql/continuous_aggs_deprecated.sql.in
  tsl/test/sql/include/cagg_migrate_common.sql
  tsl/test/sql/include/data/cagg_migrate_integer.sql.gz
  tsl/test/sql/include/data/cagg_migrate_timestamp.sql.gz
  tsl/test/sql/include/data/cagg_migrate_timestamptz.sql.gz
  tsl/test/sql/telemetry_stats.sql.in
Labels: continuous_aggregate

#6431 Remove useless AggPartCxt data structure
  tsl/src/continuous_aggs/common.h
  tsl/src/continuous_aggs/finalize.c
Labels: continuous_aggregate, tech-debt

#6418 Backport to 2.13.x: #6408: Fix groupby pathkeys for gapfill in PG16
  .unreleased/fix_6408
  tsl/src/nodes/gapfill/gapfill_plan.c
  tsl/test/shared/expected/gapfill-13.out
  tsl/test/shared/expected/gapfill-14.out
  tsl/test/shared/expected/gapfill-15.out
  tsl/test/shared/expected/gapfill-16.out
  tsl/test/shared/sql/gapfill.sql.in
Labels: is-auto-backport

#6428 Fix index matching during DML decompression
  .unreleased/fix_6428
  tsl/src/compression/compression.c
  tsl/src/compression/compression.h
  tsl/test/expected/compression_update_delete.out
  tsl/test/sql/compression_update_delete.sql
Labels: bug, compression

#6441 Backport to 2.13.x: #6439: Fix permission handling for compressed chunks on PG16
  .unreleased/pr_6439
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/test/shared/expected/security_barrier.out
  tsl/test/shared/sql/CMakeLists.txt
  tsl/test/shared/sql/security_barrier.sql
Labels: is-auto-backport

#6445 Fix flaky SQL test
  test/expected/bgw_launcher.out
  test/expected/pg_dump.out
  test/sql/bgw_launcher.sql
  test/sql/pg_dump.sql
Labels: ci

#6447 Fix pg_dump flakiness
  test/expected/pg_dump.out
  test/sql/pg_dump.sql
Labels: ci

#6449 Fix upload test results for macos regression CI
  .github/workflows/linux-build-and-test.yaml
Labels: ci

#6405 Read watermark from materialized data
  tsl/src/continuous_aggs/materialize.c
  tsl/test/expected/cagg_refresh.out
Labels: bug, performance, continuous_aggregate

#6453 Disallow database connection in pg_dump
  test/expected/pg_dump.out
  test/sql/pg_dump.sql
Labels: ci

#6451 Fix coverity scan logically dead code
  tsl/src/continuous_aggs/repair.c
Labels: bug, continuous_aggregate, tech-debt

#6464 Fix telemetry test flakiness
  test/src/telemetry/test_telemetry.c
Labels: ci

#6465 Fix use of freed path in decompression sort logic
  .unreleased/fix_6465
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/test/expected/transparent_decompression_queries.out
  tsl/test/shared/expected/transparent_decompress_chunk-16.out
  tsl/test/sql/transparent_decompression_queries.sql
Labels: bug

#6470 Use OpenSSL 3.1.4 for OS X builds
  .github/gh_matrix_builder.py
  .github/workflows/linux-build-and-test.yaml
Labels: ci, force-auto-backport

#6468 Improve core dump handling on OS X
  .github/workflows/linux-build-and-test.yaml
Labels: ci

#6457 Backport to 2.13.x: #6405: Read watermark from materialized data
  tsl/src/continuous_aggs/materialize.c
  tsl/test/expected/cagg_refresh.out
Labels: is-auto-backport

#6455 Backport to 2.13.x: #6454: Fix unique index detection for compressed chunks
  .unreleased/pr_6454
  src/indexing.c
  tsl/test/shared/expected/compress_unique_index.out
  tsl/test/shared/sql/CMakeLists.txt
  tsl/test/shared/sql/compress_unique_index.sql
Labels: is-auto-backport
