Repository timescale/timescaledb, pull requests merged in 2023-03, with the labels that each got.

#5370 Backport to 2.10.x: #5364: Fix for inconsistent num_chunks
  CHANGELOG.md
  sql/views.sql
  tsl/test/expected/information_view_chunk_count.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/information_view_chunk_count.sql
Labels: is-auto-backport

#5374 Backport to 2.10.x: #5336: Use NameData and namestrcpy for names
  CHANGELOG.md
  scripts/test_update_from_tag.sh
  src/partitioning.c
  src/partitioning.h
  src/ts_catalog/catalog.c
  src/ts_catalog/catalog.h
Labels: is-auto-backport

#5371 Backport to 2.10.x: #5360: Fix uninitialized bucket_info variable
  tsl/src/continuous_aggs/create.c
Labels: is-auto-backport

#5362 Make copy fetcher more async
  CHANGELOG.md
  tsl/src/remote/copy_fetcher.c
Labels: multinode

#5373 Backport to 2.10.x: #5343: Set PortalContext when starting job
  CHANGELOG.md
  tsl/src/bgw_policy/job.c
Labels: is-auto-backport

#5372 Backport to 2.10.x: #5317: Fix some incorrect memory handling
  src/process_utility.c
  src/ts_catalog/metadata.c
Labels: is-auto-backport

#5391 Backport to 2.10.x: #5367: Rename columns in old-style continuous aggregates
  CHANGELOG.md
  sql/updates/2.4.1--2.4.2.sql
  test/sql/updates/setup.continuous_aggs.v2.sql
Labels: is-auto-backport

#5384 Fix Hierarchical CAgg chunk_interval_size
  CHANGELOG.md
  tsl/src/continuous_aggs/create.c
  tsl/test/expected/cagg_on_cagg.out
  tsl/test/expected/cagg_on_cagg_dist_ht.out
  tsl/test/sql/include/cagg_on_cagg_common.sql
Labels: bug, continuous_aggregate

#5392 Backport to 2.10.x: #5384: Fix Hierarchical CAgg chunk_interval_size
  CHANGELOG.md
  tsl/src/continuous_aggs/create.c
  tsl/test/expected/cagg_on_cagg.out
  tsl/test/expected/cagg_on_cagg_dist_ht.out
  tsl/test/sql/include/cagg_on_cagg_common.sql
Labels: is-auto-backport

#5401 Remove unused functions
  src/ts_catalog/catalog.c
  src/ts_catalog/catalog.h
Labels: core, tech-debt, Team: Core Database

#5304 Fix sub-second intervals in hierarchical caggs
  CHANGELOG.md
  tsl/src/continuous_aggs/create.c
  tsl/test/expected/cagg_on_cagg.out
  tsl/test/expected/cagg_on_cagg_dist_ht.out
  tsl/test/sql/cagg_on_cagg.sql
  tsl/test/sql/cagg_on_cagg_dist_ht.sql
Labels: bug, continuous_aggregate

#5408 Backport to 2.10.x: #5304: Fix sub-second intervals in hierarchical caggs
  CHANGELOG.md
  tsl/src/continuous_aggs/create.c
  tsl/test/expected/cagg_on_cagg.out
  tsl/test/expected/cagg_on_cagg_dist_ht.out
  tsl/test/sql/cagg_on_cagg.sql
  tsl/test/sql/cagg_on_cagg_dist_ht.sql
Labels: is-auto-backport

#5361 Add parallel support for partialize_agg()
  CHANGELOG.md
  sql/partialize_finalize.sql
  src/planner/expand_hypertable.c
  src/planner/partialize.c
  src/planner/planner.c
  src/planner/planner.h
  tsl/test/expected/dist_copy_long.out
  tsl/test/expected/dist_partial_agg-12.out
  tsl/test/expected/dist_partial_agg-13.out
  tsl/test/expected/dist_partial_agg-14.out
  tsl/test/expected/dist_partial_agg-15.out
  tsl/test/expected/partialize_finalize.out
  tsl/test/sql/dist_copy_long.sql
  tsl/test/sql/dist_partial_agg.sql.in
  tsl/test/sql/partialize_finalize.sql
Labels: multinode

#5423 Backport to 2.10.x: #5410: Fix file trailer handling in the copy fetcher
  CHANGELOG.md
  tsl/src/remote/copy_fetcher.c
  tsl/test/expected/data_fetcher.out
  tsl/test/sql/data_fetcher.sql
  tsl/test/sql/include/data_fetcher_run.sql
Labels: is-auto-backport

#5457 Backport to 2.10.x: #5446: Add check for malloc failure in libpq calls
  CHANGELOG.md
  src/utils.h
  tsl/src/remote/connection.c
Labels: is-auto-backport

#5454 Add support for ON CONFLICT DO UPDATE for compressed hypertables.
  CHANGELOG.md
  src/nodes/chunk_dispatch/chunk_dispatch.c
  src/nodes/chunk_dispatch/chunk_insert_state.c
  src/nodes/chunk_dispatch/chunk_insert_state.h
  tsl/test/expected/compression.out
  tsl/test/expected/compression_conflicts.out
  tsl/test/sql/compression.sql
  tsl/test/sql/compression_conflicts.sql
Labels: Team: Core Database

#5465 Add missing gitignore entry
  tsl/test/sql/.gitignore
Labels: tech-debt

#5428 Use consistent snapshots when scanning metadata
  CHANGELOG.md
  src/scanner.c
Labels: bug

#5118 Stats improvement for Uncompressed Chunks
  .github/gh_matrix_builder.py
  .github/workflows/windows-build-and-test.yaml
  CHANGELOG.md
  sql/size_utils.sql
  sql/updates/reverse-dev.sql
  src/cross_module_fn.c
  src/cross_module_fn.h
  src/planner/planner.c
  src/process_utility.c
  tsl/src/compression/api.c
  tsl/src/compression/compression.c
  tsl/src/compression/compression.h
  tsl/src/init.c
  tsl/test/expected/chunk_merge.out
  tsl/test/expected/compression.out
  tsl/test/expected/telemetry_stats-12.out
  tsl/test/expected/telemetry_stats-13.out
  tsl/test/expected/telemetry_stats-14.out
  tsl/test/expected/telemetry_stats-15.out
  tsl/test/expected/transparent_decompression-12.out
  tsl/test/expected/transparent_decompression-13.out
  tsl/test/expected/transparent_decompression-14.out
  tsl/test/expected/transparent_decompression-15.out
  tsl/test/isolation/expected/compression_chunk_race.out
  tsl/test/shared/expected/extension.out
  tsl/test/shared/expected/ordered_append_join-12.out
  tsl/test/shared/expected/ordered_append_join-13.out
  tsl/test/shared/expected/ordered_append_join-14.out
  tsl/test/shared/expected/ordered_append_join-15.out
  tsl/test/shared/expected/transparent_decompress_chunk-12.out
  tsl/test/shared/expected/transparent_decompress_chunk-13.out
  tsl/test/shared/expected/transparent_decompress_chunk-14.out
  tsl/test/shared/expected/transparent_decompress_chunk-15.out
  tsl/test/sql/chunk_merge.sql
  tsl/test/sql/compression.sql
Labels: Query Experience Team

#5261 Improve Realtime Continuous Aggregate performance
  CHANGELOG.md
  sql/pre_install/tables.sql
  sql/updates/latest-dev.sql
  sql/updates/post-update.sql
  sql/updates/reverse-dev.sql
  sql/util_time.sql
  src/chunk.c
  src/hypertable.c
  src/hypertable.h
  src/ts_catalog/CMakeLists.txt
  src/ts_catalog/catalog.c
  src/ts_catalog/catalog.h
  src/ts_catalog/continuous_agg.c
  src/ts_catalog/continuous_aggs_watermark.c
  src/ts_catalog/continuous_aggs_watermark.h
  test/expected/drop_rename_hypertable.out
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/invalidation_threshold.c
  tsl/src/continuous_aggs/materialize.c
  tsl/src/continuous_aggs/materialize.h
  tsl/src/continuous_aggs/refresh.c
  tsl/test/expected/cagg_refresh.out
  tsl/test/expected/cagg_union_view-12.out
  tsl/test/expected/cagg_union_view-13.out
  tsl/test/expected/cagg_union_view-14.out
  tsl/test/expected/cagg_union_view-15.out
  tsl/test/shared/expected/extension.out
  tsl/test/sql/cagg_union_view.sql.in
Labels: performance, continuous_aggregate, core, Team: Core Database

#5321 Rewrite recompress_chunk for segmentwise processing
  sql/maintenance_utils.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  src/chunk.c
  src/chunk.h
  src/cross_module_fn.c
  src/cross_module_fn.h
  src/nodes/chunk_dispatch/chunk_insert_state.c
  tsl/src/compression/api.c
  tsl/src/compression/api.h
  tsl/src/compression/compression.c
  tsl/src/compression/compression.h
  tsl/src/compression/segment_meta.c
  tsl/src/compression/segment_meta.h
  tsl/src/init.c
  tsl/test/expected/compression_bgw.out
  tsl/test/expected/compression_ddl.out
  tsl/test/expected/recompress_chunk_segmentwise.out
  tsl/test/isolation/expected/compression_ddl_iso.out
  tsl/test/isolation/specs/compression_ddl_iso.spec
  tsl/test/shared/expected/extension.out
  tsl/test/shared/expected/transparent_decompress_chunk-13.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/recompress_chunk_segmentwise.sql
Labels: performance, compression, core, enhancement, Team: Core Database

#5430 Backport to 2.10.x: #5403: Out of on_proc_exit slots on guc license change
  CHANGELOG.md
  src/license_guc.c
  tsl/src/init.c
Labels: is-auto-backport

#5469 Backport to 2.10.x: #5428: Use consistent snapshots when scanning metadata
  CHANGELOG.md
  src/scanner.c
Labels: is-auto-backport

#5503 Backport to 2.10.x: #5499: Do not segfault on large histogram() parameters
  .github/workflows/linux-32bit-build-and-test.yaml
  CHANGELOG.md
  src/histogram.c
  test/expected/histogram_test.out
  test/sql/histogram_test.sql
Labels: is-auto-backport

#5493 Backport to 2.10.x: #5470: Ensure superuser perms during copy/move chunk
  CHANGELOG.md
  tsl/src/chunk_copy.c
Labels: is-auto-backport

#5508 Backport to 2.10.x: #5501: Handle when FROM clause is missing in continuous aggregate definition
  CHANGELOG.md
  tsl/src/continuous_aggs/create.c
  tsl/test/expected/cagg_errors.out
  tsl/test/sql/cagg_errors.sql
Labels: is-auto-backport
