Repository timescale/timescaledb, pull requests merged in 2023-05, with the labels that each got.

#5635 Backport to 2.10.x: #5615: Add permission checks to run_job()
  CHANGELOG.md
  src/bgw/job.c
  src/bgw/job.h
  tsl/src/bgw_policy/job_api.c
  tsl/test/expected/bgw_security.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/bgw_security.sql
Labels: is-auto-backport

#5636 Fix CoverityScan deference after null check
  tsl/src/continuous_aggs/create.c
Labels: bug, continuous_aggregate

#5647 Backport to 2.10.x: #5636: Fix CoverityScan deference after null check
  tsl/src/continuous_aggs/create.c
Labels: is-auto-backport

#5659 Backport to 2.10.x: #5642: Fix ALTER TABLE SET with normal tables
  CHANGELOG.md
  src/process_utility.c
  test/expected/reloptions.out
  test/sql/reloptions.sql
Labels: is-auto-backport

#5657 Fix index scan handling in DML decompression
  tsl/src/compression/compression.c
  tsl/test/expected/compression_update_delete.out
  tsl/test/sql/compression_update_delete.sql
Labels: compression

#5653 Add GUC to enable/disable DML decompression
  src/guc.c
  src/guc.h
  src/planner/planner.c
  tsl/src/compression/compression.c
  tsl/src/nodes/compress_dml/compress_dml.c
  tsl/src/planner.c
  tsl/test/expected/compression_conflicts.out
  tsl/test/expected/compression_update_delete.out
  tsl/test/sql/compression_conflicts.sql
  tsl/test/sql/compression_update_delete.sql
Labels: compression, Team: Core Database

#5628 Ignore multinode tests from PR CI runs
  .github/gh_matrix_builder.py
  .github/workflows/linux-32bit-build-and-test.yaml
  .github/workflows/windows-build-and-test.yaml
  test/pg_regress.sh
Labels: testing

#5667 Fix DML decompression issues with bitmap heap scan
  tsl/src/compression/compression.c
  tsl/test/expected/compression_update_delete.out
  tsl/test/sql/compression_update_delete.sql
Labels: compression

#5676 Backport to 2.10.x: #5672: Fixed Coverity Scan Warnings
  src/bgw/job.c
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
Labels: is-auto-backport

#5692 Use environment variables for workflows
  .github/workflows/changelog-check.yaml
  .github/workflows/pr-validation.yaml
  .github/workflows/windows-build-and-test.yaml
Labels: security, ci

#5629 Improve test suite
  tsl/test/expected/cagg_joins-12.out
  tsl/test/expected/cagg_joins-13.out
  tsl/test/expected/cagg_joins-14.out
  tsl/test/expected/cagg_joins-15.out
  tsl/test/sql/cagg_joins.sql.in
Labels: testing, continuous_aggregate

#5716 Introduce utility function ts_get_relation_relid
  src/chunk.c
  src/chunk_scan.c
  src/extension_utils.c
  src/hypertable.c
  src/process_utility.c
  src/ts_catalog/catalog.c
  src/ts_catalog/continuous_agg.c
  src/utils.h
  test/src/bgw/log.c
  test/src/bgw/params.c
  tsl/src/bgw_policy/job.c
  tsl/src/bgw_policy/reorder_api.c
  tsl/src/continuous_aggs/create.c
Labels: core, tech-debt, Team: Core Database

#5150 MERGE support on hypertables
  .unreleased/PR_5150
  CHANGELOG.md
  src/import/ht_hypertable_modify.c
  src/nodes/chunk_dispatch/chunk_dispatch.c
  src/nodes/chunk_dispatch/chunk_dispatch.h
  src/nodes/hypertable_modify.c
  src/partitioning.c
  src/planner/planner.c
  test/expected/merge.out
  test/expected/ts_merge.out
  test/sql/CMakeLists.txt
  test/sql/include/ts_merge_load.sql
  test/sql/include/ts_merge_load_ht.sql
  test/sql/include/ts_merge_query.sql
  test/sql/merge.sql
  test/sql/ts_merge.sql
  tsl/src/planner.c
  tsl/test/expected/dist_ref_table_join-12.out
  tsl/test/expected/dist_ref_table_join-13.out
  tsl/test/expected/dist_ref_table_join-14.out
  tsl/test/expected/dist_ref_table_join-15.out
  tsl/test/expected/merge_compress.out
  tsl/test/shared/expected/merge_dml.out
  tsl/test/shared/sql/CMakeLists.txt
  tsl/test/shared/sql/merge_dml.sql
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/dist_ref_table_join.sql.in
  tsl/test/sql/merge_compress.sql
Labels: core, postgresql, hypertable, pg15, enhancement, Team: Core Database
