Repository timescale/timescaledb, pull requests merged in 2023-06, with the labels that each got.

#5737 Replace heap_endscan to table_endscan
  src/copy.c
  src/hypertable.c
  src/loader/bgw_launcher.c
  test/src/bgw/params.c
  tsl/src/compression/compression.c
Labels: core, tech-debt

#5751 Backport to 2.11.x: #5750: Ensure tlist is present in decompress chunk plan
  .unreleased/bugfix_5750
  src/import/planner.h
  tsl/src/nodes/decompress_chunk/planner.c
  tsl/test/expected/compression_sorted_merge-12.out
  tsl/test/expected/compression_sorted_merge-13.out
  tsl/test/expected/compression_sorted_merge-14.out
  tsl/test/expected/compression_sorted_merge-15.out
  tsl/test/sql/compression_sorted_merge.sql.in
Labels: is-auto-backport

#5754 Fixed handling of NULL values in bookend_sfunc
  .unreleased/bugfix_5754
  src/agg_bookend.c
  test/expected/agg_bookends-12.out
  test/expected/agg_bookends-13.out
  test/expected/agg_bookends-14.out
  test/expected/agg_bookends-15.out
  test/sql/include/agg_bookends_query.sql
Labels: bug, force-auto-backport

#5757 Backport to 2.11.x: #5754: Fixed handling of NULL values in bookend_sfunc
  .unreleased/bugfix_5754
  src/agg_bookend.c
  test/expected/agg_bookends-12.out
  test/expected/agg_bookends-13.out
  test/expected/agg_bookends-14.out
  test/expected/agg_bookends-15.out
  test/sql/include/agg_bookends_query.sql
Labels: is-auto-backport

#5796 Backport to 2.11.x: #5777: Fix broken download links
  README.md
Labels: is-auto-backport

#5804 Mark cagg_watermark function as PARALLEL RESTRICTED
  .unreleased/bugfix_5804
  sql/util_time.sql
  src/ts_catalog/continuous_aggs_watermark.c
  tsl/test/expected/continuous_aggs-12.out
  tsl/test/expected/continuous_aggs-13.out
  tsl/test/expected/continuous_aggs-14.out
  tsl/test/expected/continuous_aggs-15.out
  tsl/test/t/008_mvcc_cagg.pl
  tsl/test/t/CMakeLists.txt
Labels: force-auto-backport

#5816 Backport to 2.11.x: #5813: Fix flaky test bgw_db_scheduler_fixed
  tsl/test/expected/bgw_db_scheduler_fixed.out
  tsl/test/sql/bgw_db_scheduler_fixed.sql
Labels: is-auto-backport

#5814 Backport to 2.11.x: #5804: Mark cagg_watermark function as PARALLEL RESTRICTED
  .unreleased/bugfix_5804
  sql/util_time.sql
  src/ts_catalog/continuous_aggs_watermark.c
  tsl/test/expected/continuous_aggs-12.out
  tsl/test/expected/continuous_aggs-13.out
  tsl/test/expected/continuous_aggs-14.out
  tsl/test/expected/continuous_aggs-15.out
  tsl/test/t/008_mvcc_cagg.pl
  tsl/test/t/CMakeLists.txt
Labels: is-auto-backport

#5781 Backport to 2.11.x: #5742: Fix handling of Result nodes below Sort nodes in ConstraintAwareAppend
  .unreleased/bugfix_5742
  src/nodes/constraint_aware_append/constraint_aware_append.c
  tsl/test/shared/expected/constraint_aware_append.out
  tsl/test/shared/sql/CMakeLists.txt
  tsl/test/shared/sql/constraint_aware_append.sql
Labels: is-auto-backport

#5137 Insert into index during chunk compression
  .unreleased/feature_5137
  tsl/src/compression/api.c
  tsl/src/compression/compression.c
  tsl/src/compression/compression.h
  tsl/test/expected/compression.out
  tsl/test/expected/compression_errors.out
  tsl/test/expected/compression_qualpushdown.out
  tsl/test/expected/compression_sorted_merge-12.out
  tsl/test/expected/compression_sorted_merge-13.out
  tsl/test/expected/compression_sorted_merge-14.out
  tsl/test/expected/compression_sorted_merge-15.out
  tsl/test/expected/transparent_decompression-12.out
  tsl/test/expected/transparent_decompression-13.out
  tsl/test/expected/transparent_decompression-14.out
  tsl/test/expected/transparent_decompression-15.out
  tsl/test/expected/transparent_decompression_join_index.out
  tsl/test/expected/transparent_decompression_ordered_index-12.out
  tsl/test/expected/transparent_decompression_ordered_index-13.out
  tsl/test/expected/transparent_decompression_ordered_index-14.out
  tsl/test/expected/transparent_decompression_ordered_index-15.out
  tsl/test/isolation/expected/compression_merge_race.out
  tsl/test/isolation/specs/compression_merge_race.spec.in
  tsl/test/shared/sql/include/shared_setup.sql
  tsl/test/sql/compression.sql
  tsl/test/sql/compression_errors.sql
  tsl/test/sql/compression_qualpushdown.sql
  tsl/test/sql/compression_sorted_merge.sql.in
  tsl/test/sql/include/transparent_decompression_ordered.sql
  tsl/test/sql/transparent_decompression_join_index.sql
  tsl/test/sql/transparent_decompression_ordered_index.sql.in
Labels: compression

#5819 Backport to 2.11.x: #5798: Fixed batch look ahead in compressed sorted merge
  .unreleased/bugfix_5798
  tsl/src/nodes/decompress_chunk/exec.c
  tsl/src/nodes/decompress_chunk/exec.h
  tsl/src/nodes/decompress_chunk/sorted_merge.c
  tsl/test/expected/compression_sorted_merge-12.out
  tsl/test/expected/compression_sorted_merge-13.out
  tsl/test/expected/compression_sorted_merge-14.out
  tsl/test/expected/compression_sorted_merge-15.out
  tsl/test/sql/compression_sorted_merge.sql.in
Labels: is-auto-backport

#5820 Backport to 2.11.x: #5807: Copy job config JSONB structure into current MemoryContext
  .unreleased/bugfix_5807
  src/bgw/job.c
  tsl/test/expected/bgw_custom.out
  tsl/test/sql/bgw_custom.sql
Labels: is-auto-backport

#5821 Backport to 2.11.x: #5756: Fix issues with scripts/test_update_smoke.sh
  scripts/test_update_smoke.sh
  test/sql/updates/cleanup.multinode.sql
Labels: is-auto-backport

#5515 Make hypertables support replica identity
  .unreleased/feature_5515
  src/chunk.c
  src/chunk_index.c
  src/chunk_index.h
  src/hypertable.c
  src/process_utility.c
  test/expected/alter.out
  test/expected/ddl_errors.out
  test/sql/alter.sql
  test/sql/ddl_errors.sql
  tsl/src/remote/dist_ddl.c
  tsl/test/expected/dist_ddl.out
  tsl/test/sql/dist_ddl.sql
Labels: enhancement

#5836 Fixed output ordering of merge_changelogs.sh script
  scripts/merge_changelogs.sh
Labels: force-auto-backport

#5841 Backport to 2.11.x: #5836: Fixed output ordering of merge_changelogs.sh script
  scripts/merge_changelogs.sh
Labels: is-auto-backport
