Repository timescale/timescaledb, pull requests merged in 2024-05, with the labels that each got.

#6874 Release notes header 2.15.0
  .unreleased/RELEASE_NOTES_HEADER.md.j2
  .unreleased/pr_6621
  .unreleased/template.release_notes_header.j2
  scripts/merge_changelogs.sh
Labels: release, 2.15.0

#6885 Fix policy refresh window too small
  tsl/src/bgw_policy/continuous_aggregate_api.c
  tsl/test/expected/exp_cagg_monthly.out
  tsl/test/sql/exp_cagg_monthly.sql
Labels: bug, continuous_aggregate

#6887 Release 2.15.0
  .unreleased/RELEASE_NOTES_HEADER.md.j2
  .unreleased/auto_sparse_indexes
  .unreleased/bugfix_6677
  .unreleased/bugfix_6717
  .unreleased/bugfix_6729
  .unreleased/bugfix_6732
  .unreleased/bugfix_6752
  .unreleased/bugfix_6789
  .unreleased/bugfix_6796
  .unreleased/feature_6382
  .unreleased/feature_6837
  .unreleased/feature_6865
  .unreleased/fix_6617
  .unreleased/fix_6816
  .unreleased/fix_6820
  .unreleased/pr_6621
  .unreleased/pr_6696
  .unreleased/pr_6698
  .unreleased/pr_6726
  .unreleased/pr_6754
  .unreleased/pr_6767
  .unreleased/pr_6770
  .unreleased/pr_6797
  .unreleased/pr_6798
  .unreleased/pr_6810
  .unreleased/pr_6811
  .unreleased/pr_6849
  .unreleased/pr_6867
  .unreleased/pr_6869
  .unreleased/pr_6870
  .unreleased/template.release_notes_header.j2
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.14.2--2.15.0.sql
  sql/updates/latest-dev.sql
  version.config
Labels: release

#6889 Release 2.15.0: Release branch
  .unreleased/RELEASE_NOTES_HEADER.md.j2
  .unreleased/auto_sparse_indexes
  .unreleased/bugfix_6677
  .unreleased/bugfix_6717
  .unreleased/bugfix_6729
  .unreleased/bugfix_6732
  .unreleased/bugfix_6752
  .unreleased/bugfix_6789
  .unreleased/bugfix_6796
  .unreleased/feature_6382
  .unreleased/feature_6837
  .unreleased/feature_6865
  .unreleased/fix_6617
  .unreleased/fix_6816
  .unreleased/fix_6820
  .unreleased/pr_6621
  .unreleased/pr_6696
  .unreleased/pr_6698
  .unreleased/pr_6726
  .unreleased/pr_6754
  .unreleased/pr_6767
  .unreleased/pr_6770
  .unreleased/pr_6797
  .unreleased/pr_6798
  .unreleased/pr_6810
  .unreleased/pr_6811
  .unreleased/pr_6849
  .unreleased/pr_6867
  .unreleased/pr_6869
  .unreleased/pr_6870
  .unreleased/template.release_notes_header.j2
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.14.2--2.15.0.sql
  sql/updates/2.15.0--2.14.2.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  version.config
Labels: release

#6890 Post-release changes for 2.15.0.
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.15.0--2.14.2.sql
  sql/updates/reverse-dev.sql
  version.config
Labels: release

#6895 Improve compressed DML expression pushdown
  .unreleased/pr_6895
  tsl/src/compression/compression.c
  tsl/test/expected/compression_update_delete.out
  tsl/test/sql/compression_update_delete.sql
Labels: compression

#6880 Add support for array operations to compressed DML
  .unreleased/pr_6880
  tsl/src/compression/compression.c
  tsl/src/compression/compression.h
  tsl/test/expected/compression_update_delete.out
  tsl/test/sql/compression_update_delete.sql
Labels: compression

#6909 Add bitnami docker workflow
  .github/workflows/release_build_packages.yml
Labels: ci

#6910 Bump PG versions used in CI to 13.15, 14.12, 15.7 and 16.3
  .github/ci_settings.py
Labels: ci

#6908 Fix gapfill behaviour around dst switches
  .unreleased/pr_6908
  tsl/src/nodes/gapfill/gapfill_exec.c
  tsl/test/shared/expected/gapfill-13.out
  tsl/test/shared/expected/gapfill-14.out
  tsl/test/shared/expected/gapfill-15.out
  tsl/test/shared/expected/gapfill-16.out
  tsl/test/shared/sql/gapfill.sql.in
Labels: gapfill

#6906 Add Ubuntu 24.04 to CI packaging
  .github/workflows/apt-arm-packages.yaml
  .github/workflows/apt-packages.yaml
Labels: packaging, ci

#6914 Backport to 2.15.x: #6908: Fix gapfill behaviour around dst switches
  .unreleased/pr_6908
  tsl/src/nodes/gapfill/gapfill_exec.c
  tsl/test/shared/expected/gapfill-13.out
  tsl/test/shared/expected/gapfill-14.out
  tsl/test/shared/expected/gapfill-15.out
  tsl/test/shared/expected/gapfill-16.out
  tsl/test/shared/sql/gapfill.sql.in
Labels: is-auto-backport

#6915 Skip downgrade test for Ubuntu 24.04
  .github/workflows/apt-arm-packages.yaml
  .github/workflows/apt-packages.yaml
Labels: ci

#6921 Update README.md
  README.md
Labels: documentation

#6897 Allow replica identity on compressed hypertables
  .unreleased/pr_6897
  src/process_utility.c
  tsl/test/expected/compression_ddl.out
  tsl/test/sql/compression_ddl.sql
Labels: compression, hypertable

#6907 Fix telemetry stats regression test
  src/telemetry/telemetry.c
  tsl/test/expected/telemetry_stats.out
Labels: bug, flaky-test, telemetry

#6926 Backport to 2.15.x: #6894: Add bgw_custom regression test to SOLO_TESTS
  tsl/test/sql/CMakeLists.txt
Labels: is-auto-backport

#6924 Backport to 2.15.x: #6907: Fix telemetry stats regression test
  src/telemetry/telemetry.c
  tsl/test/expected/telemetry_stats-13.out
  tsl/test/expected/telemetry_stats-14.out
  tsl/test/expected/telemetry_stats-15.out
  tsl/test/expected/telemetry_stats-16.out
Labels: is-auto-backport

#6927 Fix flaky telemetry stats regression tests
  test/sql/utils/testsupport.sql
  tsl/test/expected/telemetry_stats.out
Labels: bgw, flaky-test, force-auto-backport

#6922 Fix accessor function cagg_get_bucket_function
  tsl/src/continuous_aggs/repair.c
  tsl/test/expected/cagg_utils.out
  tsl/test/sql/cagg_utils.sql
Labels: bug, continuous_aggregate, time_bucket

#6930 Backport to 2.15.x: #6927: Fix flaky telemetry stats regression tests
  test/sql/utils/testsupport.sql
  tsl/test/expected/telemetry_stats-13.out
  tsl/test/expected/telemetry_stats-14.out
  tsl/test/expected/telemetry_stats-15.out
  tsl/test/expected/telemetry_stats-16.out
Labels: is-auto-backport

#6933 Backport to 2.15.x: #6922: Fix accessor function cagg_get_bucket_function
  tsl/src/continuous_aggs/repair.c
  tsl/test/expected/cagg_utils.out
  tsl/test/sql/cagg_utils.sql
Labels: is-auto-backport

#6928 Remove chunks when truncating a CAgg
  src/process_utility.c
  tsl/test/expected/cagg_ddl-14.out
  tsl/test/expected/cagg_ddl-15.out
  tsl/test/expected/cagg_ddl-16.out
  tsl/test/expected/cagg_invalidation.out
  tsl/test/expected/cagg_on_cagg.out
  tsl/test/expected/cagg_on_cagg_joins.out
  tsl/test/sql/cagg_ddl.sql.in
Labels: continuous_aggregate, hypertable, ddl

#6938 Remove some more PG12 and PG13 code
  src/import/planner.c
  src/process_utility.c
Labels: tech-debt

#6934 Remove dead code
  src/bgw/job.c
  src/bgw/job.h
  src/chunk.c
  src/chunk.h
  src/dimension_vector.c
  src/dimension_vector.h
  src/hypertable.c
  src/hypertable.h
  src/jsonb_utils.c
  src/jsonb_utils.h
  src/ts_catalog/array_utils.c
  src/ts_catalog/array_utils.h
  src/ts_catalog/compression_chunk_size.c
  src/ts_catalog/compression_chunk_size.h
  tsl/src/chunk_api.c
  tsl/src/chunk_api.h
  tsl/src/nodes/CMakeLists.txt
  tsl/src/nodes/compress_dml/CMakeLists.txt
  tsl/src/nodes/compress_dml/compress_dml.c
  tsl/src/nodes/compress_dml/compress_dml.h
  tsl/src/planner.c
Labels: tech-debt

#6939 Refactor CAggTimeBucketInfo to remove redundancy
  src/ts_catalog/continuous_agg.h
  tsl/src/continuous_aggs/common.c
  tsl/src/continuous_aggs/common.h
  tsl/src/continuous_aggs/create.c
Labels: continuous_aggregate, time_bucket, tech-debt

#6911 Fix _timescaledb_functions.remove_dropped_chunk_metadata
  .unreleased/pr_6911
  sql/maintenance_utils.sql
  sql/updates/2.14.2--2.15.0.sql
Labels: update-script

#6942 Backport to 2.15.x: #6911: Fix _timescaledb_functions.remove_dropped_chunk_metadata
  .unreleased/pr_6911
  sql/maintenance_utils.sql
  sql/updates/2.14.2--2.15.0.sql
Labels: is-auto-backport

#6940 Remove regprocedure oid type from catalog
  .unreleased/fix_6940
  sql/pre_install/tables.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  src/ts_catalog/continuous_agg.c
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/utils.c
  tsl/test/expected/cagg_migrate_function-14.out
  tsl/test/expected/cagg_migrate_function-15.out
  tsl/test/expected/cagg_migrate_function-16.out
  tsl/test/expected/cagg_query.out
  tsl/test/expected/exp_cagg_monthly.out
  tsl/test/expected/exp_cagg_origin.out
  tsl/test/expected/exp_cagg_timezone.out
  tsl/test/sql/cagg_query.sql
  tsl/test/sql/include/data/cagg_migrate_integer.sql.gz
  tsl/test/sql/include/data/cagg_migrate_timestamp.sql.gz
  tsl/test/sql/include/data/cagg_migrate_timestamptz.sql.gz
Labels: bug, continuous_aggregate

#6944 Backport to 2.15.x: #6940: Remove regprocedure oid type from catalog
  .unreleased/fix_6940
  sql/pre_install/tables.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  src/ts_catalog/continuous_agg.c
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/utils.c
  tsl/test/expected/cagg_migrate_function-13.out
  tsl/test/expected/cagg_migrate_function-14.out
  tsl/test/expected/cagg_migrate_function-15.out
  tsl/test/expected/cagg_migrate_function-16.out
  tsl/test/expected/cagg_query.out
  tsl/test/expected/exp_cagg_monthly.out
  tsl/test/expected/exp_cagg_origin.out
  tsl/test/expected/exp_cagg_timezone.out
  tsl/test/sql/cagg_query.sql
  tsl/test/sql/include/data/cagg_migrate_integer.sql.gz
  tsl/test/sql/include/data/cagg_migrate_timestamp.sql.gz
  tsl/test/sql/include/data/cagg_migrate_timestamptz.sql.gz
Labels: is-auto-backport

#6947 Add missed changelog message for COPY segfault fix
  .unreleased/fix_compressed_copy_segfault
Labels: force-auto-backport

#6950 Backport to 2.15.x: #6947: Add missed changelog message for COPY segfault fix
  .unreleased/fix_compressed_copy_segfault
Labels: is-auto-backport

#6948 Re-enable compressed OR boolexpr pushdown
  tsl/src/nodes/decompress_chunk/qual_pushdown.c
  tsl/test/expected/compression_qualpushdown.out
  tsl/test/expected/transparent_decompression-14.out
  tsl/test/expected/transparent_decompression-15.out
  tsl/test/expected/transparent_decompression-16.out
  tsl/test/shared/expected/transparent_decompress_chunk-14.out
  tsl/test/shared/expected/transparent_decompress_chunk-15.out
  tsl/test/shared/expected/transparent_decompress_chunk-16.out
Labels: force-auto-backport

#6953 Silence codespell check
  .github/codespell-ignore-words
  .github/workflows/code_style.yaml
  cmake/GenerateScripts.cmake
  cmake/ScriptFiles.cmake
  scripts/backport.py
  scripts/export_prefix_check.sh.in
  tsl/src/continuous_aggs/repair.c
  tsl/test/shared/sql/CMakeLists.txt
  tsl/test/t/003_mvcc_cagg.pl
Labels: ci, force-auto-backport

#6937 Simplify msvc compat stuff
  src/compat/compat-msvc-enter.h
  src/compat/compat-msvc-exit.h
  src/extension.c
  src/loader/loader.c
  src/planner/add_hashagg.c
  src/planner/planner.c
Labels: tech-debt

#6946 Backport to 2.15.x: #6931: Do not decompress batches for COPY with potentially invalid slot
  src/copy.c
  src/nodes/chunk_dispatch/chunk_dispatch.c
  src/nodes/chunk_dispatch/chunk_dispatch.h
  tsl/src/compression/compression.c
  tsl/test/expected/compress_dml_copy.out
  tsl/test/expected/compression_insert.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/compress_dml_copy.sql
  tsl/test/sql/compression_insert.sql
Labels: is-auto-backport

#6951 Add pg_upgrade test to CI
  .github/workflows/code_style.yaml
  .github/workflows/pg_upgrade-test.yaml
  scripts/test_pg_upgrade.py
  test/sql/updates/post.pg_upgrade.sql
Labels: ci, pg-upgrade

#6952 Backport to 2.15.x: #6917: Block OR BoolExpr from pushdown
  tsl/src/nodes/decompress_chunk/qual_pushdown.c
  tsl/test/expected/compression_qualpushdown.out
  tsl/test/expected/transparent_decompression-13.out
  tsl/test/expected/transparent_decompression-14.out
  tsl/test/expected/transparent_decompression-15.out
  tsl/test/expected/transparent_decompression-16.out
  tsl/test/shared/expected/transparent_decompress_chunk-13.out
  tsl/test/shared/expected/transparent_decompress_chunk-14.out
  tsl/test/shared/expected/transparent_decompress_chunk-15.out
  tsl/test/shared/expected/transparent_decompress_chunk-16.out
  tsl/test/sql/compression_qualpushdown.sql
Labels: is-auto-backport

#6954 Backport to 2.15.x: #6948: Re-enable compressed OR boolexpr pushdown
  tsl/src/nodes/decompress_chunk/qual_pushdown.c
  tsl/test/expected/compression_qualpushdown.out
  tsl/test/expected/transparent_decompression-13.out
  tsl/test/expected/transparent_decompression-14.out
  tsl/test/expected/transparent_decompression-15.out
  tsl/test/expected/transparent_decompression-16.out
  tsl/test/shared/expected/transparent_decompress_chunk-13.out
  tsl/test/shared/expected/transparent_decompress_chunk-14.out
  tsl/test/shared/expected/transparent_decompress_chunk-15.out
  tsl/test/shared/expected/transparent_decompress_chunk-16.out
Labels: is-auto-backport

#6958 Fix coverity warning about null pointer dereference
  tsl/src/continuous_aggs/common.c
Labels: coverity

#6957 Fix segfault in UNION queries with top-level ordering
  .unreleased/pr_6957
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/test/shared/expected/transparent_decompress_chunk-14.out
  tsl/test/shared/expected/transparent_decompress_chunk-15.out
  tsl/test/shared/expected/transparent_decompress_chunk-16.out
  tsl/test/shared/sql/transparent_decompress_chunk.sql.in
Labels: bug

#6962 Backport to 2.15.x: #6958: Fix coverity warning about null pointer dereference
  tsl/src/continuous_aggs/common.c
Labels: is-auto-backport

#6963 Backport to 2.15.x: #6932: Make constification functions visible outside timescale library
  src/nodes/chunk_append/chunk_append.h
  src/nodes/chunk_append/exec.c
Labels: is-auto-backport

#6961 Backport to 2.15.x: #6957: Fix segfault in UNION queries with top-level ordering
  .unreleased/pr_6957
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/test/shared/expected/transparent_decompress_chunk-13.out
  tsl/test/shared/expected/transparent_decompress_chunk-14.out
  tsl/test/shared/expected/transparent_decompress_chunk-15.out
  tsl/test/shared/expected/transparent_decompress_chunk-16.out
  tsl/test/shared/sql/transparent_decompress_chunk.sql.in
Labels: is-auto-backport

#6956 Add check for column types we use in our catalog.
  .github/workflows/catalog-updates-check.yaml
  scripts/check_updates_ast.py
Labels: ci

#6966 Release 2.15.1
  .unreleased/fix_6858
  .unreleased/fix_6940
  .unreleased/fix_compressed_copy_segfault
  .unreleased/pr_6908
  .unreleased/pr_6911
  .unreleased/pr_6957
  .unreleased/template.release_notes_header.j2
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.15.0--2.15.1.sql
  sql/updates/latest-dev.sql
  version.config
Labels: release

#6973 Post release 2.15.1
  sql/CMakeLists.txt
  sql/updates/2.15.1--2.15.0.sql
  sql/updates/reverse-dev.sql
  version.config
Labels: release
