Repository timescale/timescaledb, pull requests merged in 2024-03, with the labels that each got.

#6717 Fix handling of compressed tables in COPY path
  .unreleased/bugfix_6717
  src/copy.c
  src/nodes/chunk_dispatch/chunk_dispatch.h
  src/nodes/chunk_dispatch/chunk_insert_state.c
  tsl/src/compression/compression.c
  tsl/test/expected/compression.out
  tsl/test/sql/compression.sql
Labels: bug, segfault

#6719 Backport to 2.14.x: #6717: Fix handling of compressed tables in COPY path
  .unreleased/bugfix_6717
  src/copy.c
  src/nodes/chunk_dispatch/chunk_dispatch.h
  src/nodes/chunk_dispatch/chunk_insert_state.c
  tsl/src/compression/compression.c
  tsl/test/expected/compression.out
  tsl/test/sql/compression.sql
Labels: is-auto-backport

#6721 Increase PG startup time on windows
  .github/workflows/windows-build-and-test.yaml
Labels: ci

#6697 Refactor update test
  .github/workflows/update-test.yaml
  .gitignore
  scripts/test_downgrade.sh
  scripts/test_downgrade_from_tag.sh
  scripts/test_functions.inc
  scripts/test_repair_from_tag.sh
  scripts/test_repairs.sh
  scripts/test_update_from_tag.sh
  scripts/test_update_from_version.sh
  scripts/test_updates.sh
  scripts/test_updates_pg13.sh
  scripts/test_updates_pg14.sh
  scripts/test_updates_pg15.sh
  scripts/test_updates_pg16.sh
  test/sql/updates/README.md
  test/sql/updates/post.repair.sql
  test/sql/updates/setup.repair.sql
Labels: ci

#6726 Fix constify cagg_watermark using window functions
  .unreleased/pr_6726
  tsl/src/continuous_aggs/planner.c
  tsl/test/expected/cagg_watermark-13.out
  tsl/test/expected/cagg_watermark-14.out
  tsl/test/expected/cagg_watermark-15.out
  tsl/test/expected/cagg_watermark-16.out
  tsl/test/sql/cagg_watermark.sql.in
Labels: bug, continuous_aggregate

#6738 Disable homebrew automatic dependency upgrades
  .github/workflows/linux-build-and-test.yaml
Labels: bug, ci, MacOS

#6737 Refactor returning time dimension MINIMUM value
  tsl/src/continuous_aggs/common.h
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/invalidation_threshold.c
  tsl/src/continuous_aggs/refresh.c
Labels: continuous_aggregate, time_bucket, tech-debt

#6736 Use INVALID_HYPERTABLE_ID constant when necessary
  src/bgw/job.c
  tsl/src/bgw_policy/job_api.c
Labels: core, tech-debt

#6735 Add handler functions for Datum/Bools arrays
  src/utils.c
  src/utils.h
  tsl/src/continuous_aggs/utils.c
Labels: core, tech-debt

#6744 Check for missing memory context switch back
  coccinelle/mcxt.cocci
  src/telemetry/telemetry.c
Labels: segfault

#6752 Remove autovacuum setting from compressed chunks
  .unreleased/bugfix_6752
  sql/updates/latest-dev.sql
Labels: bug

#6740 Convert max materializations setting to GUC
  src/guc.c
  src/guc.h
  tsl/src/continuous_aggs/refresh.c
  tsl/test/expected/cagg_invalidation.out
  tsl/test/sql/cagg_invalidation.sql
Labels: continuous_aggregate, enhancement

#6761 Make CAgg error message more clear
  tsl/src/continuous_aggs/common.c
  tsl/test/expected/cagg_errors.out
Labels: continuous_aggregate, tech-debt

#6764 Exclude is_sparse_index_type in non assert builds
  tsl/src/compression/create.c
Labels: ci

#6684 Populate CAgg bucket catalog table for all CAggs
  sql/pre_install/tables.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  src/func_cache.c
  src/ts_catalog/catalog.h
  src/ts_catalog/continuous_agg.c
  src/ts_catalog/continuous_agg.h
  src/ts_catalog/continuous_aggs_watermark.c
  tsl/src/bgw_policy/continuous_aggregate_api.c
  tsl/src/continuous_aggs/common.c
  tsl/src/continuous_aggs/common.h
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/invalidation.c
  tsl/src/continuous_aggs/invalidation_threshold.c
  tsl/src/continuous_aggs/refresh.c
  tsl/src/continuous_aggs/refresh.h
  tsl/src/continuous_aggs/repair.c
  tsl/test/expected/cagg_bgw-13.out
  tsl/test/expected/cagg_bgw-14.out
  tsl/test/expected/cagg_bgw-15.out
  tsl/test/expected/cagg_bgw-16.out
  tsl/test/expected/cagg_migrate.out
  tsl/test/expected/cagg_watermark-13.out
  tsl/test/expected/cagg_watermark-14.out
  tsl/test/expected/cagg_watermark-15.out
  tsl/test/expected/cagg_watermark-16.out
  tsl/test/expected/exp_cagg_monthly.out
  tsl/test/expected/exp_cagg_timezone.out
  tsl/test/sql/cagg_bgw.sql.in
  tsl/test/sql/cagg_watermark.sql.in
  tsl/test/sql/exp_cagg_monthly.sql
  tsl/test/sql/exp_cagg_timezone.sql
  tsl/test/sql/include/data/cagg_migrate_integer.sql.gz
  tsl/test/sql/include/data/cagg_migrate_timestamp.sql.gz
  tsl/test/sql/include/data/cagg_migrate_timestamptz.sql.gz
Labels: continuous_aggregate

#6765 Move cagg_invalidation to solo tests
  tsl/test/sql/CMakeLists.txt
Labels: testing, continuous_aggregate, flaky-test

#6768 Remove multinode reference from update smoke test.
  scripts/test_update_smoke.sh
Labels: bug, force-auto-backport

#6769 Backport to 2.14.x: #6768: Remove multinode reference from update smoke test.
  scripts/test_update_smoke.sh
Labels: is-auto-backport

#6776 Refactor parameter of invalidation_state_init
  tsl/src/continuous_aggs/invalidation.c
  tsl/src/continuous_aggs/invalidation.h
  tsl/src/continuous_aggs/refresh.c
Labels: continuous_aggregate, tech-debt, refactor

#6747 Backport to 2.14.x: #6617: Fix error in show_chunks
  .unreleased/fix_6617
  src/chunk.c
  test/expected/chunk_utils.out
  test/sql/chunk_utils.sql
  tsl/test/expected/policy_generalization.out
  tsl/test/sql/policy_generalization.sql
Labels: is-auto-backport

#6778 Exclude OSM chunks from enabling autovaccum
  sql/updates/latest-dev.sql
Labels: force-auto-backport

#6777 Fix uploading Postgres log on Windows CI
  .github/workflows/windows-build-and-test.yaml
Labels: windows, ci

#6786 Add wait_for_job_to_run to testsupport.sql
  test/runner.sh
  test/sql/utils/testsupport.sql
  tsl/test/expected/bgw_custom-13.out
  tsl/test/expected/bgw_custom-14.out
  tsl/test/expected/bgw_custom-15.out
  tsl/test/expected/bgw_custom-16.out
  tsl/test/expected/cagg_bgw-13.out
  tsl/test/expected/cagg_bgw-14.out
  tsl/test/expected/cagg_bgw-15.out
  tsl/test/expected/cagg_bgw-16.out
  tsl/test/expected/scheduler_fixed.out
  tsl/test/sql/bgw_custom.sql.in
  tsl/test/sql/cagg_bgw.sql.in
  tsl/test/sql/scheduler_fixed.sql
Labels: testing, tech-debt

#6794 Remove unneeded pg_locale.h include
  tsl/src/nodes/decompress_chunk/pred_text.c
Labels: build
