Repository timescale/timescaledb, pull requests merged in 2024-12, with the labels that each got.

#7495 Remove backward direction for ABI tests
  .github/workflows/abi.yaml
Labels: testing, ci

#7504 Warning for the old CAggs format in all PG versions
  sql/updates/post-update.sql
Labels: continuous_aggregate, deprecation

#7503 Fix CAgg permissions regression leftovers
  tsl/test/expected/cagg_permissions-14.out
  tsl/test/expected/cagg_permissions-15.out
  tsl/test/expected/cagg_permissions-16.out
  tsl/test/expected/cagg_permissions-17.out
  tsl/test/sql/cagg_permissions.sql.in
Labels: testing, continuous_aggregate, force-auto-backport

#7507 Fix flaky jit regression test
  tsl/test/expected/jit.out
  tsl/test/sql/jit.sql
Labels: testing, flaky-test

#7492 Don't invalidate relation cache if cagg watermark constify is false
  src/ts_catalog/continuous_aggs_watermark.c
Labels: continuous_aggregate

#7509 Fix flaky reorder regression test
  tsl/test/expected/reorder.out
  tsl/test/sql/reorder.sql
Labels: testing, flaky-test

#7508 Add workaround for pg_depend bug in PG < 15.4
  tsl/src/compression/api.c
Labels: bug, hypercore

#7511 Encapsulate runner output cleanup into single script
  test/runner.sh
  test/runner_cleanup_output.sh
  test/runner_isolation.sh
  test/runner_shared.sh
Labels: testing, tech-debt, force-auto-backport

#7498 Add tests for exclude constraints on Hypercore TAM
  tsl/test/expected/hypercore_constraints.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/hypercore_constraints.sql
Labels: table-access-method, hypercore

#7512 Fix flaky append regression test
  test/expected/append-14.out
  test/expected/append-15.out
  test/expected/append-16.out
  test/expected/append-17.out
  test/sql/include/append_load.sql
  test/sql/include/append_query.sql
Labels: testing, planner, flaky-test

#7522 Fix flaky append regression test take 2
  test/expected/append-14.out
  test/expected/append-15.out
  test/expected/append-16.out
  test/expected/append-17.out
  test/expected/null_exclusion-14.out
  test/expected/null_exclusion-15.out
  test/expected/null_exclusion-16.out
  test/expected/null_exclusion-17.out
  test/expected/plan_ordered_append-14.out
  test/expected/plan_ordered_append-15.out
  test/expected/plan_ordered_append-16.out
  test/expected/plan_ordered_append-17.out
  test/runner_cleanup_output.sh
  tsl/test/expected/cagg_watermark.out
  tsl/test/expected/plan_skip_scan-14.out
  tsl/test/expected/plan_skip_scan-15.out
  tsl/test/expected/plan_skip_scan-16.out
  tsl/test/expected/plan_skip_scan-17.out
  tsl/test/expected/transparent_decompression-14.out
  tsl/test/expected/transparent_decompression-15.out
  tsl/test/expected/transparent_decompression-16.out
  tsl/test/expected/transparent_decompression-17.out
  tsl/test/shared/expected/constraint_exclusion_prepared.out
  tsl/test/shared/expected/memoize.out
  tsl/test/shared/expected/ordered_append-14.out
  tsl/test/shared/expected/ordered_append-15.out
  tsl/test/shared/expected/ordered_append-16.out
  tsl/test/shared/expected/ordered_append-17.out
  tsl/test/shared/expected/ordered_append_join-14.out
  tsl/test/shared/expected/ordered_append_join-15.out
  tsl/test/shared/expected/ordered_append_join-16.out
  tsl/test/shared/expected/ordered_append_join-17.out
Labels: testing, planner, flaky-test

#6901 Add support for transition tables
  .unreleased/pr_6901
  src/copy.c
  src/hypertable.c
  src/planner/planner.c
  src/process_utility.c
  src/trigger.c
  src/trigger.h
  test/expected/triggers.out
  test/sql/triggers.sql
  tsl/test/expected/hypercore_trigger.out
  tsl/test/sql/hypercore_trigger.sql
Labels: hypertable, enhancement

#7491 Add tests for unique index creation with Hypercore TAM
  tsl/test/expected/hypercore_index_btree.out
  tsl/test/sql/hypercore_index_btree.sql
Labels: hypercore

#7514 Fix error: invalid child of chunk append
  .unreleased/pr_7514
  src/nodes/chunk_append/planner.c
Labels: bug

#7526 Backport to 2.17.x: #7514: Fix error: invalid child of chunk append
  .unreleased/pr_7514
  src/nodes/chunk_append/planner.c
Labels: is-auto-backport

#7523 Bump setup windows wsl on CI
  .github/workflows/windows-build-and-test.yaml
Labels: ci

#7505 Refactor continuous aggregate materialization code
  tsl/src/continuous_aggs/materialize.c
Labels: continuous_aggregate, tech-debt

#7530 Fix compiler error when using PG_TRY..PG_FINALLY
  tsl/src/continuous_aggs/materialize.c
Labels: bug, continuous_aggregate, ci, disable-auto-backport

#7457 Add ABI test against PG snapshot
  .github/workflows/snapshot-abi.yaml
Labels: ci

#7541 Fix broken link for installation docs
  docs/BuildSource.md
Labels: documentation

#7533 Fix wrong origin returned by cagg_get_bucket_function_info
  tsl/src/continuous_aggs/common.c
  tsl/test/expected/cagg_migrate_function-14.out
  tsl/test/expected/cagg_migrate_function-15.out
  tsl/test/expected/cagg_migrate_function-16.out
  tsl/test/expected/cagg_migrate_function-17.out
  tsl/test/expected/cagg_query-14.out
  tsl/test/expected/cagg_query-15.out
  tsl/test/expected/cagg_query-16.out
  tsl/test/expected/cagg_query-17.out
  tsl/test/expected/cagg_query_using_merge-15.out
  tsl/test/expected/cagg_query_using_merge-16.out
  tsl/test/expected/cagg_query_using_merge-17.out
  tsl/test/expected/cagg_utils.out
  tsl/test/sql/CMakeLists.txt
Labels: bug, continuous_aggregate, time_bucket

#7542 Disable false positive warning on shellcheck
  scripts/clang_format_wrapper.sh
Labels: ci, force-auto-backport

#7544 Backport to 2.17.x: #7542: Disable false positive warning on shellcheck
  scripts/clang_format_wrapper.sh
Labels: is-auto-backport

#7537 Optimize conflict do update (upserts) on Hypercore TAM
  src/cross_module_fn.h
  src/nodes/chunk_dispatch/chunk_dispatch.c
  src/nodes/hypertable_modify.c
  tsl/src/hypercore/hypercore_handler.c
  tsl/src/hypercore/hypercore_handler.h
  tsl/src/init.c
Labels: upsert, table-access-method, hypercore

#7545 Pinned Ubuntu version in package workflow to 22.04
  .github/workflows/apt-arm-packages.yaml
Labels: ci

#7464 Update README to match pgai docs
  README.md
Labels: documentation

#7482 Optimize segmentwise recompression
  .unreleased/pr_7482
  tsl/src/compression/CMakeLists.txt
  tsl/src/compression/api.c
  tsl/src/compression/api.h
  tsl/src/compression/recompress.c
  tsl/src/compression/recompress.h
  tsl/src/init.c
  tsl/test/expected/recompress_chunk_segmentwise.out
  tsl/test/isolation/expected/compression_ddl_iso.out
  tsl/test/t/002_logrepl_decomp_marker.pl
Labels: compression, enhancement

#7549 Minor README.md fixes
  README.md
Labels: documentation

#7560 Upgrade pinned PG version to fix Homebrew tests
  .github/workflows/homebrew.yaml
Labels: testing

#7561 Fix for failing Homebrew tests
  .github/workflows/homebrew.yaml
Labels: testing

#7557 Fix NULL handling for in-memory tuple filtering
  .unreleased/pr_7557
  tsl/src/compression/compression_dml.c
  tsl/src/compression/compression_dml.h
  tsl/src/compression/compression_scankey.c
  tsl/src/compression/recompress.c
  tsl/test/shared/expected/compression_nulls_not_distinct.out
  tsl/test/shared/sql/compression_nulls_not_distinct.sql
Labels: bug, compression
