Repository timescale/timescaledb, pull requests merged in 2024-09, with the labels that each got.

#7207 Refactor decompress_batches_scan functions
  .unreleased/pr_7207
  tsl/src/compression/compression_dml.c
Labels: compression, enhancement

#7223 Optimize BGW CI tests
  tsl/test/expected/bgw_custom.out
  tsl/test/expected/bgw_job_stat_history_errors.out
  tsl/test/sql/bgw_custom.sql
  tsl/test/sql/bgw_job_stat_history_errors.sql
Labels: ci

#7230 Don't propagate fk constraints to osm chunk
  .unreleased/pr_7230
  src/foreign_key.c
  tsl/test/expected/chunk_utils_internal.out
  tsl/test/sql/chunk_utils_internal.sql
Labels: data-tiering

#7237 Fix flaky chunk_utils_internal test
  tsl/test/expected/chunk_utils_internal.out
  tsl/test/sql/chunk_utils_internal.sql
Labels: ci

#7238 Fix MERGE ROWID_VAR handling for PG17
  .github/gh_matrix_builder.py
  src/nodes/chunk_dispatch/chunk_dispatch.c
  src/nodes/chunk_dispatch/chunk_insert_state.c
  test/expected/ts_merge-17.out
Labels: pg17

#7243 PG17: Fix makeaclitem
  .github/gh_matrix_builder.py
  src/utils.c
Labels: pg17

#7255 Remove update test output for pg17
  test/expected/update-17.out
  test/sql/.gitignore
Labels: pg17

#7254 Remove delete test output for pg17
  test/expected/delete-17.out
  test/sql/.gitignore
Labels: pg17

#7252 Remove PG17 cursor test
  test/expected/cursor-17.out
  test/sql/.gitignore
Labels: pg17

#7251 Remove PG17 jit test output
  tsl/test/expected/jit-17.out
  tsl/test/sql/.gitignore
Labels: pg17

#7249 Remove PG17 telemetry_stats test output
  .github/workflows/windows-build-and-test.yaml
  tsl/test/expected/telemetry_stats-17.out
  tsl/test/sql/.gitignore
Labels: pg17

#7247 Remove constify_now PG17 output
  tsl/test/shared/expected/constify_now-17.out
  tsl/test/shared/sql/.gitignore
Labels: pg17

#7244 Remove generated file from repository and add it to .gitignore
  .gitignore
  test/temp_schedule.backup
Labels: ci

#7250 Remove compression_bgw PG17 output
  tsl/test/expected/compression_bgw-17.out
Labels: pg17

#7246 Remove space_constraint pg17 output
  tsl/test/shared/expected/space_constraint-17.out
  tsl/test/shared/sql/.gitignore
Labels: pg17

#7253 Remove ddl test pg17 output
  test/expected/ddl-17.out
  test/sql/.gitignore
Labels: pg17

#7248 Remove bgw_custom PG17 test output
  tsl/test/expected/bgw_custom-17.out
  tsl/test/sql/.gitignore
Labels: pg17

#7242 Fix TAP tests for PG17
  .github/gh_matrix_builder.py
  tsl/test/t/001_job_crash_log.pl
Labels: pg17

#7261 Add simple test for new PG17 MAINTAIN privilege
  tsl/test/expected/privilege_maintain.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/privilege_maintain.sql
Labels: pg17

#7258 Force english in pg_config command
  .unreleased/pr_7258
  CMakeLists.txt
Labels: build

#7262 Backport to 2.16.x: #7258: Force english in pg_config command
  .unreleased/pr_7258
  CMakeLists.txt
Labels: is-auto-backport

#7235 Backport to 2.16.x: #7229: Fix FK constraint where index and constraint column order differ
  .unreleased/pr_7229
  src/foreign_key.c
  tsl/test/expected/foreign_keys.out
  tsl/test/sql/foreign_keys.sql
Labels: is-auto-backport

#7270 Reset per compressed row memory context during tuple filtering
  .unreleased/pr_7270
  tsl/src/compression/compression.c
Labels: bug

#7277 Backport to 2.16.x: #7270: Reset per compressed row memory context during tuple filtering
  .unreleased/pr_7270
  tsl/src/compression/compression.c
Labels: is-auto-backport

#7265 Grant USAGE on debug schema
  sql/pre_install/schemas.sql
  test/expected/debug_utils.out
  test/sql/CMakeLists.txt
  test/sql/debug_utils.sql
Labels: debugging

#7275 Implement support for RETURNING clause for MERGE
  .unreleased/pr_7275
  src/import/ht_hypertable_modify.c
  src/import/ht_hypertable_modify.h
  src/nodes/hypertable_modify.c
  test/expected/ts_merge-17.out
Labels: pg17

#7279 Add additional tests for PG17 MERGE support
  test/expected/ts_merge-15.out
  test/expected/ts_merge-16.out
  test/expected/ts_merge-17.out
  test/sql/include/ts_merge_query.sql
  test/sql/ts_merge.sql.in
Labels: pg17

#7291 Refactor job error handling
  src/bgw/job.c
  src/bgw/job.h
  src/bgw/job_stat.c
  src/bgw/job_stat.h
  src/bgw/scheduler.c
  src/utils.c
  src/utils.h
  test/expected/test_utils.out
  test/sql/test_utils.sql
  test/sql/utils/testsupport.sql
  test/src/test_utils.c
  tsl/test/expected/bgw_job_stat_history_errors.out
  tsl/test/postgresql.conf.in
  tsl/test/sql/bgw_job_stat_history_errors.sql
Labels: bgw, tech-debt
