Repository timescale/timescaledb, pull requests merged in 2024-07, with the labels that each got.

#7082 Backport to 2.15.x: #7035: Fix ERROR when acquiring a tuple lock on OSM chunks on replica
  src/hypertable.c
Labels: is-auto-backport

#7081 Remove some dead code related to distributed hypertables
  src/nodes/hypertable_modify.c
  src/nodes/hypertable_modify.h
Labels: tech-debt

#7080 Fix `corresponding equivalence member not found`
  .unreleased/pr_7080
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/test/expected/transparent_decompression-14.out
  tsl/test/expected/transparent_decompression-15.out
  tsl/test/expected/transparent_decompression-16.out
  tsl/test/sql/transparent_decompression.sql.in
Labels: bug

#7083 Backport to 2.15.x: #7080: Fix `corresponding equivalence member not found`
  .unreleased/pr_7080
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/test/expected/transparent_decompression-13.out
  tsl/test/expected/transparent_decompression-14.out
  tsl/test/expected/transparent_decompression-15.out
  tsl/test/expected/transparent_decompression-16.out
  tsl/test/sql/transparent_decompression.sql.in
Labels: is-auto-backport

#7090 Backport to 2.15.x: #7088: Fix leaks with functions in DML
  .unreleased/fix_7088
  src/cache.c
  test/expected/copy_memory_usage.out
  test/sql/CMakeLists.txt
  test/sql/copy_memory_usage.sql
Labels: is-auto-backport

#7091 Use processed group clause in PG16 (take 2)
  src/planner/add_hashagg.c
  tsl/test/expected/cagg_joins.out
  tsl/test/sql/cagg_joins.sql
Labels: bug, planner

#7094 Remove centos7 from package test
  .github/workflows/rpm-packages.yaml
Labels: ci

#7075 Reduce decompression on compressed INSERT
  .unreleased/pr_7075
  tsl/src/compression/compression.c
  tsl/src/compression/compression.h
  tsl/test/expected/compression.out
  tsl/test/expected/compression_conflicts.out
  tsl/test/expected/compression_insert.out
  tsl/test/shared/expected/compress_unique_index.out
  tsl/test/shared/expected/compression_dml.out
  tsl/test/shared/expected/decompress_tracking.out
  tsl/test/shared/sql/compression_dml.sql
  tsl/test/sql/compression_insert.sql
  tsl/test/t/002_logrepl_decomp_marker.pl
Labels: compression

#7100 Adjust compression file organization
  tsl/src/compression/CMakeLists.txt
  tsl/src/compression/algorithms/CMakeLists.txt
  tsl/src/compression/algorithms/array.c
  tsl/src/compression/algorithms/array.h
  tsl/src/compression/algorithms/datum_serialize.c
  tsl/src/compression/algorithms/datum_serialize.h
  tsl/src/compression/algorithms/deltadelta.c
  tsl/src/compression/algorithms/deltadelta.h
  tsl/src/compression/algorithms/deltadelta_impl.c
  tsl/src/compression/algorithms/dictionary.c
  tsl/src/compression/algorithms/dictionary.h
  tsl/src/compression/algorithms/dictionary_hash.h
  tsl/src/compression/algorithms/float_utils.h
  tsl/src/compression/algorithms/gorilla.c
  tsl/src/compression/algorithms/gorilla.h
  tsl/src/compression/algorithms/gorilla_impl.c
  tsl/src/compression/algorithms/simple8b_rle.h
  tsl/src/compression/algorithms/simple8b_rle_bitmap.h
  tsl/src/compression/algorithms/simple8b_rle_decompress_all.h
  tsl/src/compression/compression.c
  tsl/src/compression/compression.h
  tsl/src/compression/compression_dml.c
  tsl/src/compression/compression_dml.h
  tsl/src/compression/compression_scankey.c
  tsl/src/compression/segment_meta.c
  tsl/src/init.c
  tsl/src/nodes/decompress_chunk/exec.c
  tsl/test/src/compression_unit_test.c
Labels: refactor

#7101 Reduce decompressions for compressed UPDATE/DELETE
  .unreleased/pr_7101
  src/guc.c
  src/guc.h
  tsl/src/compression/compression_dml.c
  tsl/src/compression/compression_dml.h
  tsl/src/compression/compression_scankey.c
  tsl/test/expected/compression_update_delete.out
  tsl/test/shared/expected/compression_dml.out
  tsl/test/shared/sql/compression_dml.sql
Labels: compression

#7109 Allow building against PG17
  src/bgw/job.c
  src/chunk_index.c
  src/compat/compat.h
  src/copy.c
  src/import/ht_hypertable_modify.c
  src/loader/bgw_message_queue.c
  src/nodes/chunk_dispatch/chunk_dispatch.c
  src/nodes/chunk_dispatch/chunk_insert_state.c
  src/nodes/hypertable_modify.c
  src/process_utility.c
  test/src/test_utils.c
  tsl/src/compression/compression.c
  tsl/src/compression/compression_storage.c
  tsl/src/compression/wal_utils.h
  tsl/src/reorder.c
Labels: pg17

#7108 Reduce decompression for INSERT with unique constraints
  .unreleased/pr_7108
  src/nodes/chunk_dispatch/chunk_dispatch.c
  src/nodes/chunk_dispatch/chunk_dispatch.h
  src/nodes/chunk_dispatch/chunk_insert_state.c
  src/nodes/chunk_dispatch/chunk_insert_state.h
  src/nodes/hypertable_modify.c
  tsl/src/compression/compression_dml.c
  tsl/src/compression/compression_dml.h
  tsl/src/compression/compression_scankey.c
  tsl/test/expected/compression_conflicts.out
  tsl/test/expected/compression_insert.out
  tsl/test/isolation/expected/compression_conflicts_iso.out
  tsl/test/shared/expected/compression_dml.out
  tsl/test/t/002_logrepl_decomp_marker.pl
Labels: compression

#7124 Add compression tuple filtering information to EXPLAIN
  src/nodes/chunk_dispatch/chunk_dispatch.h
  src/nodes/hypertable_modify.c
  src/nodes/hypertable_modify.h
  tsl/src/compression/compression.h
  tsl/src/compression/compression_dml.c
  tsl/test/shared/expected/compress_unique_index.out
  tsl/test/shared/expected/compression_dml.out
  tsl/test/shared/expected/decompress_tracking.out
Labels: compression

#7111 Relax CAggs JOIN restrictions
  tsl/src/continuous_aggs/common.c
  tsl/test/expected/cagg_errors.out
  tsl/test/expected/cagg_joins.out
  tsl/test/expected/cagg_utils.out
  tsl/test/sql/cagg_joins.sql
Labels: continuous_aggregate, enhancement

#7123 Fix coverity warning about NULL pointer dereference
  tsl/src/compression/compression_dml.c
Labels: coverity

#7131 Fix `enable_job_execution_logging` GUC context
  src/guc.c
  tsl/test/expected/bgw_job_stat_history.out
  tsl/test/sql/bgw_job_stat_history.sql
Labels: bug, bgw

#7139 Backport to 2.15.x: #7131: Fix `enable_job_execution_logging` GUC context
  src/guc.c
  tsl/test/expected/bgw_job_stat_history.out
  tsl/test/sql/bgw_job_stat_history.sql
Labels: is-auto-backport

#7138 Fix CAgg watermark constify using CTE
  tsl/src/continuous_aggs/planner.c
  tsl/test/expected/cagg_watermark-14.out
  tsl/test/expected/cagg_watermark-15.out
  tsl/test/expected/cagg_watermark-16.out
  tsl/test/expected/cagg_watermark-17.out
  tsl/test/sql/cagg_watermark.sql.in
Labels: bug, continuous_aggregate

#7140 Backport to 2.15.x: #7138: Fix CAgg watermark constify using CTE
  tsl/src/continuous_aggs/planner.c
  tsl/test/expected/cagg_watermark-13.out
  tsl/test/expected/cagg_watermark-14.out
  tsl/test/expected/cagg_watermark-15.out
  tsl/test/expected/cagg_watermark-16.out
  tsl/test/sql/cagg_watermark.sql.in
Labels: is-auto-backport

#7136 Fix integer overflow in window size calculation
  tsl/src/bgw_policy/policies_v2.c
Labels: coverity

#7116 Use DELETE after compression
  .unreleased/pr_7116
  src/guc.c
  src/guc.h
  tsl/src/compression/compression.c
  tsl/test/expected/compression.out
  tsl/test/isolation/expected/compression_freeze.out
  tsl/test/isolation/specs/compression_freeze.spec
  tsl/test/sql/compression.sql
Labels: compression

#7145 Remove unused variable
  tsl/src/continuous_aggs/common.c
Labels: bug, tech-debt

#7128 Optimize index path generation for ordered append
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/test/expected/transparent_decompression-14.out
  tsl/test/expected/transparent_decompression-15.out
  tsl/test/expected/transparent_decompression-16.out
  tsl/test/sql/include/transparent_decompression_query.sql
Labels: planner

#7154 Fix snapshot tests
  test/expected/debug_utils.out
  test/pgtest/CMakeLists.txt
  test/sql/debug_utils.sql
  test/t/001_extension.pl
  test/t/001_replication_telemetry.pl
  test/t/CMakeLists.txt
  test/t/functions.sql.in
Labels: ci

#7149 Fix CAggs partial view dependencies
  scripts/test_pg_upgrade.py
  scripts/test_update_from_version.sh
  test/sql/updates/post.pg_upgrade.sql
  test/sql/updates/setup.pg_upgrade.sql
  tsl/src/continuous_aggs/create.c
Labels: bug, continuous_aggregate, upgrade

#7153 Install testgres using pip on CI
  .github/workflows/pg_upgrade-test.yaml
Labels: ci, tech-debt

#6987 Fix REASSIGN OWNED BY for background jobs
  .unreleased/pr_6987
  src/bgw/job.h
  src/process_utility.c
  tsl/test/expected/bgw_db_scheduler.out
  tsl/test/expected/bgw_job_ddl.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/bgw_db_scheduler.sql
  tsl/test/sql/bgw_job_ddl.sql
Labels: bgw, ddl

#7163 Backport to 2.15.x: #6987: Fix REASSIGN OWNED BY for background jobs
  .unreleased/pr_6987
  src/bgw/job.h
  src/process_utility.c
  tsl/test/expected/bgw_db_scheduler.out
  tsl/test/expected/bgw_job_ddl.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/bgw_db_scheduler.sql
  tsl/test/sql/bgw_job_ddl.sql
Labels: is-auto-backport

#7164 Add GUC for foreign key propagation
  src/guc.c
  src/guc.h
  src/planner/expand_hypertable.c
  src/planner/planner.c
  src/planner/planner.h
Labels: planner, hypertable

#7172 Release 2.16.0
  .unreleased/fix_7055
  .unreleased/fix_7064
  .unreleased/fix_7074
  .unreleased/pr_6880
  .unreleased/pr_6895
  .unreleased/pr_6897
  .unreleased/pr_6918
  .unreleased/pr_6920
  .unreleased/pr_6987
  .unreleased/pr_6989
  .unreleased/pr_7018
  .unreleased/pr_7020
  .unreleased/pr_7046
  .unreleased/pr_7048
  .unreleased/pr_7069
  .unreleased/pr_7075
  .unreleased/pr_7101
  .unreleased/pr_7108
  .unreleased/pr_7116
  .unreleased/pr_7134
  .unreleased/pr_7161
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.15.3--2.16.0.sql
  sql/updates/latest-dev.sql
  version.config
Labels: release
