Repository timescale/timescaledb, pull requests merged in 2024-01, with the labels that each got.

#6477 Fix perl modules installation on OS X
  .github/workflows/linux-build-and-test.yaml
Labels: ci, force-auto-backport

#6443 Fix lost concurrent CAgg updates
  .unreleased/fix_6443
  src/scanner.c
  src/scanner.h
  tsl/src/continuous_aggs/invalidation_threshold.c
  tsl/test/isolation/expected/cagg_concurrent_invalidation.out
  tsl/test/isolation/specs/CMakeLists.txt
  tsl/test/isolation/specs/cagg_concurrent_invalidation.spec
Labels: bug

#6479 Backport to 2.13.x: #6443: Fix lost concurrent CAgg updates
  .unreleased/fix_6443
  src/scanner.c
  src/scanner.h
  tsl/src/continuous_aggs/invalidation_threshold.c
  tsl/test/isolation/expected/cagg_concurrent_invalidation.out
  tsl/test/isolation/specs/CMakeLists.txt
  tsl/test/isolation/specs/cagg_concurrent_invalidation.spec
Labels: is-auto-backport

#6487 Remove unused release workflow
  .github/workflows/release.yaml
Labels: ci

#6490 Backport to 2.13.x: #6365: Use numrows_pre_compression in approx row count
  .unreleased/fix_6365
  sql/size_utils.sql
  tsl/test/expected/compression.out
  tsl/test/sql/compression.sql
Labels: is-auto-backport

#6489 Backport to 2.13.x: #6384: Change bgw_log_level to use PGC_SUSET
  .unreleased/fix_6384
  src/guc.c
  tsl/test/expected/bgw_scheduler_control.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/bgw_scheduler_control.sql
Labels: is-auto-backport

#6499 Disable changelog check for backports
  .github/workflows/changelog-check.yaml
Labels: ci

#6507 Handle DST changes in gapfill
  .unreleased/fix_6507
  tsl/src/nodes/gapfill/gapfill_exec.c
  tsl/test/shared/expected/gapfill-13.out
  tsl/test/shared/expected/gapfill-14.out
  tsl/test/shared/expected/gapfill-15.out
  tsl/test/shared/expected/gapfill-16.out
  tsl/test/shared/sql/gapfill.sql.in
Labels: bug

#6510 Backport to 2.13.x: #6507: Handle DST changes in gapfill
  .unreleased/fix_6507
  tsl/src/nodes/gapfill/gapfill_exec.c
  tsl/test/shared/expected/gapfill-13.out
  tsl/test/shared/expected/gapfill-14.out
  tsl/test/shared/expected/gapfill-15.out
  tsl/test/shared/expected/gapfill-16.out
  tsl/test/shared/sql/gapfill.sql.in
Labels: is-auto-backport

#6525 Backport to 2.13.x: #6522: Disallow triggers on CAggs
  .unreleased/fix_6522
  src/process_utility.c
  tsl/test/expected/cagg_errors.out
  tsl/test/sql/cagg_errors.sql
Labels: is-auto-backport

#6534 Backport to 2.13.x: #6531: Fix if_not_exists behavior for CAgg policy with NULL offsets
  .unreleased/bugfix_5688
  tsl/src/bgw_policy/compression_api.c
  tsl/src/bgw_policy/continuous_aggregate_api.c
  tsl/src/bgw_policy/policy_utils.c
  tsl/src/bgw_policy/policy_utils.h
  tsl/src/bgw_policy/retention_api.c
  tsl/test/expected/cagg_policy.out
  tsl/test/sql/cagg_policy.sql
Labels: is-auto-backport

#6559 Remove some multinode leftovers from CAggs
  src/cross_module_fn.c
  src/cross_module_fn.h
  tsl/src/continuous_aggs/insert.c
  tsl/src/continuous_aggs/insert.h
  tsl/src/continuous_aggs/invalidation.c
  tsl/src/continuous_aggs/refresh.c
Labels: multinode, continuous_aggregate, tech-debt

#6560 Change GitHub token for changelog check
  .github/workflows/changelog-check.yaml
  scripts/check_changelog_format.py
Labels: ci
