Repository timescale/timescaledb, pull requests merged in 2025-08, with the labels that each got.

#8452 Remove Ubuntu 20.04 from package test since it's EOL
  .github/workflows/apt-arm-packages.yaml
  .github/workflows/apt-packages.yaml
Labels: ci

#8455 Avoid flakes in materialization check
  .github/workflows/nightly_cloud_smoke_test.yaml
  test/sql/updates/post.continuous_aggs.v2.sql
Labels: Continuous Aggregate

#8471 Fix MERGE behaviour with updated values
  .unreleased/pr_8471
  src/nodes/modify_hypertable_exec.c
  tsl/test/expected/cagg_refresh_using_merge.out
  tsl/test/sql/cagg_refresh_using_merge.sql
Labels: bug

#8473 Backport to 2.21.x: #8471: Fix MERGE behaviour with updated values
  .unreleased/pr_8471
  src/nodes/modify_hypertable_exec.c
  tsl/test/expected/cagg_refresh_using_merge.out
  tsl/test/sql/cagg_refresh_using_merge.sql
Labels: is-auto-backport

#8475 Backport to 2.21.x: #8467: Safeguard against making invalid range types
  tsl/src/continuous_aggs/refresh.c
Labels: is-auto-backport

#8477 Backport to 2.21.x: #8476: Assign correct no_begin for incremental cagg refresh
  tsl/src/continuous_aggs/refresh.c
Labels: is-auto-backport

#6879 Add unsorted decompressed chunk path even if we have sorted ones
  .github/gh_matrix_builder.py
  .github/workflows/linux-32bit-build-and-test.yaml
  .github/workflows/windows-build-and-test.yaml
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/test/expected/compress_bitmap_scan.out
  tsl/test/expected/compress_qualpushdown_saop.out
  tsl/test/expected/compress_sort_transform.out
  tsl/test/expected/compression.out
  tsl/test/expected/compression_ddl.out
  tsl/test/expected/compression_insert.out
  tsl/test/expected/compression_sorted_merge.out
  tsl/test/expected/compression_update_delete-15.out
  tsl/test/expected/compression_update_delete-16.out
  tsl/test/expected/compression_update_delete-17.out
  tsl/test/expected/merge_append_partially_compressed.out
  tsl/test/expected/ordered_append-15.out
  tsl/test/expected/ordered_append-16.out
  tsl/test/expected/ordered_append-17.out
  tsl/test/expected/plan_skip_scan-15.out
  tsl/test/expected/plan_skip_scan-16.out
  tsl/test/expected/plan_skip_scan-17.out
  tsl/test/expected/plan_skip_scan_dagg.out
  tsl/test/expected/recompress_chunk_segmentwise.out
  tsl/test/expected/transparent_decompression-15.out
  tsl/test/expected/transparent_decompression-16.out
  tsl/test/expected/transparent_decompression-17.out
  tsl/test/expected/transparent_decompression_ordered_index-15.out
  tsl/test/expected/transparent_decompression_ordered_index-16.out
  tsl/test/expected/transparent_decompression_ordered_index-17.out
  tsl/test/expected/vector_agg_default.out
  tsl/test/expected/vector_agg_memory.out
  tsl/test/expected/vectorized_aggregation.out
  tsl/test/shared/expected/decompress_join.out
  tsl/test/shared/expected/ordered_append_join-15.out
  tsl/test/shared/expected/ordered_append_join-16.out
  tsl/test/shared/expected/ordered_append_join-17.out
  tsl/test/shared/expected/transparent_decompress_chunk-15.out
  tsl/test/shared/expected/transparent_decompress_chunk-16.out
  tsl/test/shared/expected/transparent_decompress_chunk-17.out
  tsl/test/shared/sql/decompress_join.sql
  tsl/test/sql/compress_bitmap_scan.sql
  tsl/test/sql/recompress_chunk_segmentwise.sql
  tsl/test/sql/vector_agg_memory.sql
Labels: disable-auto-backport

#8484 Add net regression tests to SOLO_TESTS
  test/sql/CMakeLists.txt
Labels: testing, ci, force-auto-backport

#8506 Fix assertion with new CAgg GUCs
  src/guc.c
Labels: bug, Continuous Aggregate, disable-auto-backport

#8511 Update base64 encode/decode functions for PG18
  tsl/src/compression/compression.c
Labels: pg18

#8494 Improve job stat history retention job
  .unreleased/pr_8494
  sql/job_stat_history_log_retention.sql
  sql/updates/reverse-dev.sql
  tsl/test/expected/bgw_job_stat_history.out
  tsl/test/isolation/expected/bgw_job_stat_history_retention_isolation.out
  tsl/test/isolation/specs/CMakeLists.txt
  tsl/test/isolation/specs/bgw_job_stat_history_retention_isolation.spec
  tsl/test/shared/expected/extension.out
  tsl/test/sql/bgw_job_stat_history.sql
Labels: Background Worker, data-retention, jobs

#8516 Check grouping set RTEs for time_bucket in PG18
  tsl/src/compression/compression.c
  tsl/src/continuous_aggs/common.c
  tsl/src/continuous_aggs/finalize.c
  tsl/test/expected/cagg_ddl-15.out
  tsl/test/expected/cagg_ddl-16.out
  tsl/test/expected/cagg_ddl-17.out
  tsl/test/expected/cagg_ddl-18.out
  tsl/test/sql/cagg_ddl.sql.in
Labels: Continuous Aggregate, pg18

#8537 Release artefacts 2.22.0
  sql/CMakeLists.txt
  sql/updates/2.21.3--2.22.0.sql
  sql/updates/2.22.0--2.21.3.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  version.config
Labels: release

#8539 Maintain child em lists in PG 18
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
Labels: planner, pg18

#8541 Remove Continuous Aggregate GUC
  src/guc.c
  tsl/test/expected/cagg_bgw-15.out
  tsl/test/expected/cagg_bgw-16.out
  tsl/test/expected/cagg_bgw-17.out
  tsl/test/expected/cagg_invalidation.out
  tsl/test/expected/exp_cagg_monthly.out
  tsl/test/sql/cagg_bgw.sql.in
  tsl/test/sql/cagg_invalidation.sql
  tsl/test/sql/exp_cagg_monthly.sql
Labels: Continuous Aggregate

#8542 Use active and registered snapshots only
  src/chunk_adaptive.c
  src/chunk_constraint.c
  src/process_utility.c
  src/scanner.c
  src/ts_catalog/continuous_aggs_watermark.c
  tsl/src/compression/compression.c
  tsl/src/compression/compression_dml.c
  tsl/src/compression/recompress.c
  tsl/src/continuous_aggs/insert.c
  tsl/src/continuous_aggs/invalidation_threshold.c
  tsl/src/continuous_aggs/utils.c
Labels: pg18

#8556 Use ATAlterConstraint for ALTER TABLE stmt in PG18
  src/process_utility.c
Labels: pg18

#8555 Serialize WAL-based invalidation processing
  tsl/src/continuous_aggs/invalidation_multi.c
  tsl/test/isolation/expected/cagg_concurrent_process_wal.out
  tsl/test/isolation/specs/CMakeLists.txt
  tsl/test/isolation/specs/cagg_concurrent_process_wal.spec
Labels: bug
