Repository timescale/timescaledb, pull requests merged in 2025-04, with the labels that each got.

#7890 Flush error state before doing anything else
  .unreleased/pr_7890
  src/bgw/job.c
  src/bgw/job_stat.c
  src/chunk.c
  src/telemetry/telemetry.c
  tsl/src/continuous_aggs/utils.c
  tsl/test/src/compression_sql_test.c
Labels: bug

#7896 Forwardport 2.19.1
  .unreleased/pr_7834
  .unreleased/pr_7890
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.19.0--2.19.1.sql
  sql/updates/2.19.1--2.19.0.sql
  version.config
Labels: release, changelog

#7900 Fix PG_SRC_DIR path
  .github/workflows/linux-build-and-test.yaml
Labels: ci

#7889 Add constraint checking test for compression algos
  src/nodes/chunk_dispatch/chunk_dispatch.c
  tsl/test/expected/compression_insert.out
  tsl/test/sql/compression_insert.sql
Labels: testing

#7906 Remove unused structs
  src/chunk_constraint.c
  src/hypertable.c
  tsl/src/nodes/vector_agg/plan.h
Labels: tech-debt

#7905 Remove unused argument from process_compress_table
  src/cross_module_fn.c
  src/cross_module_fn.h
  src/process_utility.c
  tsl/src/compression/create.c
  tsl/src/compression/create.h
  tsl/src/continuous_aggs/options.c
Labels: tech-debt

#7874 Implement SkipScan for distinct aggregates
  .unreleased/pr_7874
  src/guc.c
  src/guc.h
  tsl/src/nodes/skip_scan/planner.c
  tsl/src/nodes/skip_scan/skip_scan.h
  tsl/src/planner.c
  tsl/test/expected/decompress_index.out
  tsl/test/expected/plan_skip_scan_dagg.out
  tsl/test/expected/skip_scan_dagg.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/decompress_index.sql
  tsl/test/sql/include/skip_scan_dagg_query.sql
  tsl/test/sql/include/skip_scan_dagg_query_ht.sql
  tsl/test/sql/plan_skip_scan_dagg.sql
  tsl/test/sql/skip_scan_dagg.sql
Labels: skip-scan

#7910 Fix not using SkipScan over one chunk
  .unreleased/pr_7910
  tsl/src/nodes/skip_scan/planner.c
  tsl/test/expected/plan_skip_scan-15.out
  tsl/test/expected/plan_skip_scan-16.out
  tsl/test/expected/plan_skip_scan-17.out
  tsl/test/expected/plan_skip_scan_dagg.out
  tsl/test/sql/include/skip_scan_dagg_query_ht.sql
Labels: bug, skip-scan

#7911 Don't create hypertable for published tables
  .unreleased/pr_7911
  src/hypertable.c
  test/expected/create_hypertable.out
  test/sql/create_hypertable.sql
Labels: hypertable

#7916 Backport to 2.19.x: #7911: Don't create hypertable for published tables
  .unreleased/pr_7911
  src/hypertable.c
  test/expected/create_hypertable.out
  test/sql/create_hypertable.sql
Labels: is-auto-backport

#7923 Add compression batch size limit GUC
  .unreleased/pr_7923
  src/guc.c
  src/guc.h
  tsl/src/compression/compression.c
  tsl/test/expected/compression.out
  tsl/test/sql/compression.sql
Labels: force-auto-backport

#7902 Fix crash in VectorAgg plan code
  .unreleased/pr_7902
  tsl/src/nodes/columnar_scan/columnar_scan.c
  tsl/src/nodes/decompress_chunk/planner.c
  tsl/src/nodes/decompress_chunk/vector_quals.h
  tsl/src/nodes/vector_agg/plan.c
  tsl/src/nodes/vector_agg/plan_decompress_chunk.c
  tsl/src/nodes/vector_agg/plan_tam.c
  tsl/test/expected/vectorized_aggregation.out
  tsl/test/sql/vectorized_aggregation.sql
Labels: bug

#7919 Require linter to be present when linting is requested
  CMakeLists.txt
Labels: ci

#7925 Backport to 2.19.x: #7902: Fix crash in VectorAgg plan code
  .unreleased/pr_7902
  tsl/src/nodes/columnar_scan/columnar_scan.c
  tsl/src/nodes/decompress_chunk/planner.c
  tsl/src/nodes/decompress_chunk/vector_quals.h
  tsl/src/nodes/vector_agg/plan.c
  tsl/src/nodes/vector_agg/plan_decompress_chunk.c
  tsl/src/nodes/vector_agg/plan_tam.c
  tsl/test/expected/vectorized_aggregation.out
  tsl/test/sql/vectorized_aggregation.sql
Labels: is-auto-backport

#7927 2.19.2 release
  .unreleased/pr_7902
  .unreleased/pr_7911
  .unreleased/pr_7923
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.19.1--2.19.2.sql
  sql/updates/2.19.2--2.19.1.sql
  version.config
Labels: release, changelog

#7928 Don't create hypertable for implicitly published tables
  .unreleased/pr_7928
  src/hypertable.c
  test/expected/create_hypertable.out
  test/sql/create_hypertable.sql
Labels: hypertable

#7913 Allow TAM chunk creation as non-owner
  .unreleased/pr_7913
  tsl/src/compression/compression_storage.c
  tsl/test/expected/hypercore_create.out
  tsl/test/sql/hypercore_create.sql
Labels: bug

#7930 Forwardport 2.19.2
  .unreleased/pr_7902
  .unreleased/pr_7911
  .unreleased/pr_7923
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.19.1--2.19.2.sql
  sql/updates/2.19.2--2.19.1.sql
  version.config
Labels: release, changelog

#7926 Fix flaky rowsecurity test
  test/expected/rowsecurity-15.out
  test/expected/rowsecurity-16.out
  test/expected/rowsecurity-17.out
  test/sql/rowsecurity.sql.in
Labels: flaky-test

#7917 Remove _timescaledb_functions.create_chunk_table
  .unreleased/pr_7917
  sql/chunk.sql
  sql/compat.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  src/chunk.c
  src/chunk.h
  src/cross_module_fn.c
  src/cross_module_fn.h
  tsl/src/chunk_api.c
  tsl/src/chunk_api.h
  tsl/src/init.c
  tsl/test/expected/chunk_api.out
  tsl/test/shared/expected/compat.out
  tsl/test/shared/expected/extension.out
  tsl/test/sql/chunk_api.sql
Labels: tech-debt

#7931 Backport to 2.19.x: #7913: Allow TAM chunk creation as non-owner
  .unreleased/pr_7913
  tsl/src/compression/compression_storage.c
  tsl/test/expected/hypercore_create.out
  tsl/test/sql/hypercore_create.sql
Labels: is-auto-backport

#7934 Manual backport of 7867
  .github/gh_matrix_builder.py
Labels: manual-backport, backported-2.19.x

#7937 Backport to 2.19.x: #7903: Don't recover hard errors for old cagg format
  .unreleased/pr_7903
  tsl/src/hypercore/attr_capture.c
  tsl/src/partialize_finalize.c
  tsl/test/expected/partialize_finalize.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/partialize_finalize.sql
Labels: is-auto-backport

#7893 Don't process hard errors in with-clause parser
  .unreleased/pr_7893
  src/with_clause_parser.c
  test/src/test_with_clause_parser.c
  tsl/test/shared/expected/with_clause_parser.out
  tsl/test/shared/sql/with_clause_parser.sql
Labels: bug

#7943 Backport to 2.19.x: #7893: Don't process hard errors in with-clause parser
  .unreleased/pr_7893
  src/with_clause_parser.c
  test/src/test_with_clause_parser.c
  tsl/test/shared/expected/with_clause_parser.out
  tsl/test/shared/sql/with_clause_parser.sql
Labels: is-auto-backport

#7880 Add experimental support for window functions in caggs
  .unreleased/pr_7880
  src/guc.c
  src/guc.h
  tsl/src/continuous_aggs/common.c
  tsl/test/expected/cagg_ddl-15.out
  tsl/test/expected/cagg_ddl-16.out
  tsl/test/expected/cagg_ddl-17.out
  tsl/test/expected/cagg_errors.out
  tsl/test/sql/cagg_ddl.sql.in
Labels: Continuous Aggregate

#7915 New order option for Incremental CAgg Refresh Policy
  .unreleased/pr_7915
  sql/policy_api.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  tsl/src/bgw_policy/continuous_aggregate_api.c
  tsl/src/bgw_policy/continuous_aggregate_api.h
  tsl/src/bgw_policy/job.c
  tsl/src/bgw_policy/job.h
  tsl/src/bgw_policy/policies_v2.c
  tsl/src/bgw_policy/policies_v2.h
  tsl/src/continuous_aggs/refresh.c
  tsl/src/continuous_aggs/refresh.h
  tsl/test/expected/cagg_refresh_policy_incremental.out
  tsl/test/shared/expected/extension.out
  tsl/test/sql/cagg_refresh_policy_incremental.sql
Labels: Continuous Aggregate, jobs

#7944 Backport to 2.19.x: #7941: Fix column mapping in column stats calculation
  .unreleased/pr_7941
  src/ts_catalog/chunk_column_stats.c
  tsl/test/expected/chunk_column_stats-14.out
  tsl/test/expected/chunk_column_stats-15.out
  tsl/test/expected/chunk_column_stats-16.out
  tsl/test/expected/chunk_column_stats-17.out
  tsl/test/sql/chunk_column_stats.sql.in
Labels: is-auto-backport

#7907 Implement partial decompress for constraint check
  tsl/src/compression/compression.c
  tsl/src/compression/compression.h
  tsl/src/compression/compression_dml.c
Labels: enhancement

#7935 Fix TAM segfault on DELETE using segmentby column
  .unreleased/pr_7935
  tsl/src/hypercore/hypercore_handler.c
  tsl/src/nodes/columnar_scan/columnar_scan.c
Labels: bug

#7933 Simplify version.config
  .github/workflows/apt-arm-packages.yaml
  .github/workflows/apt-packages.yaml
  .github/workflows/docker-images.yaml
  .github/workflows/homebrew.yaml
  .github/workflows/pgspot.yaml
  .github/workflows/rpm-packages.yaml
  .github/workflows/windows-packages.yaml
  CMakeLists.txt
  scripts/changelog/generate.sh
  scripts/test_downgrade.sh
  scripts/test_update_from_version.sh
  scripts/test_updates.sh
  sql/CMakeLists.txt
  sql/updates/README.md
  version.config
Labels: ci, tech-debt

#7952 Remove unused types from custom_type_cache
  src/custom_type_cache.c
  src/custom_type_cache.h
Labels: tech-debt

#7912 Don't capture errors estimating time max spread
  .unreleased/pr_7912
  src/estimate.c
  tsl/test/expected/custom_hashagg.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/custom_hashagg.sql
Labels: bug

#7954 Allow scheduler restarts to be disabled
  .unreleased/pr_7954
  src/loader/bgw_launcher.c
  tsl/test/expected/bgw_scheduler_restart.out
  tsl/test/sql/bgw_scheduler_restart.sql
Labels: bug

#7957 Backport to 2.19.x: #7954: Allow scheduler restarts to be disabled
  .unreleased/pr_7954
  src/loader/bgw_launcher.c
  tsl/test/expected/bgw_scheduler_restart.out
  tsl/test/sql/bgw_scheduler_restart.sql
Labels: is-auto-backport

#7964 Fix serialized hashing for scalar fixed-width by-reference columns
  .github/workflows/linux-32bit-build-and-test.yaml
  .github/workflows/windows-build-and-test.yaml
  .unreleased/uuid-segmentby-grouping-segfault
  tsl/src/nodes/decompress_chunk/compressed_batch.c
  tsl/src/nodes/decompress_chunk/planner.c
  tsl/src/nodes/vector_agg/grouping_policy_batch.c
  tsl/src/nodes/vector_agg/grouping_policy_hash.c
  tsl/src/nodes/vector_agg/hashing/hash_strategy_serialized.c
  tsl/src/planner.c
  tsl/test/expected/vector_agg_uuid_segmentby.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/vector_agg_uuid_segmentby.sql
Labels: bug

#7965 2.19.3 Release
  .unreleased/pr_7893
  .unreleased/pr_7903
  .unreleased/pr_7910
  .unreleased/pr_7912
  .unreleased/pr_7913
  .unreleased/pr_7935
  .unreleased/pr_7941
  .unreleased/pr_7954
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.19.2--2.19.3.sql
  sql/updates/2.19.3--2.19.2.sql
  version.config
Labels: release, changelog

#7979 Rename compression_with_clause to alter_table_with_clause
  src/process_utility.c
  src/ts_catalog/continuous_agg.c
  src/with_clause/CMakeLists.txt
  src/with_clause/alter_table_with_clause.c
  src/with_clause/alter_table_with_clause.h
  tsl/src/compression/create.c
  tsl/src/continuous_aggs/options.c
Labels: refactor

#7980 Move small actions to different runner
  .github/workflows/backport-trigger.yaml
  .github/workflows/backport.yaml
  .github/workflows/catalog-updates-check.yaml
  .github/workflows/changelog-check.yaml
  .github/workflows/issue-handling.yaml
  .github/workflows/pr-approvals.yaml
  .github/workflows/pr-handling.yaml
  .github/workflows/pr-validation.yaml
Labels: ci

#7990 Fixes for the new testgres 1.11.0
  scripts/test_pg_upgrade.py
  test/sql/updates/post.catalog.sql
Labels: ci, force-auto-backport

#7997 Refactor CREATE MATERIALIZED VIEW ... WITH clause
  src/process_utility.c
  src/ts_catalog/continuous_agg.c
  src/ts_catalog/continuous_agg.h
  src/with_clause/CMakeLists.txt
  src/with_clause/create_materialized_view_with_clause.c
  src/with_clause/create_materialized_view_with_clause.h
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/options.c
Labels: Continuous Aggregate, refactor

#7995 Backport to 2.19.x: #7990: Fixes for the new testgres 1.11.0
  scripts/test_pg_upgrade.py
  test/sql/updates/post.catalog.sql
Labels: is-auto-backport

#7994 Adjust HypertableModify to upstream ModifyTable
  src/cross_module_fn.h
  src/import/ht_hypertable_modify.c
  src/import/ht_hypertable_modify.h
  src/nodes/chunk_append/planner.c
  src/nodes/hypertable_modify.c
  src/nodes/hypertable_modify.h
  src/planner/planner.c
  test/expected/delete.out
  test/expected/insert-15.out
  test/expected/insert-16.out
  test/expected/insert-17.out
  test/expected/insert_many.out
  test/expected/insert_single.out
  test/expected/rowsecurity-15.out
  test/expected/rowsecurity-16.out
  test/expected/rowsecurity-17.out
  test/expected/update.out
  test/expected/upsert.out
  tsl/src/compression/compression.h
  tsl/src/compression/compression_dml.c
  tsl/test/expected/chunk_column_stats.out
  tsl/test/expected/compression_insert.out
  tsl/test/expected/compression_update_delete-15.out
  tsl/test/expected/compression_update_delete-16.out
  tsl/test/expected/compression_update_delete-17.out
  tsl/test/expected/hypercore_merge.out
  tsl/test/expected/hypercore_scans.out
  tsl/test/expected/hypercore_update.out
  tsl/test/expected/jit.out
  tsl/test/expected/modify_exclusion.out
  tsl/test/shared/expected/compress_unique_index.out
  tsl/test/shared/expected/compression_dml.out
  tsl/test/shared/expected/constify_now.out
  tsl/test/shared/expected/decompress_tracking.out
  tsl/test/shared/expected/space_constraint.out
Labels: tech-debt

#8019 Install jq explicitly in workflows that use upload_ci_stats
  .github/workflows/linux-32bit-build-and-test.yaml
  .github/workflows/linux-build-and-test.yaml
  .github/workflows/sanitizer-build-and-test.yaml
  .github/workflows/windows-build-and-test.yaml
  scripts/upload_ci_stats.sh
Labels: ci

#8021 Use proper ERRCODE on jobs
  src/bgw/job.c
Labels: Background Worker

#7785 Do DELETE instead of TRUNCATE when locks aren't acquired
  .unreleased/pr_7785
  src/guc.c
  src/guc.h
  tsl/src/compression/compression.c
  tsl/test/expected/compression.out
  tsl/test/isolation/expected/compression_conflicts_iso.out
  tsl/test/isolation/expected/compression_freeze.out
  tsl/test/isolation/specs/compression_conflicts_iso.spec
  tsl/test/isolation/specs/compression_freeze.spec
  tsl/test/t/004_truncate_or_delete_spin_lock.pl
  tsl/test/t/CMakeLists.txt
Labels: Compression

#7976 Include cagg name in timescaledb_information.jobs
  .unreleased/pr_7976
  sql/views.sql
  tsl/test/expected/cagg_migrate.out
  tsl/test/expected/cagg_policy.out
  tsl/test/expected/hypercore_policy.out
  tsl/test/sql/cagg_policy.sql
  tsl/test/sql/hypercore_policy.sql
  tsl/test/sql/include/cagg_migrate_common.sql
Labels: Background Worker, jobs

#8008 Fix compression policy error message.
  .unreleased/pr_8008
  sql/policy_internal.sql
  sql/updates/reverse-dev.sql
  tsl/test/expected/compression_bgw.out
  tsl/test/sql/compression_bgw.sql
Labels: bug, jobs

#7972 Add vectorized filtering to constraint checking
  .unreleased/pr_7972
  tsl/src/compression/compression.c
  tsl/src/compression/compression.h
  tsl/src/compression/compression_dml.c
  tsl/src/compression/compression_dml.h
  tsl/src/nodes/decompress_chunk/compressed_batch.c
  tsl/src/nodes/decompress_chunk/vector_dict.h
  tsl/test/expected/compression_insert.out
  tsl/test/sql/compression_insert.sql
Labels: enhancement

#8012 Fire event triggers on chunk creation
  .unreleased/pr_8012
  src/chunk.c
  src/guc.c
  src/guc.h
  tsl/test/expected/chunk_utils_internal.out
  tsl/test/sql/chunk_utils_internal.sql
Labels: hypertable
