Repository timescale/timescaledb, pull requests merged in 2025-06, with the labels that each got.

#8200 Fix handling NULL compression in DML checks
  .unreleased/pr_8200
  tsl/src/compression/compression.c
  tsl/src/compression/compression.h
  tsl/src/compression/compression_dml.c
  tsl/test/expected/compression_insert.out
  tsl/test/sql/compression_insert.sql
Labels: bug

#8202 Backport to 2.20.x: #8200: Fix handling NULL compression in DML checks
  .unreleased/pr_8200
  tsl/src/compression/compression.c
  tsl/src/compression/compression.h
  tsl/src/compression/compression_dml.c
  tsl/test/expected/compression_insert.out
  tsl/test/sql/compression_insert.sql
Labels: is-auto-backport

#8198 Don't inherit copy methods from postgres
  src/copy.c
  test/expected/copy.out
Labels: refactor

#8203 Release 2.20.2
  .unreleased/pr_8200
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.20.1--2.20.2.sql
  sql/updates/2.20.2--2.20.1.sql
  version.config
Labels: release, changelog

#8197 Use generic license check from cross module instead of duplicated version
  src/cross_module_fn.c
  src/cross_module_fn.h
  src/nodes/chunk_dispatch/chunk_dispatch.c
  tsl/src/compression/compression.h
  tsl/src/compression/compression_dml.c
Labels: tech-debt

#8216 Fix dropped quals bug in skipscan
  .unreleased/pr_8216
  tsl/src/nodes/skip_scan/planner.c
  tsl/test/expected/plan_skip_scan-15.out
  tsl/test/expected/plan_skip_scan-16.out
  tsl/test/expected/plan_skip_scan-17.out
  tsl/test/expected/skip_scan.out
  tsl/test/sql/include/skip_scan_query.sql
Labels: bug, skip-scan

#8222 Use RowShareLock when reading CAgg threshold
  tsl/src/continuous_aggs/invalidation_threshold.c
Labels: Continuous Aggregate

#8187 Allow concurrent CAgg refreshes
  .unreleased/pr_8187
  tsl/src/continuous_aggs/common.h
  tsl/src/continuous_aggs/invalidation.c
  tsl/src/continuous_aggs/refresh.c
  tsl/test/isolation/expected/cagg_concurrent_refresh.out
  tsl/test/isolation/specs/CMakeLists.txt
  tsl/test/isolation/specs/cagg_concurrent_refresh.spec
Labels: Continuous Aggregate

#8231 Rename incremental CAgg refresh policy tests
  tsl/test/expected/cagg_policy_incremental.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/cagg_policy_incremental.sql
Labels: testing, Continuous Aggregate

#8232 Remove unused CAgg policy API code
  tsl/src/bgw_policy/continuous_aggregate_api.c
  tsl/src/bgw_policy/continuous_aggregate_api.h
Labels: Continuous Aggregate, tech-debt

#8240 Adjust compressed_copy isolation test to work on Mac
  tsl/test/isolation/expected/compressed_copy.out
  tsl/test/isolation/specs/compressed_copy.spec
Labels: ci

#8191 Add option to not process hypertable invalidations
  .unreleased/pr_8191
  sql/ddl_api.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  tsl/src/bgw_policy/continuous_aggregate_api.c
  tsl/src/bgw_policy/job.c
  tsl/src/bgw_policy/job.h
  tsl/src/bgw_policy/policies_v2.h
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/refresh.c
  tsl/src/continuous_aggs/refresh.h
  tsl/test/expected/cagg_policy_move.out
  tsl/test/shared/expected/extension.out
  tsl/test/sql/cagg_policy_move.sql
Labels: Continuous Aggregate, docs-needed

#8246 Backport to 2.20.x: #8244: Check for valid dimension on CAgg invalidation trigger cache
  src/process_utility.c
  tsl/src/continuous_aggs/common.c
  tsl/src/continuous_aggs/insert.c
  tsl/src/continuous_aggs/options.c
  tsl/test/expected/cagg_errors.out
  tsl/test/expected/cagg_utils.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/cagg_errors.sql
Labels: is-auto-backport

#8249 Forwardport 2.20.3 Release
  .unreleased/fix_8107
  .unreleased/pr_8211
  .unreleased/pr_8216
  .unreleased/pr_8230
  .unreleased/pr_8236
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.20.2--2.20.3.sql
  sql/updates/2.20.3--2.20.2.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  version.config
Labels: release

#8250 Simplify the check for valid open dimension
  tsl/src/continuous_aggs/insert.c
  tsl/test/expected/cagg_errors.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/cagg_errors.sql
Labels: Continuous Aggregate, tech-debt

#8276 Speed up bgw test runs
  tsl/test/expected/bgw_custom.out
  tsl/test/expected/bgw_job_stat_history.out
  tsl/test/expected/bgw_job_stat_history_errors.out
  tsl/test/sql/bgw_custom.sql
  tsl/test/sql/bgw_job_stat_history.sql
  tsl/test/sql/bgw_job_stat_history_errors.sql
Labels: ci

#8280 Fix typo when checking function result
  tsl/src/compression/compression_dml.c
Labels: coverity

#8294 Fix error with null array in vectorized scalar array operation
  .unreleased/null-array
  tsl/src/nodes/decompress_chunk/compressed_batch.c
  tsl/test/expected/decompress_vector_qual.out
  tsl/test/sql/decompress_vector_qual.sql
Labels: bug

#8297 Backport to 2.20.x: #8294: Fix error with null array in vectorized scalar array operation
  .unreleased/null-array
  tsl/src/nodes/decompress_chunk/compressed_batch.c
  tsl/test/expected/decompress_vector_qual.out
  tsl/test/sql/decompress_vector_qual.sql
Labels: is-auto-backport

#8309 CI & testing improvements
  .github/workflows/nightly_cloud_smoke_test.yaml
  .github/workflows/release_feature_freeze_ceremony.yaml
  .github/workflows/trigger-package-tests.yaml
  scripts/test_update_smoke.sh
Labels: ci

#8314 Loader changes for timescaledb_lake extension
  .unreleased/pr_8314
  src/loader/loader.c
Labels: upgrade-requires-restart
