Repository timescale/timescaledb, pull requests merged in 2025-03, with the labels that each got.

#7768 Remove costing index scan of hypertable parent
  .unreleased/pr_7768
  src/planner/planner.c
Labels: hypertable

#7781 Fix flaky ordered append regression tests
  tsl/test/shared/expected/ordered_append-14.out
  tsl/test/shared/expected/ordered_append-15.out
  tsl/test/shared/expected/ordered_append-16.out
  tsl/test/shared/expected/ordered_append-17.out
  tsl/test/shared/expected/ordered_append_join-14.out
  tsl/test/shared/expected/ordered_append_join-15.out
  tsl/test/shared/expected/ordered_append_join-16.out
  tsl/test/shared/expected/ordered_append_join-17.out
  tsl/test/shared/sql/include/ordered_append_join.sql
  tsl/test/shared/sql/ordered_append.sql.in
  tsl/test/shared/sql/ordered_append_join.sql.in
Labels: planner, flaky-test

#7793 Reduce memory usage when indexing Hypercore TAM
  tsl/src/hypercore/hypercore_handler.c
Labels: table-access-method

#7799 Handle DEFAULT table access name in ALTER TABLE
  .unreleased/pr_7799
  src/process_utility.c
  test/expected/tableam_alter_defaults.out
  test/sql/CMakeLists.txt
  test/sql/tableam_alter_defaults.sql
  tsl/src/hypercore/hypercore_handler.c
  tsl/src/process_utility.c
Labels: bug, table-access-method, ddl

#7802 Add missing thanks to bug fix
  .unreleased/pr_7799
Labels: bug

#7797 Fix cleanup of compression settings with drop cascade
  src/hypertable.c
  src/process_utility.c
  tsl/test/expected/compression_settings.out
  tsl/test/sql/compression_settings.sql
Labels: bug

#7669 Add support for merging compressed chunks
  .unreleased/pr_7669
  tsl/src/chunk.c
  tsl/test/expected/merge_chunks.out
  tsl/test/sql/merge_chunks.sql
Labels: split/merge

#7809 Order merge_chunks test output
  tsl/test/expected/merge_chunks.out
  tsl/test/sql/merge_chunks.sql
Labels: ci

#7813 Use timer mock on Incremental CAgg Refresh policy tests
  tsl/test/expected/cagg_refresh_policy_incremental.out
  tsl/test/sql/cagg_refresh_policy_incremental.sql
Labels: continuous_aggregate, flaky-test, force-auto-backport

#7819 Use timer mock on Incremental CAgg Refresh policy tests take 2
  tsl/test/expected/cagg_refresh_policy_incremental.out
  tsl/test/sql/cagg_refresh_policy_incremental.sql
Labels: continuous_aggregate, flaky-test

#7806 Allow adding unique constraints to compressed chunks
  .unreleased/pr_7806
  src/process_utility.c
  tsl/test/expected/compression_constraints.out
  tsl/test/expected/compression_ddl.out
  tsl/test/expected/compression_errors-14.out
  tsl/test/expected/compression_errors-15.out
  tsl/test/expected/compression_errors-16.out
  tsl/test/expected/compression_errors-17.out
  tsl/test/expected/hypercore_index_btree.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/compression_constraints.sql
  tsl/test/sql/compression_ddl.sql
  tsl/test/sql/compression_errors.sql.in
  tsl/test/sql/hypercore_index_btree.sql
Labels: compression

#7831 Fix Incremental CAgg Refresh policy tests
  tsl/test/expected/cagg_refresh_policy_incremental.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/cagg_refresh_policy_incremental.sql
Labels: continuous_aggregate, flaky-test, force-auto-backport

#7833 Backport to 2.19.x: #7831: Fix Incremental CAgg Refresh policy tests
  tsl/test/expected/cagg_refresh_policy_incremental.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/cagg_refresh_policy_incremental.sql
Labels: is-auto-backport

#7811 Avoid recompression for DESC order during rollup
  tsl/src/compression/api.c
  tsl/test/expected/compression_merge.out
  tsl/test/sql/compression_merge.sql
Labels: bug

#7836 Backport to 2.19.x: #7811: Avoid recompression for DESC order during rollup
  tsl/src/compression/api.c
  tsl/test/expected/compression_merge.out
  tsl/test/sql/compression_merge.sql
Labels: is-auto-backport

#7818 Backport to 2.19.x: #7813: Use timer mock on Incremental CAgg Refresh policy tests
  tsl/test/expected/cagg_refresh_policy_incremental.out
  tsl/test/sql/cagg_refresh_policy_incremental.sql
Labels: is-auto-backport

#7832 Simplify setting chunk_time_interval for caggs
  .unreleased/pr_7832
  src/dimension.c
  src/dimension.h
  src/ts_catalog/continuous_agg.c
  src/ts_catalog/continuous_agg.h
  src/utils.h
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/options.c
  tsl/test/expected/cagg_ddl-14.out
  tsl/test/expected/cagg_ddl-15.out
  tsl/test/expected/cagg_ddl-16.out
  tsl/test/expected/cagg_ddl-17.out
  tsl/test/sql/cagg_ddl.sql.in
Labels: continuous_aggregate

#7841 Rollback incorrect pre-release tests
  .github/workflows/prerelease-tests-on-release-branch.yaml
Labels: testing, ci, force-auto-backport

#7842 Backport of #7841
  .github/workflows/prerelease-tests-on-release-branch.yaml
Labels: testing, ci

#7810 Remove costs from hypercore_scans explain plan
  tsl/test/expected/hypercore_scans.out
  tsl/test/sql/hypercore_scans.sql
Labels: flaky-test, hypercore

#7844 Add GUC to enable exclusive locking recompression
  .unreleased/pr_7844
  src/guc.c
  src/guc.h
  tsl/src/compression/recompress.c
  tsl/test/expected/recompress_chunk_segmentwise.out
  tsl/test/sql/recompress_chunk_segmentwise.sql
Labels: force-auto-backport

#7837 Ignore frozen chunks in compression policy
  .unreleased/pr_7837
  sql/policy_internal.sql
  tsl/src/compression/api.c
  tsl/test/expected/compression_bgw.out
  tsl/test/expected/hypercore_policy.out
  tsl/test/sql/compression_bgw.sql
  tsl/test/sql/hypercore_policy.sql
Labels: bug, force-auto-backport

#7838 Create 2.19.0 release artefacts
  sql/CMakeLists.txt
  sql/updates/2.18.2--2.19.0.sql
  sql/updates/2.19.0--2.18.2.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  version.config
Labels: release

#7846 Backport to 2.19.x: #7837: Ignore frozen chunks in compression policy
  .unreleased/pr_7837
  sql/policy_internal.sql
  tsl/src/compression/api.c
  tsl/test/expected/compression_bgw.out
  tsl/test/expected/hypercore_policy.out
  tsl/test/sql/compression_bgw.sql
  tsl/test/sql/hypercore_policy.sql
Labels: is-auto-backport

#7848 Update wording on logs during recompression
  tsl/src/compression/recompress.c
  tsl/test/isolation/expected/compression_conflicts_iso.out
  tsl/test/isolation/expected/compression_recompress.out
Labels: force-auto-backport

#7849 Backport to 2.19.x: #7848: Update wording on logs during recompression
  tsl/src/compression/recompress.c
  tsl/test/isolation/expected/compression_conflicts_iso.out
  tsl/test/isolation/expected/compression_recompress.out
Labels: is-auto-backport

#7850 Add callback is_current_xact_tuple to Arrow TTS
  .unreleased/pr_7850
  tsl/src/hypercore/arrow_tts.c
Labels: bug

#7829 CHANGELOG for 2.19.0
  CHANGELOG.md
Labels: release, changelog

#7853 Backport from 2.19.0
  .unreleased/hash-grouping-multiple
  .unreleased/pr_7632
  .unreleased/pr_7655
  .unreleased/pr_7665
  .unreleased/pr_7669
  .unreleased/pr_7673
  .unreleased/pr_7701
  .unreleased/pr_7707
  .unreleased/pr_7746
  .unreleased/pr_7764
  .unreleased/pr_7765
  .unreleased/pr_7768
  .unreleased/pr_7786
  .unreleased/pr_7788
  .unreleased/pr_7789
  .unreleased/pr_7790
  .unreleased/pr_7798
  .unreleased/pr_7799
  .unreleased/pr_7806
  .unreleased/pr_7816
  .unreleased/pr_7832
  .unreleased/pr_7837
  .unreleased/pr_7844
  .unreleased/pr_7850
  .unreleased/vectorized-text-grouping
  CHANGELOG.md
  sql/CMakeLists.txt
  sql/updates/2.18.2--2.19.0.sql
  sql/updates/2.19.0--2.18.2.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  version.config
Labels: ci

#7851 Backport to 2.19.x: #7850: Add callback is_current_xact_tuple to Arrow TTS
  .unreleased/pr_7850
  tsl/src/hypercore/arrow_tts.c
Labels: is-auto-backport

#7855 Fix workflow call to docker build
  .github/workflows/release_build_packages.yml
Labels: ci

#7856 Don't run package test as part of prerelease
  .github/workflows/apt-arm-packages.yaml
  .github/workflows/apt-packages.yaml
  .github/workflows/docker-images.yaml
  .github/workflows/homebrew.yaml
  .github/workflows/rpm-packages.yaml
  .github/workflows/windows-packages.yaml
Labels: ci

#7858 Review 2.19 release notes
  CHANGELOG.md
Labels: force-auto-backport, changelog

#7859 Remove multinode perl files
  test/perl/AccessNode.pm
  test/perl/CMakeLists.txt
  test/perl/DataNode.pm
Labels: ci

#7862 Release cache pin when checking for NOT NULL
  .unreleased/pr_7862
  src/process_utility.c
Labels: bug

#7835 Simplify smoke test script
  scripts/test_update_smoke.sh
Labels: testing

#7867 Adjust runner name after change
  .github/gh_matrix_builder.py
Labels: ci

#7834 Avoid unnecessary scheduler restarts
  .unreleased/pr_7834
  src/loader/bgw_launcher.c
  src/loader/loader.c
Labels: bug

#7883 Add CAggs to sqlsmith CI tests
  .github/workflows/sqlsmith.yaml
Labels: testing, Continuous Aggregate, ci

#7814 Automate feature freeze ceremony
  .github/workflows/minor_release.yaml
  .github/workflows/release_feature_freeze_ceremony.yaml
  scripts/changelog/RELEASE_NOTES_HEADER.md.j2
  scripts/changelog/generate.sh
  scripts/merge_changelogs.sh
  scripts/release/build_release_artefacts.sh
  scripts/release/create_minor_release_PR_commit.sh
  scripts/release/create_release_PR_commit.sh
  scripts/test_regressions.sh
Labels: ci

#7888 Simplify ChunkDispatchState handling
  src/nodes/hypertable_modify.c
Labels: tech-debt
