Repository timescale/timescaledb, pull requests merged in 2025-02, with the labels that each got.

#7585 Automate Minor release - Feature Freeze
  .github/workflows/minor_release.yaml
  scripts/release/create_minor_release_PR_commit.sh
  scripts/release/create_minor_release_branch.sh
Labels: release, ci

#7641 Backport to 2.18.x: #7637: Allow EXPLAIN in read-only mode
  .unreleased/pr_7637
  src/process_utility.c
  tsl/test/expected/read_only.out
  tsl/test/shared/expected/extension.out
  tsl/test/sql/read_only.sql
Labels: is-auto-backport

#7639 Prepare VectorAgg exec path to handle arrow slots
  tsl/src/nodes/vector_agg/exec.c
  tsl/src/nodes/vector_agg/exec.h
Labels: table-access-method, hypercore

#7612 Update existing backports in the backport script
  scripts/backport.py
Labels: ci

#7653 Push down orderby scankeys to Hypercore TAM
  .unreleased/pr_7653
  src/guc.c
  src/guc.h
  tsl/src/hypercore/hypercore_handler.c
  tsl/src/hypercore/hypercore_handler.h
  tsl/src/nodes/columnar_scan/columnar_scan.c
  tsl/test/expected/hypercore_dump_restore.out
  tsl/test/expected/hypercore_scans.out
  tsl/test/sql/hypercore_scans.sql
Labels: table-access-method, hypercore

#7656 Remove limitation of compression policy for continuous aggregates
  .unreleased/pr_7656
  tsl/src/bgw_policy/compression_api.c
  tsl/test/expected/cagg_errors.out
  tsl/test/expected/cagg_policy.out
  tsl/test/sql/cagg_errors.sql
  tsl/test/sql/cagg_policy.sql
Labels: continuous_aggregate, jobs, force-auto-backport

#7660 Backport to 2.18.x: #7656: Remove limitation of compression policy for continuous aggregates
  .unreleased/pr_7656
  tsl/src/bgw_policy/compression_api.c
  tsl/test/expected/cagg_errors.out
  tsl/test/expected/cagg_policy.out
  tsl/test/sql/cagg_errors.sql
  tsl/test/sql/cagg_policy.sql
Labels: is-auto-backport

#7661 Optimize quals on segmentby columns in ColumnarScan
  tsl/src/hypercore/arrow_tts.h
  tsl/src/hypercore/hypercore_handler.c
  tsl/src/hypercore/vector_quals.c
  tsl/src/nodes/columnar_scan/columnar_scan.c
  tsl/test/expected/hypercore_scans.out
  tsl/test/sql/hypercore_scans.sql
Labels: table-access-method, hypercore

#7666 Backport to 2.18.x: #7615: Refactor vector qual handling for arrow slots
  tsl/src/hypercore/CMakeLists.txt
  tsl/src/hypercore/arrow_tts.c
  tsl/src/hypercore/arrow_tts.h
  tsl/src/hypercore/vector_quals.c
  tsl/src/hypercore/vector_quals.h
  tsl/src/nodes/columnar_scan/columnar_scan.c
  tsl/src/nodes/columnar_scan/columnar_scan.h
Labels: is-auto-backport

#7670 Backport to 2.18.x: #7653: Push down orderby scankeys to Hypercore TAM
  .unreleased/pr_7653
  src/guc.c
  src/guc.h
  tsl/src/hypercore/hypercore_handler.c
  tsl/src/hypercore/hypercore_handler.h
  tsl/src/nodes/columnar_scan/columnar_scan.c
  tsl/test/expected/hypercore_dump_restore.out
  tsl/test/expected/hypercore_scans.out
  tsl/test/sql/hypercore_scans.sql
Labels: is-auto-backport

#7671 Backport to 2.18.x: #7661: Optimize quals on segmentby columns in ColumnarScan
  tsl/src/hypercore/arrow_tts.h
  tsl/src/hypercore/hypercore_handler.c
  tsl/src/hypercore/vector_quals.c
  tsl/src/nodes/columnar_scan/columnar_scan.c
  tsl/test/expected/hypercore_scans.out
  tsl/test/sql/hypercore_scans.sql
Labels: is-auto-backport

#7664 Adjust windows package test CI
  .github/workflows/windows-packages.yaml
Labels: ci

#7668 Fix flaky bgw scheduler test
  tsl/test/expected/bgw_scheduler_restart.out
  tsl/test/sql/bgw_scheduler_restart.sql
Labels: ci

#7665 Block merging of frozen chunks
  .unreleased/pr_7665
  src/chunk.c
  src/chunk.h
  tsl/src/chunk.c
  tsl/test/expected/merge_chunks.out
  tsl/test/sql/merge_chunks.sql
Labels: split/merge

#7678 Backport to 2.18.x: #7665: Block merging of frozen chunks
  .unreleased/pr_7665
  src/chunk.c
  src/chunk.h
  tsl/src/chunk.c
  tsl/test/expected/merge_chunks.out
  tsl/test/sql/merge_chunks.sql
Labels: is-auto-backport

#7679 Remove outdated references to distributed hypertables
  sql/size_utils.sql
  src/chunk.c
  src/cross_module_fn.c
  src/cross_module_fn.h
  src/dimension.c
  src/hypertable.h
  src/indexing.c
  src/nodes/chunk_dispatch/chunk_insert_state.c
  src/planner/expand_hypertable.c
  src/planner/planner.c
  src/process_utility.c
  src/telemetry/stats.c
  src/telemetry/stats.h
  src/ts_catalog/metadata.h
  tsl/src/chunk.c
  tsl/src/init.c
  tsl/src/partialize_finalize.c
  tsl/src/planner.c
  tsl/src/planner.h
Labels: tech-debt

#7686 Fix vectorized hash agg in GroupAgg mode in reverse order
  .unreleased/hash-groupagg-bug
  tsl/src/nodes/vector_agg/grouping_policy_hash.h
  tsl/src/nodes/vector_agg/plan.c
  tsl/test/expected/vector_agg_groupagg.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/vector_agg_groupagg.sql
Labels: bug

#7688 Backport to 2.18.x: #7686: Fix vectorized hash agg in GroupAgg mode in reverse order
  .unreleased/hash-groupagg-bug
  tsl/src/nodes/vector_agg/grouping_policy_hash.h
  tsl/src/nodes/vector_agg/plan.c
  tsl/test/expected/vector_agg_groupagg.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/vector_agg_groupagg.sql
Labels: is-auto-backport

#7630 Fix wrong crash error message on job history
  sql/pre_install/tables.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  sql/views.sql
  src/bgw/job.c
  src/bgw/job_stat.c
  src/bgw/job_stat_history.c
  src/bgw/job_stat_history.h
  src/utils.h
  tsl/src/continuous_aggs/utils.c
  tsl/test/expected/bgw_job_stat_history.out
  tsl/test/expected/bgw_job_stat_history_errors.out
  tsl/test/expected/bgw_job_stat_history_errors_permissions.out
  tsl/test/sql/bgw_job_stat_history.sql
  tsl/test/sql/bgw_job_stat_history_errors.sql
  tsl/test/sql/bgw_job_stat_history_errors_permissions.sql
Labels: bug, bgw, jobs

#7693 Revert one-reviewer rule for table access method
  .github/workflows/pr-approvals.yaml
Labels: ci

#7696 Fix the umash build
  tsl/src/import/CMakeLists.txt
Labels: force-auto-backport

#7694 Fix ExplainHook breaking call chain
  .unreleased/pr_7694
  tsl/src/hypercore/arrow_cache_explain.c
Labels: bug

#7698 Backport to 2.18.x: #7694: Fix ExplainHook breaking call chain
  .unreleased/pr_7694
  tsl/src/hypercore/arrow_cache_explain.c
Labels: is-auto-backport

#7712 Respect other extensions' ExecutorStart hooks
  .unreleased/pr_7712
  tsl/src/hypercore/attr_capture.c
Labels: bug, hypercore

#7715 Backport to 2.18.x: #7712: Respect other extensions' ExecutorStart hooks
  .unreleased/pr_7712
  tsl/src/hypercore/attr_capture.c
Labels: is-auto-backport

#7711 Load hypercore handler eagerly
  .unreleased/pr_7711
  src/cross_module_fn.c
  src/init.c
  tsl/test/expected/hypercore.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/hypercore.sql
Labels: bug, loader, hypercore

#7699 Add GUC for TAM arrow cache size
  src/guc.c
  src/guc.h
  tsl/src/hypercore/arrow_cache.c
  tsl/src/hypercore/arrow_cache.h
  tsl/test/expected/hypercore.out
  tsl/test/sql/hypercore.sql
Labels: force-auto-backport

#7721 Move FK query handling into own function
  src/planner/planner.c
Labels: tech-debt

#7728 Backport to 2.18.x: #7630: Fix wrong crash error message on job history
  sql/pre_install/tables.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  sql/views.sql
  src/bgw/job.c
  src/bgw/job_stat.c
  src/bgw/job_stat_history.c
  src/bgw/job_stat_history.h
  src/utils.h
  tsl/src/continuous_aggs/utils.c
  tsl/test/expected/bgw_job_stat_history.out
  tsl/test/expected/bgw_job_stat_history_errors.out
  tsl/test/expected/bgw_job_stat_history_errors_permissions.out
  tsl/test/sql/bgw_job_stat_history.sql
  tsl/test/sql/bgw_job_stat_history_errors.sql
  tsl/test/sql/bgw_job_stat_history_errors_permissions.sql
Labels: manual-backport

#7727 RTA updates
  README.md
Labels: force-auto-backport

#7730 Backport to 2.18.x: #7727: RTA updates
  README.md
Labels: is-auto-backport

#7731 Backport to 2.18.x: #7719: Better report message in check sql script
  scripts/check_sql_script.py
Labels: is-auto-backport

#7734 Backport to 2.18.x: #7722: Add thanks for executor hook fixes
  .unreleased/pr_7712
Labels: is-auto-backport

#7732 Trigger the backports when a release branch is updated
  .github/workflows/backport-trigger.yaml
  .github/workflows/backport.yaml
Labels: ci

#7718 Run the regression tests on ARM
  .github/gh_matrix_builder.py
  .github/workflows/linux-build-and-test.yaml
  test/expected/bgw_launcher.out
  test/sql/bgw_launcher.sql
  test/sql/include/bgw_launcher_utils.sql
  test/sql/include/bgw_launcher_utils_cleanup.sql
  tsl/CMakeLists.txt
  tsl/src/CMakeLists.txt
Labels: ci

#7737 Backport to 2.18.x: #7725: Silence compiler warning about macro arguments
  tsl/src/chunk.c
Labels: is-auto-backport

#7717 Backport to 2.18.x: #7711: Load hypercore handler eagerly
  .unreleased/pr_7711
  src/cross_module_fn.c
  src/init.c
  tsl/test/expected/hypercore.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/hypercore.sql
Labels: is-auto-backport

#7733 Backport to 2.18.x: #7695: Block dropping internal compressed chunks with `drop_chunk()`
  .unreleased/pr_7695
  src/chunk.c
  tsl/test/expected/compression_ddl.out
  tsl/test/sql/compression_ddl.sql
Labels: is-auto-backport

#7720 Backport to 2.18.x: #7699: Add GUC for TAM arrow cache size
  src/guc.c
  src/guc.h
  tsl/src/hypercore/arrow_cache.c
  tsl/src/hypercore/arrow_cache.h
  tsl/test/expected/hypercore.out
  tsl/test/sql/hypercore.sql
Labels: is-auto-backport

#7749 Backport to 2.18.x: #7697: Schedule run on release-branch.
  .github/workflows/apt-arm-packages.yaml
  .github/workflows/apt-packages.yaml
  .github/workflows/docker-images.yaml
  .github/workflows/homebrew.yaml
  .github/workflows/rpm-packages.yaml
  .github/workflows/windows-packages.yaml
Labels: is-auto-backport

#7758 Reduce privilege requirement in bgw_security
  tsl/src/bgw_policy/job_api.c
  tsl/test/expected/bgw_security.out
  tsl/test/sql/bgw_security.sql
Labels: testing

#7729 Fix flaky job crash log TAP test
  tsl/test/t/001_job_crash_log.pl
Labels: flaky-test, jobs

#7746 Block TAM rewrites with incompatible GUC setting
  .unreleased/pr_7746
  src/guc.c
  tsl/src/hypercore/hypercore_handler.c
  tsl/test/expected/hypercore_create.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/hypercore_create.sql
Labels: bug

#7769 Backport to 2.18.x: #7746: Block TAM rewrites with incompatible GUC setting
  .unreleased/pr_7746
  src/guc.c
  tsl/src/hypercore/hypercore_handler.c
  tsl/test/expected/hypercore_create.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/hypercore_create.sql
Labels: is-auto-backport

#6990 Add table mappings to compression settings
  sql/pre_install/tables.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  sql/views.sql
  src/chunk.c
  src/chunk.h
  src/nodes/chunk_dispatch/chunk_insert_state.c
  src/nodes/chunk_dispatch/chunk_insert_state.h
  src/process_utility.c
  src/ts_catalog/catalog.c
  src/ts_catalog/catalog.h
  src/ts_catalog/compression_settings.c
  src/ts_catalog/compression_settings.h
  tsl/src/compression/api.c
  tsl/src/compression/compression.c
  tsl/src/compression/compression.h
  tsl/src/compression/compression_dml.c
  tsl/src/compression/create.c
  tsl/src/compression/create.h
  tsl/src/compression/recompress.c
  tsl/src/hypercore/hypercore_handler.c
  tsl/src/nodes/decompress_chunk/decompress_chunk.c
  tsl/src/nodes/decompress_chunk/decompress_chunk.h
  tsl/test/expected/cagg_ddl-14.out
  tsl/test/expected/cagg_ddl-15.out
  tsl/test/expected/cagg_ddl-16.out
  tsl/test/expected/cagg_ddl-17.out
  tsl/test/expected/compression.out
  tsl/test/expected/compression_ddl.out
  tsl/test/expected/compression_defaults.out
  tsl/test/expected/compression_errors-14.out
  tsl/test/expected/compression_errors-15.out
  tsl/test/expected/compression_errors-16.out
  tsl/test/expected/compression_errors-17.out
  tsl/test/expected/compression_sequence_num_removal.out
  tsl/test/expected/compression_settings.out
  tsl/test/expected/hypercore_create.out
  tsl/test/sql/compression_sequence_num_removal.sql
  tsl/test/t/002_logrepl_decomp_marker.pl
Labels: compression, tech-debt

#7750 Remove useless function from regression tests
  tsl/src/continuous_aggs/utils.c
  tsl/test/expected/cagg_utils.out
  tsl/test/sql/cagg_utils.sql
Labels: tech-debt, force-auto-backport

#7764 Fix compression settings handling in Hypercore TAM
  .unreleased/pr_7764
  sql/updates/post-update.sql
  tsl/src/hypercore/hypercore_handler.c
  tsl/src/hypercore/hypercore_handler.h
  tsl/test/expected/hypercore_create.out
  tsl/test/sql/hypercore_create.sql
Labels: bug, table-access-method
