Repository timescale/timescaledb, pull requests merged in 2025-07, with the labels that each got.

#8323 Fix DML issue with expression indexes and BHS
  .unreleased/pr_8323
  tsl/src/compression/compression_dml.c
  tsl/test/expected/compression_update_delete-15.out
  tsl/test/expected/compression_update_delete-16.out
  tsl/test/expected/compression_update_delete-17.out
  tsl/test/sql/compression_update_delete.sql.in
Labels: bug

#8274 Allow creating concurrent CAgg refresh policies
  .unreleased/pr_8274
  src/time_utils.c
  tsl/src/bgw_policy/continuous_aggregate_api.c
  tsl/src/bgw_policy/continuous_aggregate_api.h
  tsl/src/bgw_policy/job.c
  tsl/src/bgw_policy/job_api.c
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/refresh.c
  tsl/src/continuous_aggs/refresh.h
  tsl/test/expected/cagg_errors.out
  tsl/test/expected/cagg_policy.out
  tsl/test/expected/cagg_policy_concurrent.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/cagg_policy.sql
  tsl/test/sql/cagg_policy_concurrent.sql
Labels: Continuous Aggregate, jobs

#8326 Bump version to 2.21.0
  sql/CMakeLists.txt
  sql/updates/2.20.3--2.21.0.sql
  sql/updates/2.21.0--2.20.3.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  version.config
Labels: release

#8328 Fix isBackgroundWorker compatibility for PG18
  src/bgw/job.c
Labels: pg18

#8329 Fix cluster_rel signature for PG18
  src/process_utility.c
Labels: pg18

#8339 Improved pre & post release actions
  .github/workflows/nightly_cloud_smoke_test.yaml
  .github/workflows/release_post_release_ceremony.yaml
Labels: ci

#8338 Refactor string output for Postgres type code
  src/chunk.c
  src/chunk_constraint.c
  src/chunk_tuple_routing.c
  src/dimension.c
  src/jsonb_utils.c
  src/nodes/chunk_dispatch/chunk_dispatch.c
  src/ts_catalog/chunk_column_stats.c
  src/utils.c
  src/utils.h
  src/with_clause/with_clause_parser.c
  tsl/src/bgw_policy/job.c
  tsl/src/bgw_policy/job.h
  tsl/src/chunk.c
  tsl/src/continuous_aggs/common.c
  tsl/src/continuous_aggs/refresh.c
Labels: tech-debt

#8342 Fix forced CAgg refresh
  tsl/src/continuous_aggs/invalidation.c
  tsl/test/expected/cagg_refresh.out
  tsl/test/expected/cagg_refresh_using_merge.out
  tsl/test/sql/include/cagg_refresh_common.sql
Labels: bug, Continuous Aggregate, force-auto-backport, force-auto-backport-workflow

#8343 Fix flaky cagg_plugin
  tsl/test/sql/CMakeLists.txt
Labels: flaky-test

#8350 Backport to 2.21.x: Fix forced CAgg refresh
  tsl/src/continuous_aggs/invalidation.c
  tsl/test/expected/cagg_refresh.out
  tsl/test/expected/cagg_refresh_using_merge.out
  tsl/test/sql/include/cagg_refresh_common.sql
Labels: manual-backport

#8353 Backport to 2.20.x: #8341: Allow quick migration from hypercore TAM to (columnstore) heap
  .unreleased/pr_8341
  tsl/src/compression/api.c
  tsl/src/hypercore/utils.c
  tsl/src/hypercore/utils.h
  tsl/src/process_utility.c
  tsl/test/expected/hypercore.out
  tsl/test/expected/hypercore_create.out
  tsl/test/sql/hypercore.sql
  tsl/test/sql/hypercore_create.sql
Labels: is-auto-backport

#8355 Backport to 2.21.x: #8341: Allow quick migration from hypercore TAM to (columnstore) heap
  .unreleased/pr_8341
  tsl/src/compression/api.c
  tsl/src/hypercore/utils.c
  tsl/src/hypercore/utils.h
  tsl/src/process_utility.c
  tsl/test/expected/hypercore.out
  tsl/test/expected/hypercore_create.out
  tsl/test/sql/hypercore.sql
  tsl/test/sql/hypercore_create.sql
Labels: is-auto-backport

#8356 Bump version.config on main
  .github/workflows/release_feature_freeze_ceremony.yaml
  .github/workflows/release_post_release_ceremony.yaml
Labels: ci

#8359 Move chunk splitting code to its own file
  tsl/src/CMakeLists.txt
  tsl/src/chunk.c
  tsl/src/chunk_split.c
Labels: refactor

#8366 Improve update test error information
  .github/workflows/update-test.yaml
  scripts/test_updates.sh
Labels: ci

#8378 Make pgspot no longer complain about CREATE OR REPLACE FUNCTION
  .github/workflows/pgspot.yaml
Labels: ci

#8377 Remove extensions no longer used from CI
  .github/gh_matrix_builder.py
  .github/workflows/linux-32bit-build-and-test.yaml
  .github/workflows/sanitizer-build-and-test.yaml
  .github/workflows/snapshot-abi.yaml
  tsl/test/isolation/specs/split_chunk_concurrent.spec
Labels: ci

#8379 Don't use \dx in tests
  test/expected/loader-oss.out
  test/expected/loader-tsl.out
  test/sql/loader.sql.in
  test/sql/utils/testsupport.sql
  tsl/test/expected/telemetry_stats.out
Labels: pg18

#8277 Fix net test
  .github/gh_matrix_builder.py
  .github/workflows/linux-32bit-build-and-test.yaml
  .github/workflows/windows-build-and-test.yaml
  test/sql/CMakeLists.txt
  test/src/net/test_conn.c
Labels: ci

#8375 Remove plan_tam.c
  tsl/src/nodes/vector_agg/plan_tam.c
Labels: tech-debt

#8388 Trigger docs action after release
  .github/workflows/release_post_release_ceremony.yaml
Labels: ci

#8403 Release 2.21.1
  .unreleased/pr_8336
  CHANGELOG.md
Labels: release, changelog

#8404 Bump version to 2.21.1
  sql/CMakeLists.txt
  sql/updates/2.21.0--2.21.1.sql
  sql/updates/2.21.1--2.21.0.sql
Labels: release

#8405 Release 2.21.1 (#8403)
  .unreleased/pr_8336
  CHANGELOG.md
Labels: release, changelog

#8415 Ping on add of specific labels
  .github/workflows/label-handling.yaml
Labels: ci

#8421 Test for a bumped version on loader change
  .github/workflows/loader_check.yml
Labels: ci

#8420 Disable poor compression ratio in nightly tests
  .github/workflows/nightly_cloud_smoke_test.yaml
  scripts/test_update_smoke.sh
Labels: ci

#8430 Fix and improve release actions
  .github/workflows/release_build_packages.yml
  .github/workflows/release_feature_freeze_ceremony.yaml
  .github/workflows/release_post_release_ceremony.yaml
Labels: ci, force-auto-backport-workflow
