Repository timescale/timescaledb, pull requests merged in 2025-01, with the labels that each got.

#7558 Remove no longer supported bitnami images from CI
  .github/workflows/docker-images.yaml
Labels: ci

#7570 Remove redundant PG17 entry from build matrix
  .github/workflows/linux-32bit-build-and-test-ignored.yaml
  .github/workflows/linux-32bit-build-and-test.yaml
Labels: ci

#7571 Bump pgspot version to 0.9.0
  .github/workflows/pgspot.yaml
Labels: ci

#6868 Remove permission section from pr handling workflow
  .github/workflows/pr-handling.yaml
Labels: ci

#7567 Edit release notes
  .unreleased/pr_6901
  .unreleased/pr_7104
  .unreleased/pr_7271
  .unreleased/pr_7295
  .unreleased/pr_7378
  .unreleased/pr_7390
  .unreleased/pr_7409
  .unreleased/pr_7411
  .unreleased/pr_7412
  .unreleased/pr_7426
  .unreleased/pr_7432
  .unreleased/pr_7434
  .unreleased/pr_7443
  .unreleased/pr_7455
  .unreleased/pr_7482
  .unreleased/pr_7486
  .unreleased/pr_7488
  .unreleased/pr_7514
  .unreleased/pr_7557
  .unreleased/resolve-vars
  .unreleased/vectorized-agg-filter
  .unreleased/vectorized-grouping-one-fixed
Labels: release

#7572 Add missing ORDER BY clause to compression_ddl_iso test
  tsl/test/isolation/expected/compression_ddl_iso.out
  tsl/test/isolation/specs/compression_ddl_iso.spec
Labels: ci

#7575 Add missing elog(DEBUG2,...) after refactoring
  tsl/src/continuous_aggs/materialize.c
Labels: continuous_aggregate, tech-debt

#7517 Fix CAgg migration performance regression
  .unreleased/pr_7517
  sql/cagg_migrate.sql
  sql/updates/reverse-dev.sql
  tsl/test/expected/cagg_migrate.out
  tsl/test/shared/expected/compat.out
  tsl/test/shared/expected/extension.out
Labels: performance, continuous_aggregate, migration, force-auto-backport

#7580 Disable IndexOnlyScans for ChunkAppend tests
  test/expected/append-14.out
  test/expected/append-15.out
  test/expected/append-16.out
  test/expected/append-17.out
  test/sql/append.sql.in
Labels: testing, flaky-test, ci

#7565 Add hint when hypertable creation fails
  .unreleased/pr_7565
  src/indexing.c
  test/expected/create_hypertable.out
  test/sql/create_hypertable.sql
Labels: hypertable

#7577 Relax lock when updating job history information
  src/bgw/job_stat_history.c
Labels: bgw, locking, jobs

#7584 Fix NaN-handling for vectorized aggregation
  .unreleased/pr_7584
  tsl/src/nodes/vector_agg/function/minmax_arithmetic_single.c
  tsl/src/nodes/vector_agg/function/minmax_templates.c
  tsl/test/expected/vector_agg_functions.out
  tsl/test/sql/vector_agg_functions.sql
Labels: bug

#7527 Restart scheduler on error
  .github/gh_matrix_builder.py
  .unreleased/pr_7527
  src/bgw/scheduler.c
  src/compat/compat.h
  src/guc.c
  src/guc.h
  src/loader/bgw_launcher.c
  src/loader/bgw_launcher.h
  src/loader/loader.c
  test/expected/bgw_launcher.out
  test/pgtest/CMakeLists.txt
  test/sql/bgw_launcher.sql
  test/sql/include/bgw_launcher_utils.sql
  tsl/test/expected/bgw_scheduler_control.out
  tsl/test/expected/bgw_scheduler_restart.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/bgw_scheduler_restart.sql
Labels: bgw

#7588 Transfer visibility when copying arrow tuple slot
  tsl/src/hypercore/arrow_tts.c
Labels: hypercore

#7589 Fix ABI issue when upgrading PG from 15.3 to 15.4+
  tsl/src/compression/api.c
Labels: ci

#7521 Add optional `force` argument to `refresh_continuous_aggregate`
  .unreleased/pr_7521
  sql/ddl_api.sql
  sql/updates/latest-dev.sql
  sql/updates/reverse-dev.sql
  tsl/src/bgw_policy/job.c
  tsl/src/continuous_aggs/create.c
  tsl/src/continuous_aggs/invalidation.c
  tsl/src/continuous_aggs/invalidation.h
  tsl/src/continuous_aggs/refresh.c
  tsl/src/continuous_aggs/refresh.h
  tsl/test/expected/cagg_refresh.out
  tsl/test/expected/cagg_refresh_using_merge.out
  tsl/test/expected/chunk_utils_internal.out
  tsl/test/shared/expected/extension.out
  tsl/test/sql/chunk_utils_internal.sql
  tsl/test/sql/include/cagg_refresh_common.sql
Labels: continuous_aggregate

#7436 Add index creation on orderby columns
  .unreleased/pr_7436
  tsl/src/compression/api.c
  tsl/src/compression/compression_storage.c
  tsl/test/expected/compression_bgw.out
  tsl/test/expected/compression_ddl.out
  tsl/test/expected/compression_indexcreate.out
  tsl/test/expected/compression_insert.out
  tsl/test/expected/compression_qualpushdown.out
  tsl/test/expected/compression_sequence_num_removal.out
  tsl/test/expected/compression_update_delete-14.out
  tsl/test/expected/compression_update_delete-15.out
  tsl/test/expected/compression_update_delete-16.out
  tsl/test/expected/compression_update_delete-17.out
  tsl/test/expected/hypercore_vacuum.out
  tsl/test/expected/telemetry_stats.out
  tsl/test/expected/vector_agg_default.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/compression_indexcreate.sql
Labels: compression

#7574 Add error for DELETE triggers with transition tables
  src/hypertable.c
  src/hypertable.h
  src/process_utility.c
  tsl/src/compression/create.c
  tsl/test/expected/compression_trigger.out
  tsl/test/expected/hypercore_trigger.out
  tsl/test/sql/CMakeLists.txt
  tsl/test/sql/compression_trigger.sql
  tsl/test/sql/hypercore_trigger.sql
Labels: compression

#7592 Add chunk ranges to constify_now test and remove costs
  tsl/test/shared/expected/constify_now.out
  tsl/test/shared/sql/constify_now.sql
Labels: ci

#7566 Improve transaction check in refresh_cagg
  .unreleased/pr_7566
  src/process_utility.c
  src/process_utility.h
  tsl/src/continuous_aggs/refresh.c
  tsl/test/expected/cagg_refresh.out
  tsl/test/expected/cagg_refresh_using_merge.out
  tsl/test/sql/include/cagg_refresh_common.sql
Labels: bug, continuous_aggregate

#7604 Bump version to 2.19.0-dev
  scripts/backport.py
  version.config
Labels: ci

#7607 Fix the backport script
  scripts/backport.py
Labels: ci

#7615 Refactor vector qual handling for arrow slots
  tsl/src/hypercore/CMakeLists.txt
  tsl/src/hypercore/arrow_tts.c
  tsl/src/hypercore/arrow_tts.h
  tsl/src/hypercore/vector_quals.c
  tsl/src/hypercore/vector_quals.h
  tsl/src/nodes/columnar_scan/columnar_scan.c
  tsl/src/nodes/columnar_scan/columnar_scan.h
Labels: hypercore

#7620 Fix downgrade path for 2.18.0
  .github/workflows/update-test.yaml
  cmake/GenerateScripts.cmake
Labels: downgrade

#7621 Allow more workflows to be triggered by github ui
  .github/workflows/abi.yaml
  .github/workflows/apt-arm-packages.yaml
  .github/workflows/apt-packages.yaml
  .github/workflows/coverity.yaml
  .github/workflows/docker-images.yaml
  .github/workflows/homebrew.yaml
  .github/workflows/libfuzzer.yaml
  .github/workflows/rpm-packages.yaml
  .github/workflows/sanitizer-build-and-test.yaml
  .github/workflows/snapshot-abi.yaml
  .github/workflows/update-test.yaml
  .github/workflows/windows-build-and-test.yaml
  .github/workflows/windows-packages.yaml
Labels: ci

#7624 Add ci check for idempotency in sql scripts
  .github/workflows/catalog-updates-check.yaml
  scripts/check_sql_script.py
  scripts/check_updates_ast.py
  sql/metadata.sql
Labels: ci

#7623 Remove some dead code from downgrade script generation
  cmake/GenerateScripts.cmake
Labels: downgrade

#7631 Update gitignore
  .gitignore
Labels: tech-debt, force-auto-backport

#7600 Fix lock order when dropping index
  .unreleased/pr_7600
  src/chunk_index.c
  tsl/test/isolation/expected/deadlock_drop_index_vacuum.out
  tsl/test/isolation/specs/CMakeLists.txt
  tsl/test/isolation/specs/deadlock_drop_index_vacuum.spec
Labels: hypertable, locking

#7634 Refactor VectorAgg to use TupleTableSlot interface
  tsl/src/nodes/vector_agg/exec.c
  tsl/src/nodes/vector_agg/grouping_policy.h
  tsl/src/nodes/vector_agg/grouping_policy_batch.c
  tsl/src/nodes/vector_agg/grouping_policy_hash.c
  tsl/src/nodes/vector_agg/hashing/batch_hashing_params.h
  tsl/src/nodes/vector_agg/hashing/hash_strategy_common.c
  tsl/src/nodes/vector_agg/hashing/hash_strategy_impl.c
  tsl/src/nodes/vector_agg/hashing/hash_strategy_impl_single_fixed_key.c
  tsl/src/nodes/vector_agg/hashing/hashing_strategy.h
  tsl/src/nodes/vector_agg/vector_slot.h
Labels: table-access-method, hypercore

#7640 Add actionable hints to update script checker
  .github/workflows/catalog-updates-check.yaml
  scripts/check_updates.py
Labels: ci

#7637 Allow EXPLAIN in read-only mode
  .unreleased/pr_7637
  src/process_utility.c
  tsl/test/expected/read_only.out
  tsl/test/sql/read_only.sql
Labels: bug
